### PR TITLE
Introducing capability to print xml in monochrome

### PR DESCRIPTION
**Pull request by rocknes**
Tested the following scenarios

Environment variable USE_COLORED_OUPUT not set
------------------------------------------------------
vcd info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Colored output
vcd --colorized info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Colored output
vcd --no-colorized info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Monochrome output

Environment variable USE_COLORED_OUPUT is set to 0
------------------------------------------------------
vcd info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 :  Monochrome output
vcd --colorized info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Colored output
vcd --no-colorized info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Monochrome output

Environment variable USE_COLORED_OUPUT is set to 1
------------------------------------------------------
vcd info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 :  Colored output
vcd --colorized info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Colored output
vcd --no-colorized info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Monochrome output

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/155)

### CODE REVIEW

**Comment by pacogomez** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/utils.py, line 345 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/155#-L0lXmsl6QK0uHJFnmYE:-L0lXmsl6QK0uHJFnmYF:bu53klc) ([raw file](https://github.com/vmware/pyvcloud/blob/176d1ec1b4e85988a6e32a96c40622f57471b349/pyvcloud/vcd/utils.py#L345)):*
> ```Python
> def stdout_xml(the_xml, is_colorized=True):
>     message = str(etree.tostring(the_xml, pretty_print=True), 'utf-8')
>     if is_colorized is True:
> ```

`is True` is redundant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/155)*

**Comment by pacogomez** [comment]
see comments below

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/155#-:-L0lYCMUhkYzsC3X0pZp:b-4awlop)*

**Comment by rocknes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/utils.py, line 345 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/155#-L0lXmsl6QK0uHJFnmYE:-L0lYnX9ewH8pThmOeIN:bss4a2b) ([raw file](https://github.com/vmware/pyvcloud/blob/176d1ec1b4e85988a6e32a96c40622f57471b349/pyvcloud/vcd/utils.py#L345)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

`is True` is redundant
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/155)*

**Comment by pacogomez** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/155#-:-L0lYtEqLCf9nCk9wuYQ:bnfp4nl)*

**Comment by anusuyar** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/155)*

**Comment by pacogomez** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/155#-:-L0lx1kyuFba3Y43NJuF:bnfp4nl)*

**Comment by anusuyar** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/155#-:-L0p_5bUP71RAV3fkhTT:bnfp4nl)*

**Pull request merged**
