### PR TITLE
VCDA-408 Undeploy a VM, VCDA-362 Delete VMs

### PR DESCRIPTION
**Pull request by pacogomez**
To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line:
Undeploy a VM, Delete VMs

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Details are included in the commit messages

- (Optional) Names of reviewers using @ sign + name
@sompa @anusuyar @sahithi @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/165)

### CODE REVIEW

**Comment by sahithi** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pyvcloud/vcd/vapp.py, line 493 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L22lQlnGI_17uOH_CDS:-L22lQlnGI_17uOH_CDT:bnspwh0) ([raw file](https://github.com/vmware/pyvcloud/blob/73289bf82fd1d6771bb8af0b7235b81e0512d57f/pyvcloud/vcd/vapp.py#L493)):*
> ```Python
> 
>         params = E.RecomposeVAppParams()
>         for name in names:
> ```

If just a single string "vm1" is passed to this method, for loop will execute for each character of the string. Please add array check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/165)*

**Comment by sahithi** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/165)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pyvcloud/vcd/vapp.py, line 493 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L22lQlnGI_17uOH_CDS:-L2383YWdub8pPYK5gZ9:b-cp8jtv) ([raw file](https://github.com/vmware/pyvcloud/blob/73289bf82fd1d6771bb8af0b7235b81e0512d57f/pyvcloud/vcd/vapp.py#L493)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

If just a single string "vm1" is passed to this method, for loop will execute for each character of the string. Please add array check.
</blockquote></details>

in general we don't validate parameters and the doc says `array` type, but I will add a check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/165)*

**Comment by rocknes** [comment]
Review status: 13 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[tox.ini, line 2 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L24U-Mea8Addu3d0ngB:-L24U-Mea8Addu3d0ngC:b-8xjlj5) ([raw file](https://github.com/vmware/pyvcloud/blob/b0d1bf75e4106a5960e187abe7a30f478b402c22/tox.ini#L2)):*
> ```INI
> [flake8]
> import-order-style = smarkets
> ```

I think we can use pep8 for this one. 

---

*[pyvcloud/vcd/client.py, line 24 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L24UECfIsVr3k6nnNvw:-L24UECfIsVr3k6nnNvx:bjw82dv) ([raw file](https://github.com/vmware/pyvcloud/blob/b0d1bf75e4106a5960e187abe7a30f478b402c22/pyvcloud/vcd/client.py#L24)):*
> ```Python
> from datetime import timedelta
> 
> import requests
> ```

shouldn't request follow lxml?

---

*[pyvcloud/vcd/client.py, line 416 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L24VOZ6c4c9HtkCjReB:-L24VOZ6c4c9HtkCjReC:bcumf2l) ([raw file](https://github.com/vmware/pyvcloud/blob/b0d1bf75e4106a5960e187abe7a30f478b402c22/pyvcloud/vcd/client.py#L416)):*
> ```Python
>             callback=callback)
> 
>     def wait_for_status_or_raise(self,
> ```

Can you please explain how is this function different from wait_for_status sans the default param values?
If they are the same, then we should collapse the implementation.

---

*[pyvcloud/vcd/vm.py, line 124 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L24X1Kryyo1yJnBllPx:-L24X1Kryyo1yJnBllPy:b-u1ftmx) ([raw file](https://github.com/vmware/pyvcloud/blob/b0d1bf75e4106a5960e187abe7a30f478b402c22/pyvcloud/vcd/vm.py#L124)):*
> ```Python
> 
>         :return:  A :class:`lxml.objectify.StringElement` object describing the
>             asynchronous task that operates the VM.
> ```

nit : operates on the VM?

---

*[tests/vcd_vm.py, line 162 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L24W52Nrd_Tu8lsrXIT:-L24W52Nrd_Tu8lsrXIU:b90qplj) ([raw file](https://github.com/vmware/pyvcloud/blob/b0d1bf75e4106a5960e187abe7a30f478b402c22/tests/vcd_vm.py#L162)):*
> ```Python
>         org = Org(self.client, resource=logged_in_org)
>         v = org.get_vdc(self.config['vcd']['vdc'])
>         vdc = VDC(self.client, href=v.get('href'))
> ```

I believe 'v' is the vdc_resource, we can assign it directly and save one rest call to vcd

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/165)*

**Comment by pacogomez** [comment]
Review status: 13 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[tox.ini, line 2 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L24U-Mea8Addu3d0ngB:-L25P8gQFakxgBYtFCBA:b-8tj9w4) ([raw file](https://github.com/vmware/pyvcloud/blob/b0d1bf75e4106a5960e187abe7a30f478b402c22/tox.ini#L2)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think we can use pep8 for this one. 
</blockquote></details>

`google` style seems to work better and enforces groups which pep8 doesn't. The default `cryptography` doesn't work well with some of our imports

---

*[pyvcloud/vcd/client.py, line 24 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L24UECfIsVr3k6nnNvw:-L25o7tBCGsitkm2ypIf:bl31lvb) ([raw file](https://github.com/vmware/pyvcloud/blob/b0d1bf75e4106a5960e187abe7a30f478b402c22/pyvcloud/vcd/client.py#L24)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

shouldn't request follow lxml?
</blockquote></details>

in `google` style yes, I changed it

---

*[pyvcloud/vcd/client.py, line 416 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L24VOZ6c4c9HtkCjReB:-L25M2u-hCBlu7sGBgzO:b-t31qc6) ([raw file](https://github.com/vmware/pyvcloud/blob/b0d1bf75e4106a5960e187abe7a30f478b402c22/pyvcloud/vcd/client.py#L416)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Can you please explain how is this function different from wait_for_status sans the default param values?
If they are the same, then we should collapse the implementation.
</blockquote></details>

The new method allows to fail on one or more task statuses. I guess we can collapse into the second implementation and check if `fail_on_statuses` is a single value or a collection. That should be backwards compatible.

---

*[pyvcloud/vcd/vm.py, line 124 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L24X1Kryyo1yJnBllPx:-L25oG9rBuKH9UPsEGWo:bb7f2mf) ([raw file](https://github.com/vmware/pyvcloud/blob/b0d1bf75e4106a5960e187abe7a30f478b402c22/pyvcloud/vcd/vm.py#L124)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit : operates on the VM?
</blockquote></details>

done

---

*[tests/vcd_vm.py, line 162 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L24W52Nrd_Tu8lsrXIT:-L25oqLhp0pSr-1JB0We:bb7f2mf) ([raw file](https://github.com/vmware/pyvcloud/blob/b0d1bf75e4106a5960e187abe7a30f478b402c22/tests/vcd_vm.py#L162)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I believe 'v' is the vdc_resource, we can assign it directly and save one rest call to vcd
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/165)*

**Comment by anusuyar** [comment]
Reviewed 9 of 14 files at r1, 1 of 1 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pyvcloud/vcd/vapp.py, line 493 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L22lQlnGI_17uOH_CDS:-L28B1QmKoW9GYNMpRPV:b-ug50m2) ([raw file](https://github.com/vmware/pyvcloud/blob/73289bf82fd1d6771bb8af0b7235b81e0512d57f/pyvcloud/vcd/vapp.py#L493)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

in general we don't validate parameters and the doc says `array` type, but I will add a check.
</blockquote></details>

I think if we start doing validation of param types, then we have to do it for all methods. I think it is better to name the variable like vm_name_list and not do any validation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/165)*

**Comment by rocknes** [comment]
:lgtm:

---

Reviewed 9 of 14 files at r1, 1 of 1 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pyvcloud/vcd/client.py, line 382 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L2Bxvo9dG1HHElep462:-L2Bxvo9dG1HHElep463:bouruux) ([raw file](https://github.com/vmware/pyvcloud/blob/8c82aae1e9de23d4ccaded7f7b1201be0e338f30/pyvcloud/vcd/client.py#L382)):*
> ```Python
>          :param timeout: (float): time (in seconds, floating point, fractional)
>             to wait for task to finish.
>          :param poll_requency: (float): time (in seconds, as above) with which
> ```

typo : poll_frequency

---

*[pyvcloud/vcd/client.py, line 386 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L2By4z21Cb1lc32zdkA:-L2By4z21Cb1lc32zdkB:b-b746wy) ([raw file](https://github.com/vmware/pyvcloud/blob/8c82aae1e9de23d4ccaded7f7b1201be0e338f30/pyvcloud/vcd/client.py#L386)):*
> ```Python
>          :param fail_on_statuses: (list): method will raise an exception if any
>             of the (TaskStatus) in this list is reached. If this parameter is
>             null then either task will achieve expected target status or throw
> ```

null or None?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-:-L2C-2cpEb_-9G1X2LEc:bnfp4nl)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tox.ini, line 2 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L24U-Mea8Addu3d0ngB:-L2C-smGPtyQIRjNOM1o:b-feg14g) ([raw file](https://github.com/vmware/pyvcloud/blob/b0d1bf75e4106a5960e187abe7a30f478b402c22/tox.ini#L2)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

`google` style seems to work better and enforces groups which pep8 doesn't. The default `cryptography` doesn't work well with some of our imports
</blockquote></details>

Just fyi though, google style enforcer for flake8 has a bug, (can't remember the exact error number, probably H306) which keeps on flip flopping between two ordering of imports.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/165)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tox.ini, line 2 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L24U-Mea8Addu3d0ngB:-L2OqfjrNvJZTWFxt9h-:bnlvvev) ([raw file](https://github.com/vmware/pyvcloud/blob/b0d1bf75e4106a5960e187abe7a30f478b402c22/tox.ini#L2)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Just fyi though, google style enforcer for flake8 has a bug, (can't remember the exact error number, probably H306) which keeps on flip flopping between two ordering of imports.
</blockquote></details>

I saw that problem but not with `google` style, which seems to be consistent

---

*[pyvcloud/vcd/client.py, line 382 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L2Bxvo9dG1HHElep462:-L2Or2v8Cph3CGYK3G1n:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/8c82aae1e9de23d4ccaded7f7b1201be0e338f30/pyvcloud/vcd/client.py#L382)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

typo : poll_frequency
</blockquote></details>

Done.

---

*[pyvcloud/vcd/client.py, line 386 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L2By4z21Cb1lc32zdkA:-L2Or8HNXhfyZg66qj6C:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/8c82aae1e9de23d4ccaded7f7b1201be0e338f30/pyvcloud/vcd/client.py#L386)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

null or None?
</blockquote></details>

Done.

---

*[pyvcloud/vcd/vapp.py, line 493 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/165#-L22lQlnGI_17uOH_CDS:-L2OrKwuBNNXDzSptJXG:b8g52mb) ([raw file](https://github.com/vmware/pyvcloud/blob/73289bf82fd1d6771bb8af0b7235b81e0512d57f/pyvcloud/vcd/vapp.py#L493)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I think if we start doing validation of param types, then we have to do it for all methods. I think it is better to name the variable like vm_name_list and not do any validation.
</blockquote></details>

I will remove validation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/165)*

**Pull request merged**
