### PR TITLE
VDP-1375, VCDA-504: Attach VC

### PR DESCRIPTION
**Pull request by ckolovson**
VDP-1375, VCDA-504: Attach VC
- Reviewers: @sompa @anusuyar

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/210)

### CODE REVIEW

**Comment by sompa** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 226 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64FuxP5Et13nlM9eqE:-L64FuxP5Et13nlM9eqF:b-uucj50) ([raw file](https://github.com/vmware/pyvcloud/blob/9b894d8f73bcf2a9514bce5a450df6a1c10b5292/pyvcloud/vcd/client.py#L226)):*
> ```Python
>         'application/vnd.vmware.vcloud.recomposeVAppParams+xml'
>     RECORDS = 'application/vnd.vmware.vcloud.query.records+xml'
>     REGISTER_VIM_SERVER_PARAMS = \
> ```

Can we rename this to VC_PARAMS or VC_SERVER_PARAMS ?

---

*[pyvcloud/vcd/platform.py, line 220 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64GCxkkniI6Up5k0s9:-L64GCxkkniI6Up5k0sA:bxltuip) ([raw file](https://github.com/vmware/pyvcloud/blob/9b894d8f73bcf2a9514bce5a450df6a1c10b5292/pyvcloud/vcd/platform.py#L220)):*
> ```Python
>     def attach_vcenter(self,
>                        vim_server_name,
>                        vim_server_host,
> ```

Can we rename these param names to have VC instead of vim ? IMO we should stick to the newer naming convention such as VC instead of VIM and NSX instead of VSM.

---

*[pyvcloud/vcd/platform.py, line 259 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64HCQSq3_DTruKtk-y:-L64HCQSq3_DTruKtk-z:b-g9dxun) ([raw file](https://github.com/vmware/pyvcloud/blob/9b894d8f73bcf2a9514bce5a450df6a1c10b5292/pyvcloud/vcd/platform.py#L259)):*
> ```Python
>             post_linked_resource(self.extension.get_resource(),
>                                  rel=RelationType.ADD,
>                                  media_type=EntityType.
> ```

Can you put this operation around a try catch block in case we get an exception during this POST operation ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/210)*

**Comment by anusuyar** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 226 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64FuxP5Et13nlM9eqE:-L64TkGoP8hImr_QxmLn:b-ys7pdt) ([raw file](https://github.com/vmware/pyvcloud/blob/9b894d8f73bcf2a9514bce5a450df6a1c10b5292/pyvcloud/vcd/client.py#L226)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Can we rename this to VC_PARAMS or VC_SERVER_PARAMS ?
</blockquote></details>

To me having REGISTER in the name feels more meaningful.

---

*[pyvcloud/vcd/platform.py, line 236 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64QcRcC1rQ3Ve_5IUZ:-L64QcRcC1rQ3Ve_5IU_:b-167vq7) ([raw file](https://github.com/vmware/pyvcloud/blob/9b894d8f73bcf2a9514bce5a450df6a1c10b5292/pyvcloud/vcd/platform.py#L236)):*
> nsx_admin_user (str):

nit: : (str) :

---

*[pyvcloud/vcd/platform.py, line 250 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64STQop-ScRcPMtcsf:-L64STQop-ScRcPMtcsg:b-do48mj) ([raw file](https://github.com/vmware/pyvcloud/blob/9b894d8f73bcf2a9514bce5a450df6a1c10b5292/pyvcloud/vcd/platform.py#L250)):*
> ```Python
>         register_vim_server_params.append(vim_server)
>         if nsx_server_name is not None:
>             shield_manager = E_VMEXT.ShieldManager(name=nsx_server_name)
> ```

Can we rename shield_manager to something related to nsx?

---

*[pyvcloud/vcd/platform.py, line 257 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64SFxu3-VCGU3fc2xE:-L64SFxu3-VCGU3fc2xF:b-l0murw) ([raw file](https://github.com/vmware/pyvcloud/blob/9b894d8f73bcf2a9514bce5a450df6a1c10b5292/pyvcloud/vcd/platform.py#L257)):*
> ```Python
> 
>         return self.client.\
>             post_linked_resource(self.extension.get_resource(),
> ```

if we are passing args as key, value pair, it better to do it for all arguments. Just not few of them.

---

*[pyvcloud/vcd/platform.py, line 259 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64HCQSq3_DTruKtk-y:-L64OlfoYAUn0_tofKgR:b8e0xzd) ([raw file](https://github.com/vmware/pyvcloud/blob/9b894d8f73bcf2a9514bce5a450df6a1c10b5292/pyvcloud/vcd/platform.py#L259)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Can you put this operation around a try catch block in case we get an exception during this POST operation ?
</blockquote></details>

I think its okay to not to have an try-catch block here. If vcd sends an error code, we throw the VCDExcetpions anyway(from the client.py) .  the users of this method should handle the exception. we should not mask it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/210)*

**Comment by ckolovson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 226 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64FuxP5Et13nlM9eqE:-L6rw62Kt6N9IQZedNe5:b-u7lia0) ([raw file](https://github.com/vmware/pyvcloud/blob/b7e1ec8b7e35b07281525763d4e2897f810b116d/pyvcloud/vcd/client.py#L226)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

To me having REGISTER in the name feels more meaningful.
</blockquote></details>

Changed to REGISTER_VC_SERVER_PARAMS

---

*[pyvcloud/vcd/platform.py, line 220 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64GCxkkniI6Up5k0s9:-L6rx7M0UIL9j6RzOvI_:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b7e1ec8b7e35b07281525763d4e2897f810b116d/pyvcloud/vcd/platform.py#L220)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Can we rename these param names to have VC instead of vim ? IMO we should stick to the newer naming convention such as VC instead of VIM and NSX instead of VSM.
</blockquote></details>

Done.

---

*[pyvcloud/vcd/platform.py, line 236 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64QcRcC1rQ3Ve_5IUZ:-L6rxYBXiAUAP1p-7MLN:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b7e1ec8b7e35b07281525763d4e2897f810b116d/pyvcloud/vcd/platform.py#L236)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

> nsx_admin_user (str):

nit: : (str) :
</blockquote></details>

Done.

---

*[pyvcloud/vcd/platform.py, line 250 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64STQop-ScRcPMtcsf:-L6rxnU_EvFaji1C9r0S:b-hs4w35) ([raw file](https://github.com/vmware/pyvcloud/blob/b7e1ec8b7e35b07281525763d4e2897f810b116d/pyvcloud/vcd/platform.py#L250)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Can we rename shield_manager to something related to nsx?
</blockquote></details>

Done. Renamed to nsx_manager

---

*[pyvcloud/vcd/platform.py, line 257 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64SFxu3-VCGU3fc2xE:-L6ryIxwc40HDqf0F-Yq:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b7e1ec8b7e35b07281525763d4e2897f810b116d/pyvcloud/vcd/platform.py#L257)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

if we are passing args as key, value pair, it better to do it for all arguments. Just not few of them.
</blockquote></details>

Done.

---

*[pyvcloud/vcd/platform.py, line 259 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/210#-L64HCQSq3_DTruKtk-y:-L6ryUUwTKzzYxY3eYkF:b-hi7i7e) ([raw file](https://github.com/vmware/pyvcloud/blob/b7e1ec8b7e35b07281525763d4e2897f810b116d/pyvcloud/vcd/platform.py#L259)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I think its okay to not to have an try-catch block here. If vcd sends an error code, we throw the VCDExcetpions anyway(from the client.py) .  the users of this method should handle the exception. we should not mask it here.
</blockquote></details>

Left as is. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/210)*

**Comment by sompa** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/210#-:-L6wqirY8ntwGmVE9EfK:bnfp4nl)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/210#-:-L6wr2ekDydVAtARunVR:bnfp4nl)*

**Pull request merged**
