### PR TITLE
VCDA-473: Implement vcd user list command

### PR DESCRIPTION
**Pull request by anusuyar**
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd user list -o AnuOrg
  deployedVMQuota    deployedVMQuotaRank  fullName    identityProviderType    isEnabled    isLdapUser    name        numberOfDeployedVMs    numberOfStoredVMs    storedVMQuota    storedVMQuotaRank
-----------------  ---------------------  ----------  ----------------------  -----------  ------------  --------  ---------------------  -------------------  ---------------  -------------------
                0                     -1              INTEGRATED              true         false         user1                         0                    0                0                   -1
                0                     -1              INTEGRATED              true         false         user2                         0                    0                0                   -1
                0                     -1              INTEGRATED              true         false         vappuser                      0                    2                0                   -1
                0                     -1              INTEGRATED              true         false         user                          0                    2                0                   -1

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/195)

### CODE REVIEW

**Comment by pacogomez** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 567 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/195#-L3n-kTQyhookLS_wAPZ:-L3n-kTQyhookLS_wAP_:bsr9fcx) ([raw file](https://github.com/vmware/pyvcloud/blob/aec254870ef377e6ef8ad5c0bac5a5b5de0caba1/pyvcloud/vcd/org.py#L567)):*
> ```Python
>         if len(user_record) < 1:
>             raise Exception('User \'%s\' does not exist.' % user_name)
>         return user_record[0]
> ```

if the record has only a summary information of the user, it would be better to return all the information available for the user, with a get of the href of the user

---

*[pyvcloud/vcd/org.py, line 590 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/195#-L3n00tUr0o8pk_OKxuN:-L3n00tUr0o8pk_OKxuO:bcs75gz) ([raw file](https://github.com/vmware/pyvcloud/blob/aec254870ef377e6ef8ad5c0bac5a5b5de0caba1/pyvcloud/vcd/org.py#L590)):*
> ```Python
> 
>         result = []
>         for r in list(query.execute()):
> ```

This is fine but this method just could return the result of the query execution:
`return query.execute()` and let the caller process the results. By converting to dict here, the caller loses the original xml representation, which could be useful for example in  a future command like `vcd-cli --output xml user list`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/195)*

**Comment by sahithi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 563 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/195#-L3ncqYEVDuIF9XyrEVr:-L3ncqYEVDuIF9XyrEVs:b-3ws38o) ([raw file](https://github.com/vmware/pyvcloud/blob/aec254870ef377e6ef8ad5c0bac5a5b5de0caba1/pyvcloud/vcd/org.py#L563)):*
> ```Python
>         :return:  (UserRecord): User record.
>         """
>         user_record = self.list_users(user_name)
> ```

Argument: isn't it supposed to be something like ('name',  user_name)?

---

*[pyvcloud/vcd/org.py, line 572 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/195#-L3ndRviHZp45wZoqC3Y:-L3ndRviHZp45wZoqC3Z:b3t84is) ([raw file](https://github.com/vmware/pyvcloud/blob/aec254870ef377e6ef8ad5c0bac5a5b5de0caba1/pyvcloud/vcd/org.py#L572)):*
> ```Python
>         """Retrieve the list of users in the current Org.
> 
>         :param name_filter: (str): Filter users by user name.
> ```

This has to be a tuple of ('name', user_name)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/195)*

**Comment by hodgesrm** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/pyvcloud/195#-L3nv_X4khLB-Amh7Uks:-L3nv_X4khLB-Amh7Ukt:b-hw1sei) (no related file):*
It is beyond the scope of this commit but I would like to see a User class similar to other pyvcloud entities.  (Logged as VDCA-482).  This would help make the programming model more consistent.  Needs further discussion, no need to resolve here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/195)*

**Comment by anusuyar** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/pyvcloud/195#-L3nv_X4khLB-Amh7Uks:-L3oRD1TfEws63xPkHXN:b-qpurho) (no related file):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

It is beyond the scope of this commit but I would like to see a User class similar to other pyvcloud entities.  (Logged as VDCA-482).  This would help make the programming model more consistent.  Needs further discussion, no need to resolve here. 
</blockquote></details>

@hodgesrm agree.

---

*[pyvcloud/vcd/org.py, line 563 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/195#-L3ncqYEVDuIF9XyrEVr:-L3oCpGgqm1CicwA6Md9:b-njxbp9) ([raw file](https://github.com/vmware/pyvcloud/blob/aec254870ef377e6ef8ad5c0bac5a5b5de0caba1/pyvcloud/vcd/org.py#L563)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Argument: isn't it supposed to be something like ('name',  user_name)?
</blockquote></details>

Yes. Changed it.

---

*[pyvcloud/vcd/org.py, line 567 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/195#-L3n-kTQyhookLS_wAPZ:-L3oR8eq9HQiHrksIQ_A:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/aec254870ef377e6ef8ad5c0bac5a5b5de0caba1/pyvcloud/vcd/org.py#L567)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

if the record has only a summary information of the user, it would be better to return all the information available for the user, with a get of the href of the user
</blockquote></details>

Done.

---

*[pyvcloud/vcd/org.py, line 572 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/195#-L3ndRviHZp45wZoqC3Y:-L3oD21TVuiZOYUuWdpp:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/aec254870ef377e6ef8ad5c0bac5a5b5de0caba1/pyvcloud/vcd/org.py#L572)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This has to be a tuple of ('name', user_name)
</blockquote></details>

Done.

---

*[pyvcloud/vcd/org.py, line 590 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/195#-L3n00tUr0o8pk_OKxuN:-L3oR9PuLmyUu5ZxDwQo:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/aec254870ef377e6ef8ad5c0bac5a5b5de0caba1/pyvcloud/vcd/org.py#L590)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

This is fine but this method just could return the result of the query execution:
`return query.execute()` and let the caller process the results. By converting to dict here, the caller loses the original xml representation, which could be useful for example in  a future command like `vcd-cli --output xml user list`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/195)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/195#-:-L3ostyQcLDC3aNqRzKj:bnfp4nl)*

**Comment by pacogomez** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/195#-:-L3oy8B9XrH6GUF2mDXa:bnfp4nl)*

**Pull request merged**
