### PR TITLE
Adding a new extension module to connect NSX-T Manager with VCD

### PR DESCRIPTION
**Pull request by mukultaneja**
Adding a new module NsxtExtension to add/update/delete NSX-T Manager

Signed-off-by: mukultaneja <mtaneja@vmware.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/764)

### CODE REVIEW

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm: once the outstanding comments are addressed.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/764#-:-M_ZOHhe9SXDMTwz2HCJ:bdxzzwu)* status: all files reviewed, 5 unresolved discussions (waiting on @mukultaneja)

___
*[pyvcloud/vcd/nsxt_extension.py, line 2 at r1](https://reviewable.io/reviews/vmware/pyvcloud/764#-M_ZMw8A6J1N0ZPEVdtd:-M_ZMw8B-qAw7g4k_ZDM:bb6ht36) ([raw file](https://github.com/vmware/pyvcloud/blob/b1ae6f571022532805defa6793d0805a79d0edc6/pyvcloud/vcd/nsxt_extension.py#L2)):*
> ```Python
> # VMware vCloud Director Python SDK
> # Copyright (c) 2014-2018 VMware, Inc. All Rights Reserved.
> ```

2021
___
*[pyvcloud/vcd/nsxt_extension.py, line 23 at r1](https://reviewable.io/reviews/vmware/pyvcloud/764#-M_ZN-Qh1_wBLyc6oPyI:-M_ZN-Qh1_wBLyc6oPyJ:b-8mwlp5) ([raw file](https://github.com/vmware/pyvcloud/blob/b1ae6f571022532805defa6793d0805a79d0edc6/pyvcloud/vcd/nsxt_extension.py#L23)):*
> ```Python
> 
> 
> class NsxtExtension(object):
> ```

No need to explicitly derive from object .. all classes in python are implicitly child class of object.

Also maybe a better name for the class would be `NSXTExtension`
___
*[pyvcloud/vcd/nsxt_extension.py, line 65 at r1](https://reviewable.io/reviews/vmware/pyvcloud/764#-M_ZNUwRClkr1s0WKw2m:-M_ZNUwRClkr1s0WKw2n:b-iv7ov4) ([raw file](https://github.com/vmware/pyvcloud/blob/b1ae6f571022532805defa6793d0805a79d0edc6/pyvcloud/vcd/nsxt_extension.py#L65)):*
> ```Python
> 
>         if not hasattr(nsxt_managers, 'NsxTManager'):
>             msg = "No Nsx-T Managers are registered yet."
> ```

nit: NSX-T
___
*[pyvcloud/vcd/nsxt_extension.py, line 72 at r1](https://reviewable.io/reviews/vmware/pyvcloud/764#-M_ZNInXAFlASRvyJCLD:-M_ZNInYESGUGMtlPi0Z:b-ccofr5) ([raw file](https://github.com/vmware/pyvcloud/blob/b1ae6f571022532805defa6793d0805a79d0edc6/pyvcloud/vcd/nsxt_extension.py#L72)):*
> ```Python
>                 return nsxt_manager
> 
>         msg = "No Nsx-T Managers found with given name {0}".format(name)
> ```

Please use f-strings
msg = f"No NSX-T Managers found with given name '{name}'."
___
*[pyvcloud/vcd/nsxt_extension.py, line 87 at r1](https://reviewable.io/reviews/vmware/pyvcloud/764#-M_ZNzfe5Lj5OFH86wB9:-M_ZNzff2Wgq4MqjGgEJ:b-iv7ov4) ([raw file](https://github.com/vmware/pyvcloud/blob/b1ae6f571022532805defa6793d0805a79d0edc6/pyvcloud/vcd/nsxt_extension.py#L87)):*
> ```Python
> 
>         if not hasattr(nsxt_managers, 'NsxTManager'):
>             msg = "No Nsx-T Managers are registered yet."
> ```

nit: NSX-T

**Review by mukultaneja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/764)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @rocknes)

___
*[pyvcloud/vcd/nsxt_extension.py, line 2 at r1](https://reviewable.io/reviews/vmware/pyvcloud/764#-M_ZMw8A6J1N0ZPEVdtd:-M_tzWj09R0q3dNyLNhX:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b1ae6f571022532805defa6793d0805a79d0edc6/pyvcloud/vcd/nsxt_extension.py#L2)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[pyvcloud/vcd/nsxt_extension.py, line 23 at r1](https://reviewable.io/reviews/vmware/pyvcloud/764#-M_ZN-Qh1_wBLyc6oPyI:-M_tzajP4GlSZiJDf65s:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b1ae6f571022532805defa6793d0805a79d0edc6/pyvcloud/vcd/nsxt_extension.py#L23)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

No need to explicitly derive from object .. all classes in python are implicitly child class of object.

Also maybe a better name for the class would be `NSXTExtension`
</blockquote></details>

Done.
___
*[pyvcloud/vcd/nsxt_extension.py, line 72 at r1](https://reviewable.io/reviews/vmware/pyvcloud/764#-M_ZNInXAFlASRvyJCLD:-M_tzcMu4cQHeC4BNqbF:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b1ae6f571022532805defa6793d0805a79d0edc6/pyvcloud/vcd/nsxt_extension.py#L72)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please use f-strings
msg = f"No NSX-T Managers found with given name '{name}'."
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/764)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

**Comment by Harish0596** [comment]
Hi

Is there any recommended python library to manage operations on NSX-T manager, just like how we use pyvcloud to manage VCD

**Pull request merged**
