### PR TITLE
Adding ability to create directly connected OrgVdc networks

### PR DESCRIPTION
**Pull request by rocknes**
(pyvcloud) C:\code\pyvcloud\tests>python -m unittest vcd_org.TestOrg.test_03_disable_org
.
----------------------------------------------------------------------
Ran 1 test in 1.870s

OK

(pyvcloud) C:\code\pyvcloud\tests>python -m unittest vcd_org.TestOrg.test_02_enable_org
.
----------------------------------------------------------------------
Ran 1 test in 1.851s

OK

(pyvcloud) C:\code\pyvcloud\tests>python -m unittest vcd_network.TestNetwork.test_001_create_orgvdc_network
.
----------------------------------------------------------------------
Ran 1 test in 4.550s

OK

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/162)

### CODE REVIEW

**Comment by anusuyar** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/vdc.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-L1trHHDrR_0xWgLpXOh:-L1trHHDrR_0xWgLpXOi:b52n16g) ([raw file](https://github.com/vmware/pyvcloud/blob/ec88eba26d09e32e3e029b2cb902a1e0625e0871/pyvcloud/vcd/vdc.py#L666)):*
> ```Python
>         """Create a new directly connected OrgVdc network in this VDC.
> 
>         :param network_name: (str) Name of the new network
> ```

The format is :param network_name: (str): 

---

*[tests/vcd_network.py, line 33 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-L1xwEECcsyPH8AYMG76:-L1xwEECcsyPH8AYMG77:b-5ex98i) ([raw file](https://github.com/vmware/pyvcloud/blob/ec88eba26d09e32e3e029b2cb902a1e0625e0871/tests/vcd_network.py#L33)):*
> ```Python
>             network_name=self.config['vcd']['vdc_direct_network_name'],
>             description='Dummy description',
>             parent_network_name=self.config['vcd']['ext_network_name'])
> ```

Can we have an assert to check if the network is created as expected?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/162)*

**Comment by rocknes** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/vdc.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-L1trHHDrR_0xWgLpXOh:-L1yp7VGEg9EPBNXXgFW:b-7ql1td) ([raw file](https://github.com/vmware/pyvcloud/blob/ec88eba26d09e32e3e029b2cb902a1e0625e0871/pyvcloud/vcd/vdc.py#L666)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

The format is :param network_name: (str): 
</blockquote></details>

fixed

---

*[tests/vcd_network.py, line 33 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-L1xwEECcsyPH8AYMG76:-L1yodyt7nFfOvfW7Uy0:bqmjwcz) ([raw file](https://github.com/vmware/pyvcloud/blob/ec88eba26d09e32e3e029b2cb902a1e0625e0871/tests/vcd_network.py#L33)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Can we have an assert to check if the network is created as expected?
</blockquote></details>

Added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/162)*

**Comment by rocknes** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/vdc.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-L1trHHDrR_0xWgLpXOh:-L1zWCgVHy30HeVXHNgt:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/ec88eba26d09e32e3e029b2cb902a1e0625e0871/pyvcloud/vcd/vdc.py#L666)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

fixed
</blockquote></details>

Done.

---

*[tests/vcd_network.py, line 33 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-L1xwEECcsyPH8AYMG76:-L1zWEUJbeWprjiD6AO-:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/ec88eba26d09e32e3e029b2cb902a1e0625e0871/tests/vcd_network.py#L33)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Added.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/162)*

**Comment by pacogomez** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/vdc.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-L1trHHDrR_0xWgLpXOh:-L1zhhTOX2UhF9MrmkE1:bur7fsn) ([raw file](https://github.com/vmware/pyvcloud/blob/ec88eba26d09e32e3e029b2cb902a1e0625e0871/pyvcloud/vcd/vdc.py#L666)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Done.
</blockquote></details>

an `is_shared=None` param should be added. If is not None then it should be set in the payload. see http://pubs.vmware.com/vcd-820/index.jsp?topic=%2Fcom.vmware.vcloud.api.reference.doc_27_0%2Fdoc%2Ftypes%2FOrgVdcNetworkType.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/162)*

**Comment by rocknes** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/vdc.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-L1trHHDrR_0xWgLpXOh:-L22RmlvQBAM1qfUpyGx:b8l53it) ([raw file](https://github.com/vmware/pyvcloud/blob/ec88eba26d09e32e3e029b2cb902a1e0625e0871/pyvcloud/vcd/vdc.py#L666)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

an `is_shared=None` param should be added. If is not None then it should be set in the payload. see http://pubs.vmware.com/vcd-820/index.jsp?topic=%2Fcom.vmware.vcloud.api.reference.doc_27_0%2Fdoc%2Ftypes%2FOrgVdcNetworkType.html
</blockquote></details>

Added the param.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/162)*

**Comment by pacogomez** [comment]
see my comment below

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/vdc.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-L1trHHDrR_0xWgLpXOh:-L22ce0MFMm5zpPfdjjN:b-y5bcf4) ([raw file](https://github.com/vmware/pyvcloud/blob/ec88eba26d09e32e3e029b2cb902a1e0625e0871/pyvcloud/vcd/vdc.py#L666)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Added the param.
</blockquote></details>

since `IsShared` is optional, the default param value should be `is_shared=None`. Only if is not none, it will be appended to the payload (whatever the value is, `True` or `False`). We should follow this pattern on every payload to send to vCD

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-:-L22dDZmD-ixWbm1lP9W:b-lxaqvm)*

**Comment by rocknes** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/vdc.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-L1trHHDrR_0xWgLpXOh:-L22g-ahRivnlIBR30k7:b-syd8u0) ([raw file](https://github.com/vmware/pyvcloud/blob/ec88eba26d09e32e3e029b2cb902a1e0625e0871/pyvcloud/vcd/vdc.py#L666)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

since `IsShared` is optional, the default param value should be `is_shared=None`. Only if is not none, it will be appended to the payload (whatever the value is, `True` or `False`). We should follow this pattern on every payload to send to vCD
</blockquote></details>

Agreed, made the chagnes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/162)*

**Comment by pacogomez** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-:-L22hFo2l7VR7EC8kQ_-:bnfp4nl)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/162#-:-L22jQY7_1mlsokDlx5G:bnfp4nl)*

**Pull request merged**
