### PR TITLE
VCDA-441  list available storage profiles

### PR DESCRIPTION
**Pull request by rdbwebster**
- Implemented list storage profiles by implementing vcd-cli command 'pvdc info name'
- New pvdc.py module to manage pvdc resources.
- New utils method for format pvdc to dictionary.

Tested by vcd-cli tenant-onboard.sh

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/188)

### CODE REVIEW

**Comment by rocknes** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pyvcloud/vcd/pvdc.py, line 2 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/188#-L3bpoMjitM-xFSAA5EH:-L3bpoMjitM-xFSAA5EI:bb6ht2i) ([raw file](https://github.com/vmware/pyvcloud/blob/9f876291b4d54ded4ecb1724c2602c8b0f116059/pyvcloud/vcd/pvdc.py#L2)):*
> ```Python
> # VMware vCloud Director Python SDK
> # Copyright (c) 2014 VMware, Inc. All Rights Reserved.
> ```

2018

---

*[pyvcloud/vcd/pvdc.py, line 27 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/188#-L3bqA-kjxB9g_U0Ud8j:-L3bqA-kjxB9g_U0Ud8k:b-5xhd4m) ([raw file](https://github.com/vmware/pyvcloud/blob/9f876291b4d54ded4ecb1724c2602c8b0f116059/pyvcloud/vcd/pvdc.py#L27)):*
> ```Python
>         Constructor for PVDC object
>         :param client:  (pyvcloud.vcd.client): The client.
>         :param href: URI representing _WellKnownEndpoint.ADMIN.
> ```

This description doesn't look right, the href should be of the pvdc resource
something like api/admin/pvdc/{id}

---

*[pyvcloud/vcd/pvdc.py, line 29 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/188#-L3bqTMkCa9thL1fQTiX:-L3bqTMkCa9thL1fQTiY:bwce7vh) ([raw file](https://github.com/vmware/pyvcloud/blob/9f876291b4d54ded4ecb1724c2602c8b0f116059/pyvcloud/vcd/pvdc.py#L29)):*
> ```Python
>         :param href: URI representing _WellKnownEndpoint.ADMIN.
>         :param resource: (lxml.objectify.ObjectifiedElement): XML
>         representation of href.
> ```

nit : representation of the resource at href

---

*[pyvcloud/vcd/pvdc.py, line 30 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/188#-L3bptE_cZc6wt-jFFu_:-L3bptE_cZc6wt-jFFua:bra3ged) ([raw file](https://github.com/vmware/pyvcloud/blob/9f876291b4d54ded4ecb1724c2602c8b0f116059/pyvcloud/vcd/pvdc.py#L30)):*
> ```Python
>         :param resource: (lxml.objectify.ObjectifiedElement): XML
>         representation of href.
>         """  # NOQA
> ```

We should avoid using #NOQA and try to format the description strings as per PEP8 standard

---

*[pyvcloud/vcd/pvdc.py, line 32 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/188#-L3bqedBRbf-DsWj8Lqj:-L3bqedC_CPzXPPegba9:b-rs07j9) ([raw file](https://github.com/vmware/pyvcloud/blob/9f876291b4d54ded4ecb1724c2602c8b0f116059/pyvcloud/vcd/pvdc.py#L32)):*
> ```Python
>         """  # NOQA
>         self.client = client
>         self.name = name
> ```

Are we using this anywhere if not, we should drop it from the param list.

---

*[pyvcloud/vcd/pvdc.py, line 74 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/188#-L3br-wv_kKtzUvKW_1Z:-L3br-wv_kKtzUvKW_1_:bb7p891) ([raw file](https://github.com/vmware/pyvcloud/blob/9f876291b4d54ded4ecb1724c2602c8b0f116059/pyvcloud/vcd/pvdc.py#L74)):*
> ```Python
>                      key,
>                      value,
>                      metadata_type='MetadataStringValue'):
> ```

Can there be other types of metadata? I see that we have hardcoded 'MetadataStringValue' in E.Type element below, should it be metadata_type instead?

---

*[pyvcloud/vcd/system.py, line 152 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/188#-L3_nGsl941n_zMAKtzH:-L3_nGsl941n_zMAKtzI:blptqhd) ([raw file](https://github.com/vmware/pyvcloud/blob/9f876291b4d54ded4ecb1724c2602c8b0f116059/pyvcloud/vcd/system.py#L152)):*
> ```Python
>                         'access to resource is forbidden' % name)
> 
>     def extract_id(urn):
> ```

This method is already defined in utils.py. We shouldn't redefine it here.

---

*[pyvcloud/vcd/utils.py, line 126 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/188#-L3_ovBGHQELt8LHZkAz:-L3_ovBGHQELt8LHZkB-:bgzfe3m) ([raw file](https://github.com/vmware/pyvcloud/blob/9f876291b4d54ded4ecb1724c2602c8b0f116059/pyvcloud/vcd/utils.py#L126)):*
> ```Python
> 
> 
> def pvdc_to_dict(pvdc, refs=None, metadata=None):
> ```

We should probably add documentation to explain what the variable 'refs' expects/is used for.

---

*[pyvcloud/vcd/utils.py, line 130 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/188#-L3_oGK41Hk1V1E57e_S:-L3_oGK41Hk1V1E57e_T:b-vlu3dg) ([raw file](https://github.com/vmware/pyvcloud/blob/9f876291b4d54ded4ecb1724c2602c8b0f116059/pyvcloud/vcd/utils.py#L130)):*
> ```Python
>     result['name'] = pvdc.get('name')
>     result['id'] = extract_id(pvdc.get('id'))
>     result['description'] = str('%s' % pvdc.Description)
> ```

str(pvdc.Description) should work too

---

*[pyvcloud/vcd/vdc.py, line 57 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/188#-L3_nRnJKsvNzZIHbDvt:-L3_nRnJKsvNzZIHbDvu:bpy263z) ([raw file](https://github.com/vmware/pyvcloud/blob/9f876291b4d54ded4ecb1724c2602c8b0f116059/pyvcloud/vcd/vdc.py#L57)):*
> ```Python
>                         result.append(vapp.get('href'))
>         if len(result) == 0:
>             raise Exception('vApp named \'%s\' not found' % name)
> ```

I guess you are working on both JIRA tasks from the same branch. This change is part of the other Pull request. Having separate git branches for JIRA tasks might be a good idea to explore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/188)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/utils.py, line 130 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/188#-L3jSVyhRo5TCFUJtpG-:-L3jSVyiJLrGhadls3yO:bviee7g) ([raw file](https://github.com/vmware/pyvcloud/blob/b484b4f65b5c4b63600bcec7bf0716dae5371166/pyvcloud/vcd/utils.py#L130)):*
> ```Python
> 
>     :param pvdc: (ProviderVdcType): xml object
>     :param pvdc: (VdcReferences): xml object retrieved from
> ```

should this be refs  instead of pvdc ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/188)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/utils.py, line 132 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/188#-L3jSaDepkC0fhhZkl1-:-L3jSaDepkC0fhhZkl10:b-9sp8yn) ([raw file](https://github.com/vmware/pyvcloud/blob/b484b4f65b5c4b63600bcec7bf0716dae5371166/pyvcloud/vcd/utils.py#L132)):*
> ```Python
>     :param pvdc: (VdcReferences): xml object retrieved from
>            the ProviderVdcType.
>     :param pvdc: (Metadata): xml object metadata retrieved from
> ```

should this be metadata instead of pvdc ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/188)*

**Comment by sompa** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/188)*

**Pull request merged**
