### PR TITLE
VCDA-409: validate PEP8 compliance

### PR DESCRIPTION
**Pull request by pacogomez**
- use yapf to auto format code
- validate with flake8
- new ./format-code.sh script

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/183)

### CODE REVIEW

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/183#-:-L3GUdzf6cTrW4IrsVoR:bnfp4nl)*

**Comment by sahithi** [comment]
:lgtm: Thanks Paco for fixing the format issues.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/183#-:-L3Un7gmDeNNCsrzxdYr:bo241mj)*

**Comment by sompa** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/183#-:-L3Whj1c5n6IKCGvMrQG:bnfp4nl)*

**Comment by sompa** [comment]
Reviewed 15 of 15 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/183)*

**Pull request merged**
