### PR TITLE
VCDA-394: Introduce capability to list external networks

### PR DESCRIPTION
**Pull request by rocknes**
* Added two new functions in platform.py to list external networks and find one by it's name
* Refactored code to create directly connected org vdc network to leverage the functions mentioned above
* Removed slashes at the end of multi line function doc strings
* Converted VDC to lowercase in function doc strings
* Added unit test to test listing of all external networks

Unit test result
---------------
(pyvcloud) C:\code\pyvcloud\tests>python -m unittest vcd_network.TestNetwork.test_030_list_external_networks
.
----------------------------------------------------------------------
Ran 1 test in 1.334s

OK

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/179)

### CODE REVIEW

**Comment by sahithi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/platform.py, line 78 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/179#-L3EfL_MUN2MmcYbHmBo:-L3EfL_MUN2MmcYbHmBp:b-hmlpkq) ([raw file](https://github.com/vmware/pyvcloud/blob/fb5bfb65a88f8b0854ecb7948a02f6affbee02c1/pyvcloud/vcd/platform.py#L78)):*
> ```Python
> 
>     def get_external_network(self, name):
>         """Fetch the XML representation of an external network resource.
> ```

Any specific reason why you emphasized it by  'XML representation'? Wouldn't 'Retrieve external network resource' suffice?

---

*[pyvcloud/vcd/platform.py, line 89 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/179#-L3Ef6jlqcRQpKOVnIHk:-L3Ef6jmjTd6I8G0y3cH:b56two2) ([raw file](https://github.com/vmware/pyvcloud/blob/fb5bfb65a88f8b0854ecb7948a02f6affbee02c1/pyvcloud/vcd/platform.py#L89)):*
> ```Python
>             if ext_net.get('name') == name:
>                 return self.client.get_resource(ext_net.get('href'))
>         raise Exception('External network \'%s\' not found.')
> ```

name of the network missing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/179)*

**Comment by sahithi** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/179)*

**Comment by rocknes** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/platform.py, line 78 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/179#-L3EfL_MUN2MmcYbHmBo:-L3F754fz4LK9Xi4IFx2:bt2vr0x) ([raw file](https://github.com/vmware/pyvcloud/blob/fb5bfb65a88f8b0854ecb7948a02f6affbee02c1/pyvcloud/vcd/platform.py#L78)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Any specific reason why you emphasized it by  'XML representation'? Wouldn't 'Retrieve external network resource' suffice?
</blockquote></details>

Fixed 

---

*[pyvcloud/vcd/platform.py, line 89 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/179#-L3Ef6jlqcRQpKOVnIHk:-L3F76hmjks_uOhcyoIB:b-c4rif5) ([raw file](https://github.com/vmware/pyvcloud/blob/fb5bfb65a88f8b0854ecb7948a02f6affbee02c1/pyvcloud/vcd/platform.py#L89)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

name of the network missing.
</blockquote></details>

Added the missing param

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/179)*

**Comment by pacogomez** [comment]
minor cosmetic changes, otherwise :lgtm: 

---

Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 194 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/179#-L3FA65gQkOVjd4TRJ5N:-L3FA65gQkOVjd4TRJ5O:br0kc5i) ([raw file](https://github.com/vmware/pyvcloud/blob/044e1ce1a30e168d14b3a4b35092a98cf92fd7f7/pyvcloud/vcd/client.py#L194)):*
> ```Python
>     EXTERNAL_NETWORK_REFS = \
>         'application/vnd.vmware.admin.vmwExternalNetworkReferences+xml'
>     EXTENSION_SERVICES = 'application/vnd.vmware.admin.extensionServices+xml'
> ```

declare items in alphabetical order

---

*[pyvcloud/vcd/platform.py, line 65 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/179#-L3FALl-W5i0GPCFPGRX:-L3FALl-W5i0GPCFPGRY:b7vak6i) ([raw file](https://github.com/vmware/pyvcloud/blob/044e1ce1a30e168d14b3a4b35092a98cf92fd7f7/pyvcloud/vcd/platform.py#L65)):*
> ```Python
> 
>         :return:  A list of :class:`lxml.objectify.StringElement` objects
>         representing the external network references.
> ```

nit: add 4 spaces to the continuing line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/179#-:-L3FB3og2E0xU3KjY-ig:b-3l0i8e)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/179#-:-L3FBIhKzuHmvLBjUJuP:bnfp4nl)*

**Comment by rocknes** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 194 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/179#-L3FA65gQkOVjd4TRJ5N:-L3FCJh9IlISpazi6PKo:bb6un1j) ([raw file](https://github.com/vmware/pyvcloud/blob/044e1ce1a30e168d14b3a4b35092a98cf92fd7f7/pyvcloud/vcd/client.py#L194)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

declare items in alphabetical order
</blockquote></details>

Done

---

*[pyvcloud/vcd/platform.py, line 65 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/179#-L3FALl-W5i0GPCFPGRX:-L3FCL3kdvFhCohAlcXM:b-8b11j9) ([raw file](https://github.com/vmware/pyvcloud/blob/044e1ce1a30e168d14b3a4b35092a98cf92fd7f7/pyvcloud/vcd/platform.py#L65)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

nit: add 4 spaces to the continuing line
</blockquote></details>

Added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/179)*

**Comment by pacogomez** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/179#-:-L3FD1bRzYER0QSxbcJb:bnfp4nl)*

**Pull request merged**
