### PR TITLE
get an edge gateway and the nat rules of an edge gateway

### PR DESCRIPTION
**Pull request by floriankammermann**
tested by tests/vcd_edge_gateway.py

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/225)

### CODE REVIEW

**Comment by rocknes** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tests/vcd_edge_gateway.py, line 47 at r1](https://beta.reviewable.io/reviews/vmware/pyvcloud/225#-L99WG1f1osUugbSEQ0u:-L99WG1f1osUugbSEQ0v:b-wg39aa) ([raw file](https://github.com/vmware/pyvcloud/blob/06c3b930f69a83d6703d08de5c564c428a871e91/tests/vcd_edge_gateway.py#L47)):*
> ```Python
>         vdc = VDC(self.client, resource=v)
>         with self.assertRaisesRegex(Exception, 'Edge Gateway not found \'' +
>                                     self.config['vcd']['edge_gateway'] +
> ```

Please roll --self.config['vcd']['edge_gateway'] + '_not_existent\''-- into a single config key-value pair

---

*[tests/vcd_edge_gateway.py, line 50 at r1](https://beta.reviewable.io/reviews/vmware/pyvcloud/225#-L99WLhf4Nhit-BgTcsB:-L99WLhf4Nhit-BgTcsC:b-fohc7u) ([raw file](https://github.com/vmware/pyvcloud/blob/06c3b930f69a83d6703d08de5c564c428a871e91/tests/vcd_edge_gateway.py#L50)):*
> ```
>                                     '_not_existent\'') as exception:
>             assert exception
> ```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/225#-:-L99WeYKE1WocWh64Qcr:bnfp4nl)*

**Comment by floriankammermann** [comment]
@rocknes do you not agree with my statement? If you don't agree I will move the _no_existent edge gateway to a config key-value pair, to get the pull request approved.

**Comment by rocknes** [comment]
My suggestion of converting the name ['vcd']['edge_gateway'] + '_not_existent' to a configuration was to make sure that you don't have to create the string multiple times. It's a good practice to have your constants defined in one single place.

Btw I have already approved the pull request :) I marked my comment as just a discussion.

Add @rhodges, @anusuyar or @sompa to get a second ship it (:lgtm), before we can merge your code.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/225#-:-LAPVJeH5pIyUIMJedOS:bps053z)*

**Comment by pandeys** [comment]
These functionalities are written in the mean time in pyvcloud.

**Pull request closed without merging**
