### PR TITLE
VCDA-354: CSE support multiple vCenters

### PR DESCRIPTION
**Pull request by pacogomez**
- renamed Extension to APIExtension, new location in api_extension.py
- new class Extension to work with admin extension, file extension.py
- more meaningfull error message when wkep is not available
- introduced logging into TestCase class
- return vCenter of a VM
- added more fields to config.yml
- added new Platform class to work with vSphere resources
- unit tests

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/173)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/api_extension.py, line 46 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30NZU6pQVnocaRjwm2:-L30NZU6pQVnocaRjwm3:b-j16s2l) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/pyvcloud/vcd/api_extension.py#L46)):*
> ```Python
>         return to_dict(ext, self.ATTRIBUTES)
> 
>     def get_api_filters(self, service_id):
> ```

What determines when to define parameters with a comment vs. when not to?  This should be consistent either way. 

---

*[tests/config.yml, line 5 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30ONOwIGPyhu1O6p3S:-L30ONOwIGPyhu1O6p3T:bw7hobu) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/tests/config.yml#L5)):*
> ```YAML
>   org: System
>   user: administrator
>   password: 'ca$hc0w'
> ```

We should not have passwords for systems in Github. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/173)*

**Comment by sahithi** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[pyvcloud/vcd/api_extension.py, line 2 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30bY23-PNfUt8NbfvK:-L30bY24Dwb_dwTk_0b9:b-65l1p2) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/pyvcloud/vcd/api_extension.py#L2)):*
> ```Python
> # VMware vCloud Director Python SDK
> # Copyright (c) 2014 VMware, Inc. All Rights Reserved.
> ```

2018 VMware

---

*[pyvcloud/vcd/api_extension.py, line 72 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30croZbK1D9gdfIqek:-L30croZbK1D9gdfIqel:b-hhnc5) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/pyvcloud/vcd/api_extension.py#L72)):*
> ```Python
>         return ext
> 
>     def add_extension(self, name, namespace, routing_key, exchange, patterns):
> ```

Missing doc-string for several methods, please add

---

*[pyvcloud/vcd/client.py, line 916 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30dLk1Vkf_8U8TkHV5:-L30dLk2iiBPqMwITaP1:b-u901wa) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/pyvcloud/vcd/client.py#L916)):*
> ```Python
>             return self._session_endpoints[wk_type]
>         else:
>             raise Exception(
> ```

Note for our future discussions: We should categorize and follow proper Exception hierarchy for all exceptions emerging from vcd-cli and Pyvcloud going forward.

---

*[pyvcloud/vcd/platform.py, line 34 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30dx8aDUpYGyo3_GXY:-L30dx8b5nHkTlBDwQM3:b-pu8fcn) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/pyvcloud/vcd/platform.py#L34)):*
> ```Python
>         """List vCenter servers attached to the system.
> 
>         :return: a list of vCenter items
> ```

You mean list of vCenter resources? Also, add type

---

*[pyvcloud/vcd/platform.py, line 41 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30eCzllIDuobimCW0q:-L30eCzllIDuobimCW0r:b-syr808) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/pyvcloud/vcd/platform.py#L41)):*
> ```Python
>             EntityType.VIM_SERVER_REFS.value).VimServerReference
> 
>     def get_vcenter(self, name):
> ```

missing doc string

---

*[tests/vcd_vapp_vm_system.py, line 1 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30eRwMEmNVHpPuWySB:-L30eRwMEmNVHpPuWySC:b1jrc5z) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/tests/vcd_vapp_vm_system.py#L1)):*
> ```Python
> import os
> ```

Copy right header

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/173)*

**Comment by pacogomez** [comment]
Review status: 6 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[pyvcloud/vcd/api_extension.py, line 2 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30bY23-PNfUt8NbfvK:-L30gISHP-AV_ndo6QVn:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/pyvcloud/vcd/api_extension.py#L2)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

2018 VMware
</blockquote></details>

Done.

---

*[pyvcloud/vcd/api_extension.py, line 46 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30NZU6pQVnocaRjwm2:-L30ag4AdRBdjCMg6QZe:b-3r71hm) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/pyvcloud/vcd/api_extension.py#L46)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

What determines when to define parameters with a comment vs. when not to?  This should be consistent either way. 
</blockquote></details>

we are adding docstrings to new code and will document previously written code in a best effort basis.

---

*[pyvcloud/vcd/api_extension.py, line 72 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30croZbK1D9gdfIqek:-L30gKr0OfYygpfBLrlj:b3y7gio) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/pyvcloud/vcd/api_extension.py#L72)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Missing doc-string for several methods, please add
</blockquote></details>

This is code added before, will do in a best effort basis

---

*[pyvcloud/vcd/platform.py, line 34 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30dx8aDUpYGyo3_GXY:-L30j9U7TZE0ShtZZTOB:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/pyvcloud/vcd/platform.py#L34)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

You mean list of vCenter resources? Also, add type
</blockquote></details>

Done.

---

*[pyvcloud/vcd/platform.py, line 41 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30eCzllIDuobimCW0q:-L30j9mjcEOoJqIGQ8d7:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/pyvcloud/vcd/platform.py#L41)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

missing doc string
</blockquote></details>

Done.

---

*[tests/config.yml, line 5 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30ONOwIGPyhu1O6p3S:-L30aZvHxa4Q8mQEMxmA:b-lbnz7d) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/tests/config.yml#L5)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

We should not have passwords for systems in Github. 
</blockquote></details>

cleared

---

*[tests/vcd_vapp_vm_system.py, line 1 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30eRwMEmNVHpPuWySB:-L30i2j9wuet4JdMmP43:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/tests/vcd_vapp_vm_system.py#L1)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Copy right header
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/173)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: 6 of 10 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-:-L34LXO_ny4mq4OGr6sp:bnfp4nl)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-:-L34Meb96HFK1Q4wGpfy:bnfp4nl)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/platform.py, line 20 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L34Psz-9ai9Cf8UUam2:-L34Psz0yneK4PwO-pnI:bn1g448) ([raw file](https://github.com/vmware/pyvcloud/blob/ec75018df733903a37001bef19aa77c15a190909/pyvcloud/vcd/platform.py#L20)):*
> ```Python
> from pyvcloud.vcd.client import RelationType
> from pyvcloud.vcd.extension import Extension
> ```

Would it be a good idea to add doc at the class level, to precisely describe what the class is intended to do ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/173)*

**Comment by sompa** [comment]
Reviewed 6 of 10 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/173)*

**Comment by sompa** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-:-L34Qi0zOSoezpCgkcuS:bnfp4nl)*

**Comment by pacogomez** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pyvcloud/vcd/api_extension.py, line 72 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L30croZbK1D9gdfIqek:-L34Rkub7ZGD92GLpFn3:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/12f05b63c8acef9989e627ffab98cfbce22ce05b/pyvcloud/vcd/api_extension.py#L72)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

This is code added before, will do in a best effort basis
</blockquote></details>

Done.

---

*[pyvcloud/vcd/platform.py, line 20 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/173#-L34Psz-9ai9Cf8UUam2:-L34TPFeu6C9qqVAsm65:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/ec75018df733903a37001bef19aa77c15a190909/pyvcloud/vcd/platform.py#L20)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Would it be a good idea to add doc at the class level, to precisely describe what the class is intended to do ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/173)*

**Pull request merged**
