### PR TITLE
VCDA-258: Provide an optional parameter to specify IOPS during creation

### PR DESCRIPTION
**Pull request by sompa**
Unit tests run : TestDiskSetup

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/158)

### CODE REVIEW

**Comment by rocknes** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/vdc.py, line 357 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/158#-L1KDOIKLmfIZUmVbZR-:-L1KDOIL-xxTzhrQJLLD:bbzvwuf) ([raw file](https://github.com/vmware/pyvcloud/blob/a09431c4a9f1ae46b0cfbf1cace4979c82c09365/pyvcloud/vcd/vdc.py#L357)):*
> ```Python
>         :param bus_type: (str): The bus type of the new disk.
>         :param bus_subtype: (str): The bus subtype  of the new disk.
>         :param iops: (str): The iops of the new disk.
> ```

Since iops is a numerical value, we should use int.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/158)*

**Comment by anusuyar** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/vcd_disk_setup.py, line 23 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/158#-L1KjFLtHgYI2KhLfh-g:-L1KjFLtHgYI2KhLfh-h:b-whpysc) ([raw file](https://github.com/vmware/pyvcloud/blob/a09431c4a9f1ae46b0cfbf1cace4979c82c09365/tests/vcd_disk_setup.py#L23)):*
> ```Python
>         vdc = VDC(self.client, href=v.get('href'))
> 
>         taskObj = vdc.add_disk(self.config['vcd']['disk'], 10*1024*1024, '200', None, None, '10 MB Disk')
> ```

Can we added assert here to check in 'add_disk' operation is successful? I think the TC will pass even if add_disk fails in the server.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/158)*

**Comment by sompa** [comment]
*[tests/vcd_disk_setup.py, line 23 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/158#-L1KjFLtHgYI2KhLfh-g:-L1yL601EiWDF0UFmAIy:bs7wumb) ([raw file](https://github.com/vmware/pyvcloud/blob/a09431c4a9f1ae46b0cfbf1cace4979c82c09365/tests/vcd_disk_setup.py#L23)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Can we added assert here to check in 'add_disk' operation is successful? I think the TC will pass even if add_disk fails in the server.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/158)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vdc.py, line 357 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/158#-L1KDOIKLmfIZUmVbZR-:-L1yL7iy2KVuKtfFmdHg:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/a09431c4a9f1ae46b0cfbf1cace4979c82c09365/pyvcloud/vcd/vdc.py#L357)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Since iops is a numerical value, we should use int.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/158)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/158#-:-L1yZN37giMJRvESflPk:bnfp4nl)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[tests/vcd_disk_setup.py, line 19 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/158#-L1ymFXNN1BKvtrsmZL-:-L1ymFXNN1BKvtrsmZL0:b3rei1) ([raw file](https://github.com/vmware/pyvcloud/blob/0f2cbd7514c7f83e1ff6547e4deaa749f739f798/tests/vcd_disk_setup.py#L19)):*
> ```Python
> 
>         taskObj = vdc.add_disk(self.config['vcd']['disk'],
>                                10*1024*1024, 200,
> ```

Please specify the name of the param that you are supplying the value for. Since python doesn't have strict type checking positional arguments are a recipe for disaster.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/158)*

**Pull request merged**
