### PR TITLE
Add attach_network_to_vm method

### PR DESCRIPTION
**Pull request by rvdh**
This method makes it possible to attach a network to virtual machines
inside a vapp. A unit test has also been added and a hardcoded parameter, also used for other tests, has been made configurable.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/242)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Thanks for the PR @rvdh!  This looks like a good feature.  

We need to have an internal discussion about the test you submitted. We're moving to a new mechanism which you can see in the system_tests directory and it may make sense to put it there instead of adding to the unit tests, which are harder to run.  I'll get back to you with detailed feedback as soon as we can do that.

**Comment by rvdh** [comment]
@hodgesrm I'm trying to run the system tests, but they seem to assume the credentials provided are for a vCloud admin. My organisation is paying for a VDC admin account / resources. As such, these methods in system_test_framework/base_test.py:

  ```
  Environment.attach_vc()
  Environment.create_pvdc()
  Environment.create_org()
  Environment.create_users()
  Environment.create_ovdc()
```

All fail because of insufficient rights. If I comment them out, I think some required initialisation isn't done, because I get more errors (about an OrgVDC not existing, but it does). 

So it looks like these tests weren't designed to be run with accounts with only VDC access. Is there a way for me to get easy access to a vCloud environment with admin rights? Or should the system tests be re-written to allow testing with a VDC account (as was always possible in the past - I just supplied the organisation and VDC information).

**Comment by hodgesrm** [comment]
Hi @rvdh!  Thanks for the message.  That's a great question--to be honest we didn't even consider it  in the system test redesign.  I'm going to ask @rocknes to weigh in on this as he's developing the code.  We'll come up with a recommendation as quickly as possible to unblock you. 

Speaking of unblocking, I have a pending PR that adds additional recommendations on system test development to the system_tests/README.md.  It should clear review soon.  If you want to have a look at https://github.com/vmware/pyvcloud/pull/245 you'll see the proposed documentation there.

**Comment by hodgesrm** [comment]
Hi @rvdh, we had a look at the question you raised about system tests with only VDC access.  At this time that's out of scope for us though we might implement it later on. 

Therefore our best option is to evaluate your PR with the existing unit test.  We'll take the responsibility for converting to the new test format.

**Comment by hodgesrm** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pyvcloud/vcd/vapp.py, line 299 at r3](https://reviewable.io/reviews/vmware/pyvcloud/242#-LDJSvdP2y5Bafi48iwP:-LDJSvdP2y5Bafi48iwQ:b-uro5jb) ([raw file](https://github.com/vmware/pyvcloud/blob/0c81efbb139ccea75a3549390355f7fec4b07b09/pyvcloud/vcd/vapp.py#L299)):*
> ```Python
>         :param ip_address: (str):     the IP address assigned to this NIC.
>         :return: (TaskType) a
>          :class:`pyvcloud.schema.vcd.v1_5.schemas.admin.vCloudEntities.TaskType`
> ```

This type does not appear to be correct.  Can you check the type that is returned?  It should be an lxml.objectify.StringElement to be consistent with other calls. 

---

*[pyvcloud/vcd/vapp.py, line 671 at r3](https://reviewable.io/reviews/vmware/pyvcloud/242#-LDJTfdN2wH4c81m2NUp:-LDJTfdN2wH4c81m2NUq:b-kyvhad) ([raw file](https://github.com/vmware/pyvcloud/blob/0c81efbb139ccea75a3549390355f7fec4b07b09/pyvcloud/vcd/vapp.py#L671)):*
> ```Python
>             params.append(E.AllEULAsAccepted(all_eulas_accepted))
> 
>         self.resource = self.client.get_resource(self.href)
> ```

Why was it necessary to add this line?

---

*[tests/vcd_vapp.py, line 100 at r3](https://reviewable.io/reviews/vmware/pyvcloud/242#-LDJToVp1rNuw5Wc8U1p:-LDJToVp1rNuw5Wc8U1q:b-6zhxen) ([raw file](https://github.com/vmware/pyvcloud/blob/0c81efbb139ccea75a3549390355f7fec4b07b09/tests/vcd_vapp.py#L100)):*
> ```Python
>         assert task.get('status') == TaskStatus.SUCCESS.value
> 
>     def test_013_attach_network_to_vm(self):
> ```

Were you able to execute this case successfully and if so what was the command you used ot invoke it?  (We've had problems with this test case, hence my question.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/242)*

**Comment by rvdh** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 299 at r3](https://reviewable.io/reviews/vmware/pyvcloud/242#-LDJSvdP2y5Bafi48iwP:-LDLS25M8ctGagMfoedG:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/0c81efbb139ccea75a3549390355f7fec4b07b09/pyvcloud/vcd/vapp.py#L299)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

This type does not appear to be correct.  Can you check the type that is returned?  It should be an lxml.objectify.StringElement to be consistent with other calls. 
</blockquote></details>

Done.

---

*[pyvcloud/vcd/vapp.py, line 671 at r3](https://reviewable.io/reviews/vmware/pyvcloud/242#-LDJTfdN2wH4c81m2NUp:-LDLSAGJBbKibib06yjj:b-udqvou) ([raw file](https://github.com/vmware/pyvcloud/blob/0c81efbb139ccea75a3549390355f7fec4b07b09/pyvcloud/vcd/vapp.py#L671)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Why was it necessary to add this line?
</blockquote></details>

It wasn't, I think this was part of my debugging. I removed it and the test was still succesful. 

---

*[tests/vcd_vapp.py, line 100 at r3](https://reviewable.io/reviews/vmware/pyvcloud/242#-LDJToVp1rNuw5Wc8U1p:-LDLSHg_5GiMzmT7xXQk:brpr8eb) ([raw file](https://github.com/vmware/pyvcloud/blob/0c81efbb139ccea75a3549390355f7fec4b07b09/tests/vcd_vapp.py#L100)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Were you able to execute this case successfully and if so what was the command you used ot invoke it?  (We've had problems with this test case, hence my question.)
</blockquote></details>

I've managed to move the test to the system_tests as per your suggestion, by commenting out some stuff to get around my lack of permissions in the VDC environment. You should be able to run it now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/242)*

**Comment by rvdh** [comment]
@hodgesrm @rocknes I've moved the test to the system_tests.

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/242#-:-LDLSb7Q2PgJbZgzwj-L:b-3hslz5)*

**Comment by rvdh** [comment]
@hodgesrm I would appreciate an update :)

**Comment by hodgesrm** [comment]
@rvdh, thanks for the updates.  You are in line for review today.   Back shortly.

**Comment by rvdh** [comment]
@hodgesrm Thanks! I'm doing some rebasing right now on this PR and https://github.com/vmware/pyvcloud/pull/241 because they're a mess. Will post a comment when I'm done.

**Comment by rvdh** [comment]
@hodgesrm Done with rebasing this PR :).

**Comment by hodgesrm** [comment]
This is looking much better, thanks for rebasing!  I'm going to pull your code and try to run the system test as a double check.  Should be done this afternoon Pacific time.  I'll post final comments thereafter. 

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 299 at r3](https://reviewable.io/reviews/vmware/pyvcloud/242#-LDJSvdP2y5Bafi48iwP:-LEFNMA8DDSKu1COyW-2:btolfaz) ([raw file](https://github.com/vmware/pyvcloud/blob/0c81efbb139ccea75a3549390355f7fec4b07b09/pyvcloud/vcd/vapp.py#L299)):*
<details><summary><i>Previously, rvdh (RvdH) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry to come back on this, but it appears your return type is actually lxml.objectify.ObjectElement -- I just learned we had wrong return types from another review. (I'm working on cleaning this up in client.py as it's super confusing.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/242#-:-LEFOXSECPFkxmAi0wkH:b-b6h616)*

**Comment by hodgesrm** [comment]
Hi @rvdh, I pulled your code and ran basic tests on it.  Overall looks good.  There are a few pending comments (3 I believe).  If you can respond to these your PR will be good to merge.  Thanks!!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[system_tests/vapp_tests.py, line 371 at r4](https://reviewable.io/reviews/vmware/pyvcloud/242#-LEM8L-s14AmEahEbZ48:-LEM8L-s14AmEahEbZ49:bc50zz3) ([raw file](https://github.com/vmware/pyvcloud/blob/00ccb709c60a44bcdf9e6c1648f76e3427707388/system_tests/vapp_tests.py#L371)):*
> ```Python
>             client.logout()
> 
>     def test_0055_attach_network_to_vm(self):
> ```

Please add a docstring comment describing the proposition you are testing similar to other cases above and below.

---

*[system_tests/vapp_tests.py, line 389 at r4](https://reviewable.io/reviews/vmware/pyvcloud/242#-LEM9mJg1-asHJDVpu4G:-LEM9mJg1-asHJDVpu4H:b2ps82p) ([raw file](https://github.com/vmware/pyvcloud/blob/00ccb709c60a44bcdf9e6c1648f76e3427707388/system_tests/vapp_tests.py#L389)):*
> ```Python
>             network_name = Environment.get_default_orgvdc_network_name()
> 
>             task = vapp.attach_network_to_vm(vm_name, network_name, 0)
> ```

It appears to me that we don't clean up an existing network added by a previous execution of this case if the test is cancelled/fails.  

Assuming that reading is correct can you add an operation to detach the network (i.e., ensure it's not there) before trying to add the network?  Otherwise we may get build failures due to not cleaning up. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/242#-:-LEMA_vc17b2gHg60ttV:b-e3rehz)*

**Pull request closed without merging**
