### PR TITLE
VCDA 419 retrieve API filters

### PR DESCRIPTION
**Pull request by pacogomez**
To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
retrieve API filters registered for an extension

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

$ python -m unittest vcd_ext.TestExtension -v
test_0001_get_extension (vcd_ext.TestExtension) ... ok

----------------------------------------------------------------------
Ran 1 test in 2.105s

OK

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/166)

### CODE REVIEW

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/pyvcloud/166#-L26et35Ntdy5MSCvNxU:-L26et35Ntdy5MSCvNxV:b-xgrgee) (no related file):*
For my understanding, can you please add any documentation links on api filters and their usage here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/166#-:-L26f7voDAKeCAGHw08m:bnfp4nl)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/pyvcloud/166#-L26et35Ntdy5MSCvNxU:-L26zJvYKQRP5z7kiKZt:b4io3xy) (no related file):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

For my understanding, can you please add any documentation links on api filters and their usage here?
</blockquote></details>

This is to define what URLs will be used for an API extension.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/166)*

**Comment by rocknes** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ChangeLog, line 17 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/166#-L2FySOTx1uOEQtLQdeO:-L2FySOTx1uOEQtLQdeP:blf8a9o) ([raw file](https://github.com/vmware/pyvcloud/blob/a5f9f8b942aef47ac005b0fce4aef762559fdfff/ChangeLog#L17)):*
> ```
> * cleanup and new options
> * VCDA-213 cleanup pyvcloud repository
> * auto
> ```

Looks like incomplete copy paste.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/166#-:-L2FzFX1caYCbdOkfWzi:bnfp4nl)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ChangeLog, line 17 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/166#-L2FySOTx1uOEQtLQdeO:-L2OiCVQMVFr789D5L73:b-ld30w4) ([raw file](https://github.com/vmware/pyvcloud/blob/a5f9f8b942aef47ac005b0fce4aef762559fdfff/ChangeLog#L17)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Looks like incomplete copy paste.
</blockquote></details>

this is merged automatically, I will take a look

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/166)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ChangeLog, line 17 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/166#-L2FySOTx1uOEQtLQdeO:-L2OkHvxwJY3uRmGunGo:bke3vew) ([raw file](https://github.com/vmware/pyvcloud/blob/f942c6027205e8d7c03cf97c41bc71900fe2360d/ChangeLog#L17)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

this is merged automatically, I will take a look
</blockquote></details>

it was entered as is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/166)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ChangeLog, line 17 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/166#-L2FySOTx1uOEQtLQdeO:-L2OkM3Z-ZsHNjBwpfHh:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/f942c6027205e8d7c03cf97c41bc71900fe2360d/ChangeLog#L17)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

it was entered as is
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/166)*

**Pull request merged**
