### PR TITLE
[VCDA-2669] Add VCDApiVersion object for easy version comparison

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Create a version class for easy comparison of version objects

Testing done:
* Checked if comparisons are as expected.
* Added 37-alpha version to supported api version list
* Checked if login works properly after the changes

@rocknes @sakthisunda

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/776)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/776)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[pyvcloud/vcd/client.py, line 31 at r1](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiRxHAmAt8cDjfpKOqe:-MiRxHAmAt8cDjfpKOqf:bkjr7sj) ([raw file](https://github.com/vmware/pyvcloud/blob/2c6f6a3ea20fabfb482a8fdb37f98e8203726e87/pyvcloud/vcd/client.py#L31)):*
> ```Python
> import requests
> 
> from pyvcloud.vcd.vcd_api_version import VCDApiVersion
> ```

Is vcd_api_version an existing module ?

**Review by rocknes — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/776)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[pyvcloud/vcd/client.py, line 31 at r1](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiRxHAmAt8cDjfpKOqe:-MiSe30a-FyTXNYhl2wI:b-30owb4) ([raw file](https://github.com/vmware/pyvcloud/blob/2c6f6a3ea20fabfb482a8fdb37f98e8203726e87/pyvcloud/vcd/client.py#L31)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Is vcd_api_version an existing module ?  
</blockquote></details>

I think he forgot to add the file to the PR :P Great  catch Sakthi :)

**Comment by Anirudh9794** [comment]
___
*[pyvcloud/vcd/client.py, line 31 at r1](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiRxHAmAt8cDjfpKOqe:-MiTIKZj6JpzBKRNXIa4:b-ubhlez) ([raw file](https://github.com/vmware/pyvcloud/blob/2c6f6a3ea20fabfb482a8fdb37f98e8203726e87/pyvcloud/vcd/client.py#L31)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think he forgot to add the file to the PR :P Great  catch Sakthi :)
</blockquote></details>

sorry about that, Added the missing module

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/776)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[pyvcloud/vcd/vcd_api_version.py, line 33 at r2](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiTdtWG9wpSjjiNPc_R:-MiTdtWG9wpSjjiNPc_S:bwl4pon) ([raw file](https://github.com/vmware/pyvcloud/blob/9e9ade23d5d95ab940a775c08dcd122230a86be4/pyvcloud/vcd/vcd_api_version.py#L33)):*
> ```Python
> 
>     def __gte__(self, vcd_api_version):
>         return not self.__lt__(vcd_api_version)
> ```

Are all the above methods __eq__ , __lt__, __gt__ , __lte__ and __gte__ really required. Even otherwise, straight comparison of Version inherited objects should be possible. right?

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/776)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[pyvcloud/vcd/vcd_api_version.py, line 33 at r2](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiTdtWG9wpSjjiNPc_R:-MiTen2i5TqlozM3sZd8:b-o7s5km) ([raw file](https://github.com/vmware/pyvcloud/blob/9e9ade23d5d95ab940a775c08dcd122230a86be4/pyvcloud/vcd/vcd_api_version.py#L33)):*
> Are all the above methods eq , lt, gt , lte and gte really required?. Even otherwise, straight comparison of Version inherited objects should be possible. right?

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/776)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[pyvcloud/vcd/client.py, line 854 at r2](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiThJnQ1aJhHuH1-bmA:-MiThJnQ1aJhHuH1-bmB:b-ziidsx) ([raw file](https://github.com/vmware/pyvcloud/blob/9e9ade23d5d95ab940a775c08dcd122230a86be4/pyvcloud/vcd/client.py#L854)):*
> ```Python
>         if not self._api_version:
>             self._logger.debug("Negotiating API version")
>             active_versions = self.get_supported_versions_list()
> ```

FYI: This will skip any alpha versions, which is fine in my opinion, do add this behavior as doc string of the methods that calls the _negotiate_api_version method.
___
*[pyvcloud/vcd/client.py, line 937 at r2](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiTgXWG0vCdTEj99YAZ:-MiTgXWHCuMqxBMwzO2R:b-c57qvu) ([raw file](https://github.com/vmware/pyvcloud/blob/9e9ade23d5d95ab940a775c08dcd122230a86be4/pyvcloud/vcd/client.py#L937)):*
> ```Python
>                 for version in versions.AlphaVersion:
>                     if not hasattr(version, 'deprecated') or \
>                             version.get('deprecated') == 'false':
> ```

Adding a .lower() would be advisable to avoid case sensitivity while checking for 'false'
___
*[pyvcloud/vcd/client.py, line 939 at r2](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiTgu2f4dHIdt7Sc6yq:-MiTgu2f4dHIdt7Sc6yr:beranx6) ([raw file](https://github.com/vmware/pyvcloud/blob/9e9ade23d5d95ab940a775c08dcd122230a86be4/pyvcloud/vcd/client.py#L939)):*
> ```Python
>                             version.get('deprecated') == 'false':
>                         active_versions.append(str(version.Version.text))
>             active_versions.sort(key=VCDApiVersion)
> ```

This feels a bit weird .. this is a list of strings but we are asking it to be sorted as VCDApiVersion objects.
Can you please check this piece of code out?

Also please make sure that the returned list is indeed of type list[string]
___
*[pyvcloud/vcd/vcd_api_version.py, line 9 at r2](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiTfnVO7BHYaFw2Kxz9:-MiTfnVP3ATY1N3l5WYc:b-xbzwcp) ([raw file](https://github.com/vmware/pyvcloud/blob/9e9ade23d5d95ab940a775c08dcd122230a86be4/pyvcloud/vcd/vcd_api_version.py#L9)):*
> ```Python
> 
>     def __eq__(self, vcd_api_version):
>         if vcd_api_version.is_prerelease and self.is_prerelease and \
> ```

Can you please add a comment explaining why this particular check is necessary?

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/776)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

**Review by rocknes — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/776#-:-Mi_SzEt7batJ_btHGes:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/776)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[pyvcloud/vcd/client.py, line 854 at r2](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiThJnQ1aJhHuH1-bmA:-Mib0GZp2KGB7fSSmC6x:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/9e9ade23d5d95ab940a775c08dcd122230a86be4/pyvcloud/vcd/client.py#L854)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

FYI: This will skip any alpha versions, which is fine in my opinion, do add this behavior as doc string of the methods that calls the _negotiate_api_version method.
</blockquote></details>

Done.
___
*[pyvcloud/vcd/client.py, line 937 at r2](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiTgXWG0vCdTEj99YAZ:-MiXnDDhEPlwtS2iPc99:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/9e9ade23d5d95ab940a775c08dcd122230a86be4/pyvcloud/vcd/client.py#L937)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Adding a .lower() would be advisable to avoid case sensitivity while checking for 'false'
</blockquote></details>

Done.
___
*[pyvcloud/vcd/client.py, line 939 at r2](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiTgu2f4dHIdt7Sc6yq:-MiXpsWjAUik3fUkcFJn:biownf1) ([raw file](https://github.com/vmware/pyvcloud/blob/9e9ade23d5d95ab940a775c08dcd122230a86be4/pyvcloud/vcd/client.py#L939)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This feels a bit weird .. this is a list of strings but we are asking it to be sorted as VCDApiVersion objects.
Can you please check this piece of code out?

Also please make sure that the returned list is indeed of type list[string]
</blockquote></details>

Verified that sorting using key as VCDApiVersion works fine.
Also verified that the returned list contains strings
___
*[pyvcloud/vcd/vcd_api_version.py, line 9 at r2](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiTfnVO7BHYaFw2Kxz9:-Mib-jpo6ymbgltweC0L:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/9e9ade23d5d95ab940a775c08dcd122230a86be4/pyvcloud/vcd/vcd_api_version.py#L9)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Can you please add a comment explaining why this particular check is necessary?
</blockquote></details>

Done.
___
*[pyvcloud/vcd/vcd_api_version.py, line 33 at r2](https://reviewable.io/reviews/vmware/pyvcloud/776#-MiTdtWG9wpSjjiNPc_R:-Mib-oezE-65HJ8v2ZQv:bsnuc4t) ([raw file](https://github.com/vmware/pyvcloud/blob/9e9ade23d5d95ab940a775c08dcd122230a86be4/pyvcloud/vcd/vcd_api_version.py#L33)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> Are all the above methods eq , lt, gt , lte and gte really required?. Even otherwise, straight comparison of Version inherited objects should be possible. right?
</blockquote></details>

Added comment in the class explaining why the comparison operators should be overloaded.

**Pull request merged**
