### PR TITLE
VCDA-229 & VCDA-455: Show Info of Right and Role

### PR DESCRIPTION
**Pull request by sahithi**
1. Implementation of Role Info command
2. Implementation of Right Info command
3. Renamed method org.get_role() -> org.get_role_record() & org.get_right() -> org.get_right_record()

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/176)

### CODE REVIEW

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/176#-:-L3B7wS5yJEnGBCdMwa6:bnfp4nl)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 566 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/176#-L3F6K38QzimPf9U6mR2:-L3F6K38QzimPf9U6mR3:bz2jfwg) ([raw file](https://github.com/vmware/pyvcloud/blob/000fd6ad9205a0df7ceb05dea82fdcd7d35878fa/pyvcloud/vcd/org.py#L566)):*
> ```Python
>         """Retrieves resource of a given role.
> 
>         :param role_name: name of the role
> ```

missing type of  the param

---

*[pyvcloud/vcd/org.py, line 670 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/176#-L3F6O1VuY-TdMvQDfAB:-L3F6O1VuY-TdMvQDfAC:bqxnfdo) ([raw file](https://github.com/vmware/pyvcloud/blob/000fd6ad9205a0df7ceb05dea82fdcd7d35878fa/pyvcloud/vcd/org.py#L670)):*
> ```Python
>         """Retrieves resource of a given right.
> 
>         :param right_name: name of the right
> ```

missing type of the param

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/176#-:-L3F6TkfsghTY6rnobRc:bnfp4nl)*

**Comment by sompa** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/176)*

**Comment by sompa** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/176#-:-L3FElG5lxN5J7L_DXt5:bnfp4nl)*

**Pull request merged**
