### PR TITLE
Enable configuring organization settings when orgnization is created

### LINKED ISSUE #406: Support for custom LDAP settings
Hi Team,

I have a requirement to configure custom LDAP settings at the time of the organization creation. I cannot find a way to do that via library. When I check the REST API reference it has OrgLdapSettings element. Is configuring LDAP not available in the module?

Reference:
https://www.vmware.com/support/vcd/doc/rest-api-doc-1.5-html/types/AdminOrgType.html

Thanks,
Chaminda

### PR DESCRIPTION
**Pull request by cdivitotawela**
* Ability to configure VAppLease settings
* Ability to configure LDAP settings
* Backward compatibility is maintained by keeping new parameter settings options with default value

Unit tests:
Unit test vcd_org_settings.py added covering VAppLease and LDAP configuration

Signed-off-by: Chaminda Divitotawela <cdivitotawela@gmail.com>

Fixes #406

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/476)

### CODE REVIEW

**Comment by cdivitotawela** [comment]
@rocknes @pacogomez could you advice how the PR approval process work. Is there anything further I need to do?

**Comment by azzamsa** [comment]
Works well in on my end. 

Any reason that prevents this PR from being merged?

**Comment by azzamsa** [comment]
@cdivitotawela would you like to share the reason for closing this PR?

**Comment by cdivitotawela** [comment]
> @cdivitotawela would you like to share the reason for closing this PR?

Unfortunately I am no longer working on VMWare products and won't be able to support on the PR. Hope someone actively working on the product can pick up the changes.

**Comment by azzamsa** [comment]
Thanks a lot for your PR. 

We have been using it for over a year in production.

**Comment by cdivitotawela** [comment]
> Thanks a lot for your PR.
> 
> We have been using it for over a year in production.

Nice to hear that. Would you please create a PR from same code and try to merge it. I have not worked with pyvcloud for more than 1 year so don't have the touch to work on this. I have no objection anyone creating another PR with same code and merge to main :)

**Comment by azzamsa** [comment]
No, I give up.

- https://github.com/vmware/pyvcloud/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Aazzamsa
- https://github.com/vmware/vcd-cli/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Aazzamsa

We maintain our own fork: https://github.com/BiznetGIO/pyvcloud

**Pull request closed without merging**
