### PR TITLE
Exception class hierarchy implementation

### PR DESCRIPTION
**Pull request by anusuyar**
Created the new Exception class hierarchy for pyvcloud.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/230)

### CODE REVIEW

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/230#-:-LAQTQAS4Ei1lWy9gwIJ:bnfp4nl)*

**Comment by hodgesrm** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/230)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/230#-:-LAUOY2C14nEbwBP_1Vl:bnfp4nl)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/230#-:-LBNf40u100j5arvuhny:bnfp4nl)*

**Comment by hodgesrm** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/230)*

**Pull request merged**
