### PR TITLE
[VCDA-633 and VCDA-586] Refactored org.py and added catalog system tests

### PR DESCRIPTION
**Pull request by rocknes**
* Added missing doc-strings.
* Refactored implementation of catalog operations to use post/put/delete_linked_resource instead of hand crafted hrefs.
* Added Catalog system tests

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/247)

### CODE REVIEW

**Comment by rocknes** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 69 at r1](https://reviewable.io/reviews/vmware/pyvcloud/247#-LEFISzJAWkQNAFGLVBe:-LELbAlJ-0hcb1I36dY9:b-w8msgo) ([raw file](https://github.com/vmware/pyvcloud/blob/321b6800049d71c0ba78e14d0b2fe5d793969c08/pyvcloud/vcd/org.py#L69)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Typo: representation.   Would also be helpful to describe when this function is needed to reduce hair-on-fire bugs when clients forget to reload. :)
</blockquote></details>

Fixed. Added extra comment on the use of the reload() method.

---

*[pyvcloud/vcd/org.py, line 91 at r1](https://reviewable.io/reviews/vmware/pyvcloud/247#-LEFCUC46NAaP4kIL8w3:-LEL97JqEuV8JoATlxAb:b-7c34of) ([raw file](https://github.com/vmware/pyvcloud/blob/321b6800049d71c0ba78e14d0b2fe5d793969c08/pyvcloud/vcd/org.py#L91)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

What is the exact element type returned?  I have struggled with this as it's hard to tell what you are holding as a client and what properties it has.  Should at least be 'catalog' for consistency with other calls.
</blockquote></details>

As discussed over call, this comment is no longer valid.

---

*[pyvcloud/vcd/org.py, line 147 at r1](https://reviewable.io/reviews/vmware/pyvcloud/247#-LEFDTccAr_J8A_UP18P:-LELbJwp5tztmXUCYGlS:bfwkz2n) ([raw file](https://github.com/vmware/pyvcloud/blob/321b6800049d71c0ba78e14d0b2fe5d793969c08/pyvcloud/vcd/org.py#L147)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

This return type is clearer but do you think we can perhaps link to the vCD entity type?  (Just starting the conversation, let's at least apply this style consistently on any lxml objectified element as you do say what it represents.)
</blockquote></details>

Yes, I agree, as discussed over the call, we need to figure out a way to reference <x>Type objects in vCD ReST documentation.
For the time being, I am leaving mention of EntityType.<x> which evaluates to the actual xml schema types. vCD users should be familiar with those xml schemas. If not, they can search those online. 

---

*[pyvcloud/vcd/org.py, line 221 at r1](https://reviewable.io/reviews/vmware/pyvcloud/247#-LEFEgcz4P3NJrPsqts0:-LEL6k0y6QflSAdviQAe:busn702) ([raw file](https://github.com/vmware/pyvcloud/blob/321b6800049d71c0ba78e14d0b2fe5d793969c08/pyvcloud/vcd/org.py#L221)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

This style of param comment does not parse correctly in Sphinx generated documentation.  You have to use :param str catalog_name: to get the type to show up correctly, according to my experiments.

(Is this style PEP'ed anywhere?)
</blockquote></details>

As discussed on the call, the current doc string format generates usable documents via sphinx. However we should revisit this issue once we pickup the story to clean all doc-strings across the project.

---

*[pyvcloud/vcd/org.py, line 959 at r1](https://reviewable.io/reviews/vmware/pyvcloud/247#-LEFGXy50gJTkxy75HQZ:-LELbjV409f-DUtCKt8s:b7inl0) ([raw file](https://github.com/vmware/pyvcloud/blob/321b6800049d71c0ba78e14d0b2fe5d793969c08/pyvcloud/vcd/org.py#L959)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Return type appears to be an lxml.objectified type if I'm reading the code correctly rather than a RoleType.
</blockquote></details>

Yes, there are other instances of doc-string referring to UserType, OrgRecordType etc. Have fixed all of them.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/247)*

**Comment by rocknes** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vmware/pyvcloud/247#-LEFIFwz9NTyqRKqsQNu:-LEL6EUi4Vd6OLRfJ28Y:b-52e1pg) (no related file):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Refactoring overall looks great, plus new test cases are much needed.  Thanks for the hard work. 

In a future PR we should add some documentation on objectified types.  They are key to understanding what's going on in the API. 
</blockquote></details>

Added extra documentation for objectified types :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/247)*

**Comment by hodgesrm** [comment]
:lgtm:   Thanks for the opportunity to review.  A learning experience as always!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pyvcloud/vcd/org.py, line 938 at r2](https://reviewable.io/reviews/vmware/pyvcloud/247#-LEPeOLw3t_5hpqNORdV:-LEPeOLw3t_5hpqNORdW:bhcz9sz) ([raw file](https://github.com/vmware/pyvcloud/blob/087224863145a6523efc4016276b251a749a4c69/pyvcloud/vcd/org.py#L938)):*
> ```Python
>         :return: A generator object capable of generating
>             :class:`lxml.objectify.ObjectifiedElement` objects, which contains
>             QueryResultUserRecordType XML data representaing a user.
> ```

Typo: representaing (no need to get back to me)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/247#-:-LEPegFPBq1qZJo13xKW:b-j7jkil)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/247#-:-LEQqF8T4hCaw_RzHn0Y:bnfp4nl)*

**Pull request merged**
