### PR TITLE
VCDA-344,367:Reset/Deploy vapp/vm

### PR DESCRIPTION
**Pull request by sompa**
- Includes SDK methods for resetting and deploying a vapp or VM(s) within a vapp

- Added SDK methods for deploying a vApp/VM
  Added SDK methods for resetting a vApp/VM
   Command : **vcd vapp reset sompa-vapp vAppTemplate2 vAppTemplate1**

```
Are you sure you want to reset the vApp or VM(s)? [y/N]: y
vappReset: Resetting Virtual Machine vAppTemplate2(a631e3bb-80a0-47c8-b45e-070321f3621c)
vappReset: Resetting Virtual Machine vAppTemplate2(a631e3bb-80a0-47c8-b45e-070321f3621c)
task: f054db3a-f17a-4338-9937-494e295859fd, Reset Virtual Machine vAppTemplate2(a631e3bb-80a0-47c8-b45e-070321f3621c), result: success
vappReset: Resetting Virtual Machine vAppTemplate1(b455d13b-b66d-484a-82bb-f439a5faea0d)
vappReset: Resetting Virtual Machine vAppTemplate1(b455d13b-b66d-484a-82bb-f439a5faea0d)
task: e870fd9a-ff8d-488e-80a1-81e4eb86031e, Reset Virtual Machine vAppTemplate1(b455d13b-b66d-484a-82bb-f439a5faea0d), result: success
```
Command: **vcd vapp deploy sompa-vapp vAppTemplate1  vAppTemplate2 --power-off** 
Will deploy the vApp/VM in partially running state. Please refer docs for additional info.
```
vappDeploy: Starting Virtual Machine vAppTemplate1(b455d13b-b66d-484a-82bb-f439a5faea0d)
vappDeploy: Starting Virtual Machine vAppTemplate1(b455d13b-b66d-484a-82bb-f439a5faea0d)
task: 79bfcea6-1809-4d43-8247-dd60431494a7, Running Virtual Machine vAppTemplate1(b455d13b-b66d-484a-82bb-f439a5faea0d), result: success
vappDeploy: Starting Virtual Machine vAppTemplate2(a631e3bb-80a0-47c8-b45e-070321f3621c)
vappDeploy: Starting Virtual Machine vAppTemplate2(a631e3bb-80a0-47c8-b45e-070321f3621c)
task: c381fc7a-3e6c-443e-a773-20ea69241e54, Running Virtual Machine vAppTemplate2(a631e3bb-80a0-47c8-b45e-070321f3621c), result: success

```

  Unit tests added for the above to SDK methods.
Tests Run:
(pyvcloud) malakars-m01:tests malakars$ python -m unittest vcd_vapp_vm.TestVAppVM.test_1002_deploy_vapp
.
----------------------------------------------------------------------
Ran 1 test in 9.402s

OK
(pyvcloud) malakars-m01:tests malakars$ python -m unittest vcd_vapp_vm.TestVAppVM.test_1003_reset_vapp
.
----------------------------------------------------------------------
Ran 1 test in 17.906s

OK

- @rocknes @pacogomez @sahithi @anusuyar @hodgesrm

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/180)

### CODE REVIEW

**Comment by pacogomez** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/client.py, line 166 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F57SctSiRe1ZN0ES5:-L3F57SctSiRe1ZN0ES6:baeaiqy) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/client.py#L166)):*
> ```Python
>     SNAPSHOT_REVERT_TO_CURRENT = 'snapshot:revertToCurrent'
>     TASK_CANCEL = 'task:cancel'
>     DEPLOY = 'deploy'
> ```

it should be defined in alphabetical order

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by pacogomez** [comment]
Reviewed 3 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 156 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F5X_kzLBJme4zX7bT:-L3F5X_kzLBJme4zX7bU:b-6jkmsr) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L156)):*
> ```Python
> 
>         :param power_on: (bool): True by default, unless otherwise specified.
>         :param force_customization: (bool): Used to specify whether to force \
> ```

nit: no need for backslash, continuation line should have an extra margin

---

*[pyvcloud/vcd/vapp.py, line 165 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F5n5HHBCXC-vFGazg:-L3F5n5HHBCXC-vFGazh:b7sb6nf) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L165)):*
> ```Python
>             self.resource = self.client.get_resource(self.href)
>         deploy_vapp_params = E.DeployVAppParams()
>         deploy_vapp_params.set('powerOn', str(power_on).lower())
> ```

these parameters should be defined as `None` by default and added to the params object only if they are not None

---

*[pyvcloud/vcd/vapp.py, line 199 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F5JcXDSifQv5IeKLB:-L3F5JcXDSifQv5IeKLC:bvn7v16) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L199)):*
> ```Python
> 
>     def power_reset(self):
>         """Resets  a vApp.
> ```

extra white space

---

*[pyvcloud/vcd/vapp.py, line 201 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F5N1BIyXlkGg9hzUn:-L3F5N1BIyXlkGg9hzUo:bkqd1yn) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L201)):*
> ```Python
>         """Resets  a vApp.
> 
>         :return: A :class:`lxml.objectify.StringElement` object describing \
> ```

no need for backslash

---

*[pyvcloud/vcd/vm.py, line 134 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F62dXhZWHkxJLXnul:-L3F62dXhZWHkxJLXnum:b-s1h4w1) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vm.py#L134)):*
> ```Python
>             self.resource = self.client.get_resource(self.href)
>         deploy_vm_params = E.DeployVAppParams()
>         deploy_vm_params.set('powerOn', str(power_on).lower())
> ```

see my comment above about params

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by pacogomez** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by anusuyar** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 155 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F8pq6giNWO39UCdnq:-L3F8pq6giNWO39UCdnr:beusbzh) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L155)):*
> ```Python
>         Deploying the vApp will allocate all resources assigned to the vApp.
> 
>         :param power_on: (bool): True by default, unless otherwise specified.
> ```

we need to describe what this param does .

---

*[pyvcloud/vcd/vm.py, line 120 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F98Kn37ocrTAjRT8O:-L3F98Kn37ocrTAjRT8P:b-lc0c42) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vm.py#L120)):*
> ```Python
>             self.resource, RelationType.POWER_RESET, None, None)
> 
>     def deploy(self, power_on=True,
> ```

method params should be part of the docstring

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 149 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3FIv0nkMBKojtJj69l:-L3FIv0nkMBKojtJj69m:b-psdq5b) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L149)):*
> ```Python
>             EntityType.OWNER.value)
> 
>     def deploy(self, power_on=True,
> ```

Can you add #TODO with Jira task# to add leasesettingseconds in future when the actual bug is fixed?

---

*[pyvcloud/vcd/vm.py, line 120 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3FJAtwR7NSUTZ7lMfJ:-L3FJAtwR7NSUTZ7lMfK:btk4jj0) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vm.py#L120)):*
> ```Python
>             self.resource, RelationType.POWER_RESET, None, None)
> 
>     def deploy(self, power_on=True,
> ```

Same, add a TODO here with Jira# for leasesettingseconds attribute

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sahithi** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vm.py, line 134 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F62dXhZWHkxJLXnul:-L3Lsppuz-aiwXYqdJ81:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vm.py#L134)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

see my comment above about params
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vm.py, line 120 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F98Kn37ocrTAjRT8O:-L3Lzqhj8RH5JTfC4UEJ:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vm.py#L120)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

method params should be part of the docstring
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vm.py, line 120 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3FJAtwR7NSUTZ7lMfJ:-L3LrtmfIzQ-MgsS5Fe7:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vm.py#L120)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Same, add a TODO here with Jira# for leasesettingseconds attribute
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vapp.py, line 201 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F5N1BIyXlkGg9hzUn:-L3LrRW1jw3W60WK10Da:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L201)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

no need for backslash
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vapp.py, line 199 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F5JcXDSifQv5IeKLB:-L3LrP1ajch7oAMVHzu3:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L199)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

extra white space
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vapp.py, line 165 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F5n5HHBCXC-vFGazg:-L3LsmFjmn8DuGi2o_Np:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L165)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

these parameters should be defined as `None` by default and added to the params object only if they are not None
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vapp.py, line 156 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F5X_kzLBJme4zX7bT:-L3FoKnHLJqGcyNdQJ65:b9o2m07) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L156)):*
> extra margin
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vapp.py, line 149 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3FIv0nkMBKojtJj69l:-L3Fn99Rh9vRpDI3tNJr:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L149)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you add #TODO with Jira task# to add leasesettingseconds in future when the actual bug is fixed?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vapp.py, line 155 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F8pq6giNWO39UCdnq:-L3FnxEw9M17AmRqjRbK:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L155)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

we need to describe what this param does .
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/client.py, line 166 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F57SctSiRe1ZN0ES5:-L3Fn2ij2ERFMrQ2A9CE:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/client.py#L166)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

it should be defined in alphabetical order
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sahithi** [comment]
:lgtm: after adding Jira task# for LeaseSettingSeconds

---

Review status: 3 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 149 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3FIv0nkMBKojtJj69l:-L3UEtNkX9E7a8K--vDT:b-z70b41) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L149)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Jira task# is missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-:-L3UF5tI0zl5W5a7DwL0:b-iitx06)*

**Comment by sompa** [comment]
>  LeaseSettingSeconds
Done. https://jira.eng.vmware.com/browse/VCDA-465

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-:-L3UH7ktax7iBrmus2jJ:b2i1co0)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vapp.py, line 149 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3FIv0nkMBKojtJj69l:-L3UHgJTcyL_Ye_ce9XX:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vapp.py#L149)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Jira task# is missing
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180)*

**Comment by sahithi** [comment]
Include Jira task# as part of TODO so that anyone from the team in the future should be able to figure out what exactly needs to be done looking at TODO. 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-:-L3UHM7fQJKUiGNnT4Wy:b6enmtt)*

**Comment by anusuyar** [comment]
:lgtm: after adding the missing params in the docstring.

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[pyvcloud/vcd/vm.py, line 120 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-L3F98Kn37ocrTAjRT8O:-L3Ucf26DYqgK1TjhrQQ:byv0vpm) ([raw file](https://github.com/vmware/pyvcloud/blob/63029b73110e231ba855ab44a4c8a764873485d7/pyvcloud/vcd/vm.py#L120)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you missed adding the params to docstring

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/180#-:-L3Uck9We0z_-3IEY283:b-srtst2)*

**Pull request merged**
