### PR TITLE
VCDA-495: Add a sample application to illustrate on-boarding

### PR DESCRIPTION
**Pull request by hodgesrm**
Created a sample script tenant-onboard.py that reads org information
from a .yaml configuration and then creates everything it finds in vCD.
If run again, the script creates anything missing and leaves existing
entities alone. Script tenant-remove.py removes the org. Sample org
information is included in tenant.yaml.

@pacogomez, @sahithi, @anusuyar

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/202)

### CODE REVIEW

**Comment by pacogomez** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/tenant.yaml, line 9 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4o5MpoehGXrqnUb47_:-L4o5MpoehGXrqnUb47a:b-fg8pab) ([raw file](https://github.com/vmware/pyvcloud/blob/4e7ab77aaed1e3720775b282dc25df1dabb560e7/examples/tenant.yaml#L9)):*
> ```YAML
> vcd_host: "10.150.199.132"
> vcd_admin_user: "administrator"
> vcd_admin_password: "s3cretPW"
> ```

It is preferable to use something like `********` for password

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/202)*

**Comment by hodgesrm** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/tenant.yaml, line 9 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4o5MpoehGXrqnUb47_:-L4rTwbc2h1fL1CbLrpW:b-cx5p0j) ([raw file](https://github.com/vmware/pyvcloud/blob/4e7ab77aaed1e3720775b282dc25df1dabb560e7/examples/tenant.yaml#L9)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

It is preferable to use something like `********` for password
</blockquote></details>

Fixed and pushed.  Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/202)*

**Comment by sahithi** [comment]
Hi Robert, Well written examples with good coverage.  I actually learnt new things from below examples. I have provided few comments on naming convention & other minor items.

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[examples/tenant-onboard.py, line 76 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rWMkLO6Pkl7pXiEL8:-L4rWMkM4zz4SrzZzp3a:b-7x0mke) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L76)):*
> ```Python
>     system = System(client, admin_resource=sys_admin_resource)
>     result = system.create_org(cfg.org, "Test Org", True)
>     org = Org(client, resource=client.get_org_by_name(cfg.org))
> ```

client.get_org_by_name() doesn't return resource. Further operations on org may fail.

Below is the right usage and eliminates the need for reload(). It may not make sense for user to call reload() on just created org.
org_record = client.get_org_by_name(cfg.org))
Org(client, href = org_record.get('href')

---

*[examples/tenant-onboard.py, line 88 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rXbNi0m2LXjSuMD2I:-L4rXbNi0m2LXjSuMD2J:bn4ukbq) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L88)):*
> ```Python
> except Exception:
>     print("User does not exist, creating: {0}".format(cfg.user['name']))
>     role = org.get_role_record(cfg.user['role'])
> ```

Rename the variable 'role' to 'role_record'.
Consistent and clear naming convention (for variables) in the sample example can help users to get familiarized with different object types an entity can be retrieved in viz., record, resource, reference.

---

*[examples/tenant-onboard.py, line 89 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4r_0kuf5olDYHSv4Po:-L4r_0kuf5olDYHSv4Pp:b-75x1ax) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L89)):*
> ```Python
>     print("User does not exist, creating: {0}".format(cfg.user['name']))
>     role = org.get_role_record(cfg.user['role'])
>     result = org.create_user(user_name=cfg.user['name'],
> ```

rename 'result' to 'user_resource'

---

*[examples/tenant-onboard.py, line 92 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4r_ZdQu5g8_4yTiVWy:-L4r_ZdQu5g8_4yTiVWz:brxd5fh) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L92)):*
> ```Python
>                              password=cfg.user['password'],
>                              role_href=role.get('href'))
>     user_resource = org.get_user(cfg.user['name'])
> ```

This call seems redundant here. user_resource can be obtained from org.create_user(..)

---

*[examples/tenant-onboard.py, line 93 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4r_HOKip0t4kzK-Pj0:-L4r_HOKip0t4kzK-Pj1:b-vqam3t) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L93)):*
> ```Python
>                              role_href=role.get('href'))
>     user_resource = org.get_user(cfg.user['name'])
>     print("User now exists: {0}".format(cfg.user['name']))
> ```

replace cfg.user['name'] with user_resource.get('name') 

---

*[examples/tenant-onboard.py, line 108 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4raJnPaMl-bM_mqdyf:-L4raJnPaMl-bM_mqdyg:bmu1dvj) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L108)):*

>  vdc = VDC(client, resource=org.get_vdc(cfg.vdc['vdc_name']))

can be replaced by

vdc = VDC(client, resource=vdc_resource) //vdc_resource received is the latest version of vdc.

I think we need to convey the message to users (via sample example) that they need to call org.reload() method before invoking a new operation on the org as opposed to reloading after every org operation. For that matter entity could be anything vdc, vapp etc.

for example: 
//create catalogs
org.create_catalog(cat1) 
org.create_catalog(cat2)
org.create_catalog(cat3)

//get catalogs
org.reload()
org.get_catalogs()

The current style may teach user to write something like this:

org.create_catalog(cat1)
org.reload(()
org.create_catalog(cat2)
org.reload()

org.get_catalogs()
-------------------------------------------------------------
There is nothing wrong with both the examples. Second approach is definitely safest way to prevent errors but can give a performance hit. Somehow we should try to convey a message to the users that reload() method is a must before invoking certain operations. For example  vapp.shutdown() cannot immediately follow vapp.poweron(), There needs to be reload() in between. At the same time calling it multiple times can get redundant for other examples.

---

*[examples/tenant-onboard.py, line 119 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rfdRM_5wLbePgbuw5:-L4rfdRNzO655vgQZVTD:bajzuit) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L119)):*
> ```Python
>     print("Catalog does not exist, creating: {0}".format(cfg.catalog['name']))
>     catalog_kwargs = cfg.catalog
>     result = org.create_catalog(**catalog_kwargs)
> ```

result -> catalog_resource

---

*[examples/tenant-onboard.py, line 121 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rfitH3nbzulMeNQLh:-L4rfitH3nbzulMeNQLi:b-mu0t41) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L121)):*
> ```Python
>     result = org.create_catalog(**catalog_kwargs)
>     org.reload()
>     catalog_resource = org.get_catalog_resource(cfg.catalog['name'])
> ```

remove this line

---

*[examples/tenant-onboard.py, line 122 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rfkzmH2B6pDS7kYHI:-L4rfkzmH2B6pDS7kYHJ:butr3yl) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L122)):*
> ```Python
>     org.reload()
>     catalog_resource = org.get_catalog_resource(cfg.catalog['name'])
>     print("Catalog now exists: {0}".format(cfg.catalog['name']))
> ```

catalog_resource.get('name')

---

*[examples/tenant-onboard.py, line 125 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rgCC82vyOXS0CMLiF:-L4rgCC82vyOXS0CMLiG:bhyass4) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L125)):*
> ```Python
> 
> # Check for OVF templates in the catalog and upload them if they are missing.
> for entry in cfg.templates:
> ```

rename entry -> catalog_item; cfg.templates -> cfg.catalog_items

---

*[examples/tenant-onboard.py, line 157 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rgxqsLokGVorA4RKE:-L4rgxqsLokGVorA4RKF:bo9u7n1) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L157)):*
> ```Python
>             entry['catalog_name'], entry['item_name'])
>         resource_type = 'adminCatalogItem'
>         q = client.get_typed_query(
> ```

q -> query

---

*[examples/tenant-onboard.py, line 186 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rhGHc5RJUnKgjEVrj:-L4rhGHc5RJUnKgjEVrk:bqaasmk) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L186)):*
> ```Python
>     for network in cfg.networks['isolated']:
>         isolated_network_list = vdc.list_orgvdc_network_resources(
>             name=network['network_name'], type='isolated')
> ```

type='isolated', I remember someone using enum value. Anusuya?
@anusuyar 

---

*[examples/tenant-remove.py, line 60 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rhlY_bRP-duDgkcIP:-L4rhlYaUSjvTPpZK60B:b-li76t3) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-remove.py#L60)):*
> ```Python
> print("Fetching Org...")
> try:
>     org_resource = client.get_org_by_name(cfg.org)
> ```

org_resource -> org_record

---

*[examples/tenant.yaml, line 50 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rhzTpWGKp0xhxYSD2:-L4rhzTpWGKp0xhxYSD3:b-7uelah) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant.yaml#L50)):*
> ```YAML
> # One or more items that will be loaded in the catalog. Specify the full
> # path of files. 
> templates: 
> ```

templates -> catalog_items

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-:-L4ri8ol7m8F7pXF_eoE:bal74nf)*

**Comment by hodgesrm** [comment]
Thank you.  I have made all requested changes and will push after a round of careful testing. 

---

Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[examples/tenant-onboard.py, line 76 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rWMkLO6Pkl7pXiEL8:-L4vfD1xya4wEkYd4sH2:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L76)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

client.get_org_by_name() doesn't return resource. Further operations on org may fail.

Below is the right usage and eliminates the need for reload(). It may not make sense for user to call reload() on just created org.
org_record = client.get_org_by_name(cfg.org))
Org(client, href = org_record.get('href')
</blockquote></details>

Done.

---

*[examples/tenant-onboard.py, line 88 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rXbNi0m2LXjSuMD2I:-L4vfEK3x9-nFdWSZ22E:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L88)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Rename the variable 'role' to 'role_record'.
Consistent and clear naming convention (for variables) in the sample example can help users to get familiarized with different object types an entity can be retrieved in viz., record, resource, reference.
</blockquote></details>

Done.

---

*[examples/tenant-onboard.py, line 89 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4r_0kuf5olDYHSv4Po:-L4w4CxdkJWJMdbmM7WX:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L89)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

rename 'result' to 'user_resource'
</blockquote></details>

Done.

---

*[examples/tenant-onboard.py, line 92 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4r_ZdQu5g8_4yTiVWy:-L4vfZGo7dbBimz14Mym:ba3dfob) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L92)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This call seems redundant here. user_resource can be obtained from org.create_user(..)
</blockquote></details>

Removed

---

*[examples/tenant-onboard.py, line 93 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4r_HOKip0t4kzK-Pj0:-L4w4EuAFKvm75zsj-xl:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L93)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

replace cfg.user['name'] with user_resource.get('name') 
</blockquote></details>

Done.

---

*[examples/tenant-onboard.py, line 108 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4raJnPaMl-bM_mqdyf:-L4vhKkIVdvX7i531e63:b-aqnkub) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L108)):*
> vdc = VDC(client, resource=vdc_resource)
Thanks for the extended explanation. I'm going with the approach of reloading after an operation that affects org contents.  This is good for the example though in future it seems we should do this automatically, for example by marking objects as 'dirty' and reloading them before an operation that requires them. 

---

*[examples/tenant-onboard.py, line 119 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rfdRM_5wLbePgbuw5:-L4vhwNdYZuen_j5oJs5:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L119)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

result -> catalog_resource
</blockquote></details>

Done.

---

*[examples/tenant-onboard.py, line 121 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rfitH3nbzulMeNQLh:-L4vhurFWSrRUPrhy4_x:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L121)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

remove this line
</blockquote></details>

Done.

---

*[examples/tenant-onboard.py, line 122 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rfkzmH2B6pDS7kYHI:-L4vhxbBmPxgIwg1_FLb:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L122)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

catalog_resource.get('name')
</blockquote></details>

Done.

---

*[examples/tenant-onboard.py, line 125 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rgCC82vyOXS0CMLiF:-L4vx7OH-BpQykDqkBV3:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L125)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

rename entry -> catalog_item; cfg.templates -> cfg.catalog_items
</blockquote></details>

Done.

---

*[examples/tenant-onboard.py, line 157 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rgxqsLokGVorA4RKE:-L4vx6OBn38ZsJv2uYaw:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L157)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

q -> query
</blockquote></details>

Done.

---

*[examples/tenant-onboard.py, line 186 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rhGHc5RJUnKgjEVrj:-L4vy-49QsL7slnW06Dz:buk5ssl) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L186)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

type='isolated', I remember someone using enum value. Anusuya?
@anusuyar 
</blockquote></details>

It's FenceMode.ISOLATED.  Switched over to that, thanks. 

---

*[examples/tenant-remove.py, line 60 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rhlY_bRP-duDgkcIP:-L4w2ryvZRZlqyBAYzUN:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-remove.py#L60)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

org_resource -> org_record
</blockquote></details>

Done.

---

*[examples/tenant.yaml, line 50 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4rhzTpWGKp0xhxYSD2:-L4w358BT301Ui2dl2Ze:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant.yaml#L50)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

templates -> catalog_items
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-:-L4w4OkCP-QJcS7Knerp:btfxd4t)*

**Comment by hodgesrm** [comment]
p.s., I mean 'push a new commit' of course. :)

---

Review status: all files reviewed at latest revision, 15 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-:-L4w4ZKUSgX2i-fP0RlG:bn34s2t)*

**Comment by anusuyar** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[examples/tenant-onboard.py, line 147 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4wAN0LjWhmh9adPYZ3:-L4wAN0LjWhmh9adPYZ4:b-a3ltep) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L147)):*
> ```Python
> # use them for vApps.  The following code loops until catalog items are
> # in the right state.
> print("Checking for unresolved templates")
> ```

It is better to create a generic utility method in pyvcloud which perform this functionality.  (to wait till the state of a particular entity changes to the desired state).  We can create a task in our backlog if we want to prioritize it later.

We have many pyvclould methods which take a long time to complete. It is better to have functionality in pyvcloud than to make the user write it themselves.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/202)*

**Comment by hodgesrm** [comment]
Review status: 1 of 4 files reviewed at latest revision, 16 unresolved discussions.

---

*[examples/tenant-onboard.py, line 147 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4wAN0LjWhmh9adPYZ3:-L4x8r5EWcX2kN5grP8s:brt40d2) ([raw file](https://github.com/vmware/pyvcloud/blob/bbac7a03a4a4435d5a52b109e9fc3c3997a20b73/examples/tenant-onboard.py#L147)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

It is better to create a generic utility method in pyvcloud which perform this functionality.  (to wait till the state of a particular entity changes to the desired state).  We can create a task in our backlog if we want to prioritize it later.

We have many pyvclould methods which take a long time to complete. It is better to have functionality in pyvcloud than to make the user write it themselves.
</blockquote></details>

I definitely agree with this and will write a JIRA for it.  I think this PR should go through as now however as that's potentially a lengthy process to decide how to address those issues.  (I would also put task management in the same category.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/202)*

**Comment by anusuyar** [comment]
:lgtm: (after addressing my comments)

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[examples/tenant-onboard.py, line 172 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4xBknm1aPXvsv-Lfum:-L4xAs4bAtZcseVlEgzi:b-bz26vj) ([raw file](https://github.com/vmware/pyvcloud/blob/e8533bb7e279866cfaa4d79abf2059527fd2e9f6/examples/tenant-onboard.py#L172)):*
> ```Python
>                 catalog_item['item_name']))
>         else:
>             for r in records:
> ```

I think it will be better to avoid single letter variable. 

maybe something like below? Even it doesn't look good. but maybe we can think of a better variable name

```
for record in records
   record_dict = to_dict(record , resource_type=resource_type)
```

---

*[examples/tenant-onboard.py, line 207 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4xAQTo8X7cjtH-X5eO:-L4xAQTo8X7cjtH-X5eP:baubkro) ([raw file](https://github.com/vmware/pyvcloud/blob/e8533bb7e279866cfaa4d79abf2059527fd2e9f6/examples/tenant-onboard.py#L207)):*
> ```Python
>             while not network_exists:
>                 new_network_list = vdc.list_orgvdc_network_resources(
>                     name=network['network_name'], type='isolated')
> ```

Can we change to FenceMode.ISOLATED.value in other places as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-:-L4xCMkmg5W4mhwYbScw:ba7igs6)*

**Comment by hodgesrm** [comment]
Review status: 3 of 4 files reviewed at latest revision, 17 unresolved discussions.

---

*[examples/tenant-onboard.py, line 172 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4xBknm1aPXvsv-Lfum:-L4xJ4_vDc_Qv6ELZY-I:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/e8533bb7e279866cfaa4d79abf2059527fd2e9f6/examples/tenant-onboard.py#L172)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I think it will be better to avoid single letter variable. 

maybe something like below? Even it doesn't look good. but maybe we can think of a better variable name

```
for record in records
   record_dict = to_dict(record , resource_type=resource_type)
```
</blockquote></details>

Done.

---

*[examples/tenant-onboard.py, line 207 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-L4xAQTo8X7cjtH-X5eO:-L4xK2Moz9W6ueZUqBuc:b-y5hhga) ([raw file](https://github.com/vmware/pyvcloud/blob/e8533bb7e279866cfaa4d79abf2059527fd2e9f6/examples/tenant-onboard.py#L207)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Can we change to FenceMode.ISOLATED.value in other places as well?
</blockquote></details>

Done.  (Missed that.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/202)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/202#-:-L5BErcxONQ3zqHX9Gs8:bnfp4nl)*

**Comment by anusuyar** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/202)*

**Pull request merged**
