### PR TITLE
VCDA-213 cleanup pyvcloud repository

### PR DESCRIPTION
**Pull request by pacogomez**
see commit messages for details

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/157)

### CODE REVIEW

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 111 of 111 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/157#-:-L0vJm17dj8bNCIS0TMp:bnfp4nl)*

**Comment by eulerjiang** [comment]
Any reason to clean the VCA codes?  

After clean up, I see some method was removed like compose_vapp, create_vdc_network.  

Thanks!

**Comment by pacogomez** [comment]
We have deprecated some of the previous code, but:

**Comment by eulerjiang** [comment]
@pacogomez Thanks!

**Pull request merged**
