### PR TITLE
RevertToSnapshot and RemoveAllSnapshot functionality for VMs

### PR DESCRIPTION
**Pull request by szimszon**
This commit is about to extend the functionality of the library with two new procedure:
* revert vm back to current snapshot and
* remove all snapshot from the vm

### CODE REVIEW

**Comment by hodgesrm** [comment]
Hi @szimszon, 

Welcome back.  Your snapshot code looks good to me but I would like to request that you merge your new samples into make-vm-snapshot.py so that you have steps to create the snapshot, revert back, and remove.  This will reduce code duplication in the samples and will ensure it works on any vApp.  

Once you do that I'll clone a copy of your repo to run the new sample and unit test case(s), then merge if all goes well.  

Best regards, Robert

**Comment by szimszon** [comment]
Hi I merged the example code, but now I got:

flake8 runtests: commands[0] | flake8 pyvcloud/vcd
pyvcloud/vcd/client.py:217:5: E122 continuation line missing indentation or outdented
ERROR: InvocationError: '/home/travis/build/vmware/pyvcloud/.tox/flake8/bin/flake8 pyvcloud/vcd'

But this is not my code and I can't find any problem anyway with it... :(
What is this?

**Comment by hodgesrm** [comment]
Thanks @szimszon. I also see the flake8 error; it seems to have been introduced in a recent commit from internal work. I'll pass your note back to the person who pushed it.  Meanwhile I'll pull your code and test today.

**Comment by szimszon** [comment]
Thank you @hodgesrm !

**Comment by hodgesrm** [comment]
The flake8 problem is fixed.  If you merge from upstream and repush the Travis build should come up clean.  Thanks for pointing the problem out.  I still have to run my tests but hope to do that this afternoon.

**Comment by hodgesrm** [comment]
Hi again,  

I pulled and tested your new code.  The unit test cases look good.  I did find a problem with the example, however.  Can you add a vm.reload() command as shown by the following diff?  The in-memory resource does not automatically refresh to get a link to the snapshot after creation. Hence execution fails.  I put this in and it solves the problem.  (We're going to look at link behavior in a later release but for now it's how the API works.)

Here's the diff: 

diff --git a/examples/vm-snapshot-tasks.py b/examples/vm-snapshot-tasks.py
index 2332051..b305964 100755
--- a/examples/vm-snapshot-tasks.py
+++ b/examples/vm-snapshot-tasks.py
@@ -74,6 +74,7 @@ print("Waiting for Snapshot finish...")
 task_monitor.wait_for_success(snaphot_resource)
 
 print("Revert Back To Current Snapshot...")
+vm.reload()
 snaphot_resource = vm.snapshot_revert_to_current()
 print("Waiting for Revert finish...")
 task_monitor.wait_for_success(snaphot_resource)

If you pull from upstream again and push this change the PR will be good for merging.  The upstream pull will clear the flake8 error if you have not already done so.

Cheers, Robert

**Comment by hodgesrm** [comment]
Reviewed 2 of 6 files at r1, 1 of 1 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/206)*

**Comment by hodgesrm** [comment]
Reviewed 1 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/206)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/206#-:-L5o-NV8f7NQ_JCKfh1P:bnfp4nl)*

**Comment by hodgesrm** [comment]
Commit is merged.  Thanks again @szimszon.  Looking forward to your next PR. 👍

**Pull request merged**
