### PR TITLE
VCDA-421 & VCDA-422: Implementing SDK methods and cli commands to connect/disconnect ovdc_network to/from vapp.

### PR DESCRIPTION
**Pull request by anusuyar**
```
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd vapp disconnect v1 ovdcnet
Are you sure you want to disconnect the network? [y/N]: y
Successfully disconnected ovdc network 'ovdcnet' from vapp 'v1'

C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd vapp disconnect v1 ovdcneter
Are you sure you want to disconnect the network? [y/N]: y
Usage: vcd vapp disconnect [OPTIONS] <vapp-name> <orgvdc-network-name>

Error: Orgvdc network 'ovdcneter' is not attached to the vapp

C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd vapp connect v1 ovdcneter
Usage: vcd vapp connect [OPTIONS] <vapp-name> <orgvdc-network-name>

Error: Orgvdc network 'ovdcneter' does not exist in vdc 'vdc1'

C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd vapp connect v1 ovdcnet
Successfully connected ovdc network 'ovdcnet' to vapp 'v1'

C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd vapp connect v1 ovdcnet
Usage: vcd vapp connect [OPTIONS] <vapp-name> <orgvdc-network-name>

Error: Orgvdc network 'ovdcnet' is already connected to vapp.

```

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/190)

### CODE REVIEW

**Comment by sompa** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/vapp.py, line 616 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3cp8y3VdBO_34YJ3H7:-L3cp8y3VdBO_34YJ3H8:b-le1hj0) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L616)):*
> ```Python
> 
>     def connect_org_vdc_network(self, orgvdc_network_name, retain_ip=False,
>                                 is_deployed=False):
> ```

Please check the comments made on vcd-cli part of this, to make these (retain_ip, is_deployed) value as None.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/190)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 653 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3d9llqsRf7fUpk4naa:-L3d9llrswSdBp8ilxBo:bui12n7) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L653)):*
> ```Python
> 
>         network_config = E.Configuration(
>             E.ParentNetwork(href=orgvdc_network_href), E.FenceMode('bridged'),
> ```

Why is this 'bridged' by default? Shouldn't we let user specify?

---

*[pyvcloud/vcd/vapp.py, line 686 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3dA98Hq_H528VIr_7x:-L3dA98Hq_H528VIr_7y:b-yn01bn) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L686)):*
> ```Python
>                             % orgvdc_network_name)
>         else:
>             network_configuration_section.remove(matched_orgvdc_network_config)
> ```

Deepcopy network_configuration_section before removing elements from it. Modifying self.resource directly is error prone.

---

*[pyvcloud/vcd/vapp.py, line 693 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3dCYeZb3zDhkbx5Zjx:-L3dCYeZb3zDhkbx5Zjy:b9tkmfp) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L693)):*
> ```Python
>             network_configuration_section)
> 
>     def get_network_configuration_section(self):
> ```

Do you think this is a private method? If yes,start the method anme with '_'

---

*[pyvcloud/vcd/vapp.py, line 700 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3dBs5gYWnaNucgXVJ5:-L3dBs5gYWnaNucgXVJ6:b-qg81c7) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L700)):*
> ```Python
>         """
>         return self.client.get_resource(
>             self.resource.get('href') + '/networkConfigSection/')
> ```

Avoid using literals in constructing link unless there is no alternative.
Use find_link() or get_linked_resource()

---

*[pyvcloud/vcd/vapp.py, line 703 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3dCGgirO6FaoITHsFO:-L3dCGgirO6FaoITHsFP:b-mbczr4) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L703)):*
> ```Python
> 
>     @staticmethod
>     def search_for_network_config_by_name(orgvdc_network_name,
> ```

Seems like private method. Start the name with ' _'

---

*[pyvcloud/vcd/vapp.py, line 710 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3dCSTkrkXq8vUSQyvy:-L3dCSTkrkXq8vUSQyvz:b-d0wxhj) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L710)):*
> ```Python
>             searched.
>         :param network_configuration_section :(lxml.objectify.StringElement):
>             NetworkConfigSection of a vapp.
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/190)*

**Comment by sahithi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/190)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 656 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3dSQ-SXb4O_7TGm2Yz:-L3dSQ-TZtLk91_umicR:b-6iiw41) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L656)):*
> ```Python
>             E.RetainNetInfoAcrossDeployments(retain_ip))
> 
>         network_configuration_section.append(
> ```

Can vApp be connected to multiple networks? Could there be a possibility of conflict between existing network and the new network to be added? For example, Adding a network to a vApp with isolated network.

I may need some education here. We can discuss offline if you prefer that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/190)*

**Comment by hodgesrm** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/190)*

**Comment by anusuyar** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 616 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3cp8y3VdBO_34YJ3H7:-L3f2DLnFUKjGOzp0jc0:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L616)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Please check the comments made on vcd-cli part of this, to make these (retain_ip, is_deployed) value as None.
</blockquote></details>

Done.

---

*[pyvcloud/vcd/vapp.py, line 653 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3d9llqsRf7fUpk4naa:-L3elbhYJ8oUxQjhK2sk:b-mo0qjw) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L653)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Why is this 'bridged' by default? Shouldn't we let user specify?
</blockquote></details>

Done. we only support bridged mode when connecting to orgvdc network right now. So added a param fence_mode='bridge'. will add options for other fence_mode when we support it.

---

*[pyvcloud/vcd/vapp.py, line 656 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3dSQ-SXb4O_7TGm2Yz:-L3em7ukHrgKWfnbNWgD:bn6fxz8) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L656)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can vApp be connected to multiple networks? Could there be a possibility of conflict between existing network and the new network to be added? For example, Adding a network to a vApp with isolated network.

I may need some education here. We can discuss offline if you prefer that.
</blockquote></details>

vapp can be connected to more than one orgVDC networks. I am not sure if there will be conflict with existing and new network. If there were any, vdc will throw appropriate error.  I don't think we have to deal with those possible conflicts in pyvcloud.

---

*[pyvcloud/vcd/vapp.py, line 686 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3dA98Hq_H528VIr_7x:-L3eu6XvFXgOgcgpaiPq:b-h0yi78) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L686)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Deepcopy network_configuration_section before removing elements from it. Modifying self.resource directly is error prone.
</blockquote></details>

Done.  removed get_network_configuration_section()

---

*[pyvcloud/vcd/vapp.py, line 693 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3dCYeZb3zDhkbx5Zjx:-L3euCKhbrLewzcg6YzI:b8c6hub) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L693)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Do you think this is a private method? If yes,start the method anme with '_'
</blockquote></details>

I removed this method in this revision.

---

*[pyvcloud/vcd/vapp.py, line 700 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3dBs5gYWnaNucgXVJ5:-L3euFXUoQ5yvMp8wNlT:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L700)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Avoid using literals in constructing link unless there is no alternative.
Use find_link() or get_linked_resource()
</blockquote></details>

Done.

---

*[pyvcloud/vcd/vapp.py, line 703 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3dCGgirO6FaoITHsFO:-L3euGdrpjmwIAqWt3PO:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L703)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Seems like private method. Start the name with ' _'
</blockquote></details>

Done.

---

*[pyvcloud/vcd/vapp.py, line 710 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-L3dCSTkrkXq8vUSQyvy:-L3emjCNf2B-jU8NQVlY:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/6fd62fc6ab41e6dfbb76a048d76612e82dc3685c/pyvcloud/vcd/vapp.py#L710)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/190)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-:-L3iZjUQ4IUg7tgJ9oSP:bnfp4nl)*

**Comment by sompa** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/190#-:-L3j5yI-BX4YqjP4fk16:bnfp4nl)*

**Pull request merged**
