### PR TITLE
VCDA-311 For independent disk related operation, name of the disk can now  be None

### PR DESCRIPTION
**Pull request by rocknes**
.Added logic to handle situation when neither name nor id has been
specified.

Moved all disk related tests into vcd_disk.py
Moved out storage profile related tests to vcd_storage_profile.py

(pyvcloud) C:\code\pyvcloud\tests>python -m unittest vcd_disk.TestDisk
.........
----------------------------------------------------------------------
Ran 9 tests in 48.922s

OK

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/168)

### CODE REVIEW

**Comment by pacogomez** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/vdc.py, line 27 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/168#-L2IZo3E6TfEuhT9NDod:-L2IZo3E6TfEuhT9NDoe:b-idx9bi) ([raw file](https://github.com/vmware/pyvcloud/blob/35370f775f2961acbed8f56a9e3d0f22b5b6f289/pyvcloud/vcd/vdc.py#L27)):*
> ```Python
> from pyvcloud.vcd.utils import get_admin_href
> 
> import pprint
> ```

is this used anywhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/168)*

**Comment by rocknes** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/vdc.py, line 27 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/168#-L2IZo3E6TfEuhT9NDod:-L2IncEcWiYU3QF-NAj2:b-yeuxzd) ([raw file](https://github.com/vmware/pyvcloud/blob/35370f775f2961acbed8f56a9e3d0f22b5b6f289/pyvcloud/vcd/vdc.py#L27)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

is this used anywhere?
</blockquote></details>

No, will get rid of it. I was using it to print xml replies, forgot to remove the import

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/168)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/168#-:-L2MxqaKj54D50cz6aQN:bnfp4nl)*

**Comment by pacogomez** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/168#-:-L2Oi6QuIAlxXftSRAlh:bnfp4nl)*

**Pull request merged**
