### PR TITLE
Link/Unlink a given role to its template

### PR DESCRIPTION
**Pull request by sahithi**
1. [New] Commands for link and unlink of role to its template
2. [Fixes] Refactoring of org.list_roles()

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/164)

### CODE REVIEW

**Comment by anusuyar** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/vcd_role_right.py, line 70 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1xwmHkEZXNtsgph4K6:-L1xwmHkEZXNtsgph4K7:b-ptexhl) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/tests/vcd_role_right.py#L70)):*
> ```Python
>         role_record = org.get_role(role_name)
>         role = Role(self.client, href=role_record.get('href'))
>         role.link()
> ```

I think we should add an assert to check if the link/unlink operation has been successful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/org.py, line 573 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1yNwSpt1t_43AE2K4Q:-L1yNwSpt1t_43AE2K4R:bpj60if) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/pyvcloud/vcd/org.py#L573)):*
> Retrieve the list of role in the current Org
Change it to the above to be consistent across all docs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/org.py, line 614 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1yOVwBSmxxdZYlQLRL:-L1yOVwBSmxxdZYlQLRM:bthxze9) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/pyvcloud/vcd/org.py#L614)):*
> ```Python
>     def list_rights(self, name_filter=None):
>         """
>         Get list of rights in the current Org
> ```

"Retrieve the list of rights in the current Org. "

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/role.py, line 52 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1yOh33VQvrxgUay0Ff:-L1yOh33VQvrxgUay0Fg:b-gdl0ie) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/pyvcloud/vcd/role.py#L52)):*
> ```Python
>         Unlinks the role from its template.
>         :return: None
>         """
> ```

#NOQA is missing here. This would result in flake8 errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/role.py, line 62 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1yOsSEuuwX45A8Dhb_:-L1yOsSEuuwX45A8Dhba:box2bni) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/pyvcloud/vcd/role.py#L62)):*
> #NOQA is missing here. This would result in flake8 errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164)*

**Comment by sompa** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/role.py, line 60 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1yS1yj0sMZys6B73ZO:-L1yS1yj0sMZys6B73ZP:bjbnuux) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/pyvcloud/vcd/role.py#L60)):*
> ```Python
>     def link(self):
>         """
>         Links the role to its template.
> ```

Does this conform to the formatting standards ? Could you run the flake8 to make sure that there are no errors ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164)*

**Comment by anusuyar** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/role.py, line 60 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1yS1yj0sMZys6B73ZO:-L1yUGGBUAZ8ewKQW6Wz:b5p2jpi) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/pyvcloud/vcd/role.py#L60)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Does this conform to the formatting standards ? Could you run the flake8 to make sure that there are no errors ?
</blockquote></details>

Yes. we need to format it so that flake8 doesn't throw any warnings

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164)*

**Comment by sahithi** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 573 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1yNwSpt1t_43AE2K4Q:-L1yZNk-vZQBq_pWLSjo:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/pyvcloud/vcd/org.py#L573)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

> Retrieve the list of role in the current Org
Change it to the above to be consistent across all docs.
</blockquote></details>

Done.

---

*[pyvcloud/vcd/org.py, line 614 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1yOVwBSmxxdZYlQLRL:-L1yZNFEWBRShkYYFo_X:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/pyvcloud/vcd/org.py#L614)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

"Retrieve the list of rights in the current Org. "
</blockquote></details>

Done.

---

*[pyvcloud/vcd/role.py, line 60 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1yS1yj0sMZys6B73ZO:-L1yTzUFK0GqXrr1abjG:bl5m4uv) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/pyvcloud/vcd/role.py#L60)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Yes. we need to format it so that flake8 doesn't throw any warnings
</blockquote></details>

I inspected the code and it does not violate any Pep8 standards. Anyway, I modified it to conform to flake8 standards. 

---

*[tests/vcd_role_right.py, line 70 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1xwmHkEZXNtsgph4K6:-L1yWdeAdEWtpn9qCfsn:b7la5ku) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/tests/vcd_role_right.py#L70)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I think we should add an assert to check if the link/unlink operation has been successful.
</blockquote></details>

link() and unlink() return 204 (empty body) and vcd would throw exception if it fails for any reason.
Other existing commands like delete_user(), delete_role() also return 204 and no explicit verification is done for those tests.

We can still verify if these operations are really successful by making another rest-api call, but I think that is overkill.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-:-L1yduYYR33rURR-jafX:bnfp4nl)*

**Comment by rocknes** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pyvcloud/vcd/role.py, line 60 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1yS1yj0sMZys6B73ZO:-L2-bDATqcwPnnC5kEHd:bbj5rs4) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/pyvcloud/vcd/role.py#L60)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I inspected the code and it does not violate any Pep8 standards. Anyway, I modified it to conform to flake8 standards. 
</blockquote></details>

flake8 is a tool which validates a particular style of python code, pep8 is a standard, there are other standards e.g. the google style.

Also if possible install flake8-import-order plugin, and while running flake8 specify the param --import-order-style=pep8 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-:-L2-c3PYpu8E-KXc8QA6:bnfp4nl)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 614 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1yOVwBSmxxdZYlQLRL:-L20GOzEA8Pkh8zH5lmy:b-rtxvh7) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/pyvcloud/vcd/org.py#L614)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

format docstring

---

*[pyvcloud/vcd/org.py, line 576 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L20GAxWaZ7CLLgNf8wJ:-L20GAxWaZ7CLLgNf8wK:b2rjd82) ([raw file](https://github.com/vmware/pyvcloud/blob/410b465a50283a51dd39115ef0d714ee83f4dce0/pyvcloud/vcd/org.py#L576)):*
> ```Python
>                              'role name'
>         :return: (list): (RoleRecord) List of roles
>         """  # NOQA
> ```

Please format docstring and remove # NOQA

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[pyvcloud/vcd/role.py, line 56 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L20SNQ8KXS85rFEF94M:-L20SNQ8KXS85rFEF94N:b-cbx1h6) ([raw file](https://github.com/vmware/pyvcloud/blob/410b465a50283a51dd39115ef0d714ee83f4dce0/pyvcloud/vcd/role.py#L56)):*
> ```Python
>         if self.resource is None:
>             self.resource = self.client.get_resource(self.href)
>         self.client.post_linked_resource(
> ```

Is vCD returning any result?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164)*

**Comment by sahithi** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 614 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L1yOVwBSmxxdZYlQLRL:-L222OOEJOHkekdQs0qj:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/358615f5bec4fd29da044d1fe5b4fe5b175b9e62/pyvcloud/vcd/org.py#L614)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

format docstring
</blockquote></details>

Done.

---

*[pyvcloud/vcd/org.py, line 576 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L20GAxWaZ7CLLgNf8wJ:-L222NZMPs_z1euXdzck:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/410b465a50283a51dd39115ef0d714ee83f4dce0/pyvcloud/vcd/org.py#L576)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

Please format docstring and remove # NOQA
</blockquote></details>

Done.

---

*[pyvcloud/vcd/role.py, line 56 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/164#-L20SNQ8KXS85rFEF94M:-L222PAHk6svKhcfR9gM:b-krqard) ([raw file](https://github.com/vmware/pyvcloud/blob/410b465a50283a51dd39115ef0d714ee83f4dce0/pyvcloud/vcd/role.py#L56)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

Is vCD returning any result?
</blockquote></details>

No. Response status is 204

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/164)*

**Pull request merged**
