### PR TITLE
VCDA-365,366: Shutdown and Reboot a vapp/VM

### PR DESCRIPTION
**Pull request by sompa**
Includes SDK methods for rebooting and shutting down a vapp or VM(s) within a vapp

Added SDK methods for rebooting a vApp/VM
Added SDK methods for shutting down a vApp/VM
Added required unit tests.

**Command** : **vcd vapp shutdown sompa-vapp**
```
Are you sure you want to shutdown the vApp? [y/N]: y
vappShutdownGuest: Shutting down Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)
vappShutdownGuest: Shutting down Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)
task: 0df63085-0b7a-4bf4-9c46-203d2979655e, Shut down Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9), result: success


```
**Command:** **vcd vapp shutdown sompa-vapp vm3**
```
Are you sure you want to shutdown the vApp? [y/N]: y
vappShutdownGuest: Shutting down Virtual Machine vm3(afe0a16d-2750-43ec-a779-73073d12088c)
task: bd97d769-4de7-47b1-b5e5-49c9bf258cb7, result: error, message: [ 21bbfe02-5ce1-4247-bccc-f2f25b214d26 ] null
 - Cannot complete operation because VMware Tools is not running in this virtual machine.
(vcd-cli) malakars-m01:vcd-cli malakars$ vcd vapp reboot sompa-vapp vm3
Are you sure you want to reboot the vApp or VM(s)? [y/N]: y
vappRebootGuest: Rebooting Virtual Machine vm3(afe0a16d-2750-43ec-a779-73073d12088c)
task: f7ede655-0f53-404e-b216-e40e1a3085a6, result: error, message: [ 4d2e708f-cc9e-4f8e-8d95-bc67dc3d8fce ] Internal Server Error
 - Failed to reboot guest os for the VM "vm3 (afe0a16d-2750-43ec-a779-73073d12088c)" as required VM tools were found unavailable.
 - Cannot complete operation because VMware Tools is not running in this virtual machine.
```
**Command : vcd vapp reboot sompa-vapp**
```
Are you sure you want to reboot the vApp or VM(s)? [y/N]: y
vappRebootGuest: Rebooting Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)
vappRebootGuest: Rebooting Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)
task: 85ed6d2b-eb0f-4199-99bf-bc4b7d6a64eb, Reboot Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9), result: success

```
**Command : vcd vapp reboot sompa-vapp vm3**
```
Are you sure you want to reboot the vApp or VM(s)? [y/N]: y
vappRebootGuest: Rebooting Virtual Machine vm3(afe0a16d-2750-43ec-a779-73073d12088c)
task: 3d07779b-4849-4ad7-bfc2-686af445a04f, result: error, message: [ 94940880-d9e0-41b6-80db-7c04a56f7f28 ] Internal Server Error
 - Failed to reboot guest os for the VM "vm3 (afe0a16d-2750-43ec-a779-73073d12088c)" as required VM tools were found unavailable.
 - Cannot complete operation because VMware Tools is not running in this virtual machine.
```

Tests Run : 
`(pyvcloud) malakars-m01:tests malakars$ python -m unittest vcd_vapp_vm.TestVAppVM.test_1004_shutdown_vapp
.
----------------------------------------------------------------------
Ran 1 test in 14.628s

OK
(pyvcloud) malakars-m01:tests malakars$ python -m unittest vcd_vapp_vm.TestVAppVM.test_1005_reboot_vapp
.
----------------------------------------------------------------------
Ran 1 test in 10.343s

OK

`
`(pyvcloud) malakars-m01:tests malakars$ python -m unittest vcd_vm.TestVM.test_1005_reboot_vm
.
----------------------------------------------------------------------
Ran 1 test in 6.778s

OK
(pyvcloud) malakars-m01:tests malakars$ python -m unittest vcd_vm.TestVM.test_1004_shutdown_vm
.
----------------------------------------------------------------------
Ran 1 test in 8.307s

OK
`
- @rocknes @pacogomez @anusuyar @sahithi @hodgesrm @rdbwebster

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/185)

### CODE REVIEW

**Comment by sahithi** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-L3VQFQHMwcBDsmeqfLg:-L3VQFQHMwcBDsmeqfLh:b-m1igav) (no related file):*
> vappRebootGuest: Rebooting Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)
> vappRebootGuest: Rebooting Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)

Why are these msgs getting printed twice and where are these coming from?

---

*[pyvcloud/vcd/vm.py, line 162 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-L3VPGYJ-g6dG_ka27U1:-L3VPGYKLCAupAMieeAQ:b-1xvuce) ([raw file](https://github.com/vmware/pyvcloud/blob/3bcc5da2686fb2b44544b147414c66ba870fee5f/pyvcloud/vcd/vm.py#L162)):*
>  def reboot(self):
>
>  def shutdown(self):

Duplicate methods?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/185)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vm.py, line 162 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-L3VPGYJ-g6dG_ka27U1:-L3VTcRGvmS71F-k7KM7:b-1ornvy) ([raw file](https://github.com/vmware/pyvcloud/blob/3bcc5da2686fb2b44544b147414c66ba870fee5f/pyvcloud/vcd/vm.py#L162)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

>  def reboot(self):
>
>  def shutdown(self):

Duplicate methods?
</blockquote></details>

Removed. The messages were indeed coming from those two methods. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/185)*

**Comment by sompa** [comment]
*[a discussion](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-L3VQFQHMwcBDsmeqfLg:-L3VU7cYwkIl2K8Oh6rx:b6zv11p) (no related file):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> vappRebootGuest: Rebooting Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)
> vappRebootGuest: Rebooting Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)

Why are these msgs getting printed twice and where are these coming from?
</blockquote></details>

Dups indeed. Removed those methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/185)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/vm.py, line 162 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-L3VPGYJ-g6dG_ka27U1:-L3VV5YnmyEyJ2UySv3m:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/3bcc5da2686fb2b44544b147414c66ba870fee5f/pyvcloud/vcd/vm.py#L162)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Removed. The messages were indeed coming from those two methods. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/185)*

**Comment by anusuyar** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 200 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-L3VZyPCzui-FvYjw40C:-L3VZyPCzui-FvYjw40D:bxox4hp) ([raw file](https://github.com/vmware/pyvcloud/blob/e9339c54405d9428233797813f3e8271ef8f3077/pyvcloud/vcd/vapp.py#L200)):*
> ```Python
> 
>     def shutdown(self):
>         """Shuts down a vApp.
> ```

'Shutdown the vApp.' is better. To be consistent with  'Reboots the vApp'

---

*[pyvcloud/vcd/vm.py, line 88 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-L3V_JeD2VTDt9wmPTbS:-L3V_JeD2VTDt9wmPTbT:b-wzn8w7) ([raw file](https://github.com/vmware/pyvcloud/blob/e9339c54405d9428233797813f3e8271ef8f3077/pyvcloud/vcd/vm.py#L88)):*
> ```Python
> 
>     def shutdown(self):
>         """Shuts down a VM.
> ```

'Shutdown the VM'

---

*[tests/vcd_vapp_vm.py, line 141 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-L3V_if9VqC-mZ3E7Dcd:-L3V_ifAmFzSjrYIiVmw:b9eyzml) ([raw file](https://github.com/vmware/pyvcloud/blob/e9339c54405d9428233797813f3e8271ef8f3077/tests/vcd_vapp_vm.py#L141)):*
> ```Python
>         assert task.get('status') == TaskStatus.SUCCESS.value
> 
>     def test_1004_shutdown_vapp(self):
> ```

What is the difference between this method and test_1004_shutdown_vapp?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/185)*

**Comment by sompa** [comment]
*[tests/vcd_vapp_vm.py, line 141 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-L3V_if9VqC-mZ3E7Dcd:-L3WhLgzHWSFr7vHc9qX:bhbcqzr) ([raw file](https://github.com/vmware/pyvcloud/blob/e9339c54405d9428233797813f3e8271ef8f3077/tests/vcd_vapp_vm.py#L141)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

What is the difference between this method and test_1004_shutdown_vapp?
</blockquote></details>

Both methods got added because of a bad merge. I have removed the dups.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/185)*

**Comment by sompa** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 200 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-L3VZyPCzui-FvYjw40C:-L3Wh48Q6ffVmWC3V8JF:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/e9339c54405d9428233797813f3e8271ef8f3077/pyvcloud/vcd/vapp.py#L200)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

'Shutdown the vApp.' is better. To be consistent with  'Reboots the vApp'
</blockquote></details>

Done.

---

*[pyvcloud/vcd/vm.py, line 88 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-L3V_JeD2VTDt9wmPTbS:-L3Wgrni6fXwO0p3CyKn:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/e9339c54405d9428233797813f3e8271ef8f3077/pyvcloud/vcd/vm.py#L88)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

'Shutdown the VM'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/185)*

**Comment by sahithi** [comment]
:lgtm:

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-:-L3ZdbIIbX9vPz1UYMK_:bnfp4nl)*

**Comment by sahithi** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/185)*

**Comment by pacogomez** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-:-L3ZolAmV4Xo_kZTPxCt:bnfp4nl)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/185#-:-L3ZweFV1JhV2-dRz10D:bnfp4nl)*

**Pull request merged**
