### PR TITLE
VCDA-451: work with pending tasks

### PR DESCRIPTION
**Pull request by pacogomez**
- fixes --no-wait flag
- list tasks by status
- wait for task by id
- option to overwrite catalog item when capturing vApp

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/178)

### CODE REVIEW

**Comment by sahithi** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 435 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-L3Ei-BDHUjKnpw1PF0n:-L3Ei-BDHUjKnpw1PF0o:b1i59mk) ([raw file](https://github.com/vmware/pyvcloud/blob/abcdd087114dd32a83b189f9e15088af2147dc02/pyvcloud/vcd/org.py#L435)):*
> ```Python
>                      customize_on_instantiate=False,
>                      overwrite=False):
>         """Capture a vApp as a catalog item template.
> ```

nit: 'Capture vApp' instead of 'Capture a vApp'

---

*[pyvcloud/vcd/org.py, line 445 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-L3EiFgIxgAJ0VKYEjoq:-L3EiFgIxgAJ0VKYEjor:b-3yevy) ([raw file](https://github.com/vmware/pyvcloud/blob/abcdd087114dd32a83b189f9e15088af2147dc02/pyvcloud/vcd/org.py#L445)):*
> ```Python
>             vApp to be instantiated from this vApp template can be customized.
>         :param overwrite: (bool): A flag indicating if the item in the catalog
>             will be overwrite if it already exists. If it doesn't exists, this
> ```

nit: A flag indicating if the item in the catalog 'has to be overwritten'

---

*[pyvcloud/vcd/org.py, line 463 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-L3EigVGrBiKuhD4RQOp:-L3EigVGrBiKuhD4RQOq:bjzki4k) ([raw file](https://github.com/vmware/pyvcloud/blob/abcdd087114dd32a83b189f9e15088af2147dc02/pyvcloud/vcd/org.py#L463)):*
> ```Python
>                 item = self.get_catalog_item(catalog_resource.get('name'),
>                                              catalog_item_name)
>                 contents.append(E.TargetCatalogItem(href=item.get('href'),
> ```

This just simply overwrites all the required variables in the vCD database. Shouldn't we be deleting the actual old physical catalog item? we cannot leave that stranded in vCenter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/178)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/task.py, line 74 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-L3EklI8X7bNP9FniGil:-L3EklI8X7bNP9FniGim:b-qiyhad) ([raw file](https://github.com/vmware/pyvcloud/blob/abcdd087114dd32a83b189f9e15088af2147dc02/pyvcloud/vcd/task.py#L74)):*
> ```Python
> 
>     def list_tasks(self,
>                    filter_statuses=[
> ```

filter_status_list instead of filter_statuses.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/178)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 435 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-L3Ei-BDHUjKnpw1PF0n:-L3F2FdKidbFGPAbA3cZ:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/abcdd087114dd32a83b189f9e15088af2147dc02/pyvcloud/vcd/org.py#L435)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

nit: 'Capture vApp' instead of 'Capture a vApp'
</blockquote></details>

Done.

---

*[pyvcloud/vcd/org.py, line 445 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-L3EiFgIxgAJ0VKYEjoq:-L3F2PvVMc-1lOXH0Neo:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/abcdd087114dd32a83b189f9e15088af2147dc02/pyvcloud/vcd/org.py#L445)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

nit: A flag indicating if the item in the catalog 'has to be overwritten'
</blockquote></details>

Done.

---

*[pyvcloud/vcd/org.py, line 463 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-L3EigVGrBiKuhD4RQOp:-L3F2TzFVomLI8ZXd1nP:b-8rdc5h) ([raw file](https://github.com/vmware/pyvcloud/blob/abcdd087114dd32a83b189f9e15088af2147dc02/pyvcloud/vcd/org.py#L463)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This just simply overwrites all the required variables in the vCD database. Shouldn't we be deleting the actual old physical catalog item? we cannot leave that stranded in vCenter.
</blockquote></details>

no, the API takes care of deleting the old catalog item, we just need to pass this element

---

*[pyvcloud/vcd/task.py, line 74 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-L3EklI8X7bNP9FniGil:-L3F2d0Qs3AzoX_f5Chz:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/abcdd087114dd32a83b189f9e15088af2147dc02/pyvcloud/vcd/task.py#L74)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

filter_status_list instead of filter_statuses.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/178)*

**Comment by pacogomez** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/178)*

**Comment by sahithi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-:-L3FFa35nqgrhFx3NXz-:bnfp4nl)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/task.py, line 77 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-L3FFhZ_VBSj3sjwWt4z:-L3FFhZatps0z3wmZJs4:b-fy29cc) ([raw file](https://github.com/vmware/pyvcloud/blob/927d687250ae43d9e8e5cb5c93f3f9fb14d599b0/pyvcloud/vcd/task.py#L77)):*
> ```Python
>                        TaskStatus.QUEUED.value, TaskStatus.PRE_RUNNING.value,
>                        TaskStatus.RUNNING.value
>                    ],
> ```

Should we be adding TaskStatus.ERROR  to this list ? Some of the tasks accessible to the user might be in error state and the user might want to access those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/178)*

**Comment by sompa** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/178)*

**Comment by pacogomez** [comment]
Reviewed 3 of 9 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[pyvcloud/vcd/task.py, line 77 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-L3FFhZ_VBSj3sjwWt4z:-L3FHUf5wzsKHi7lSWJv:bby2kbl) ([raw file](https://github.com/vmware/pyvcloud/blob/927d687250ae43d9e8e5cb5c93f3f9fb14d599b0/pyvcloud/vcd/task.py#L77)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Should we be adding TaskStatus.ERROR  to this list ? Some of the tasks accessible to the user might be in error state and the user might want to access those.
</blockquote></details>

this is just the default value, users can provide their own list

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/178)*

**Comment by pacogomez** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/178)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/task.py, line 77 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-L3FFhZ_VBSj3sjwWt4z:-L3FW90ao81h9oc5oCdV:b32w0x) ([raw file](https://github.com/vmware/pyvcloud/blob/927d687250ae43d9e8e5cb5c93f3f9fb14d599b0/pyvcloud/vcd/task.py#L77)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

this is just the default value, users can provide their own list
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/178)*

**Comment by sompa** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/178#-:-L3FWD5J_6nw02Ui9t9n:bnfp4nl)*

**Pull request merged**
