### PR TITLE
VCDA-382/3/4/6/7/8

### PR DESCRIPTION
**Pull request by pacogomez**
see commit messages for details

python -m unittest vcd_vm.py -v
test_0001_modify_cpu (vcd_vm.TestVAppVM) ... ok
test_0002_modify_memory (vcd_vm.TestVAppVM) ... ok
test_0003_power_on (vcd_vm.TestVAppVM) ... ok

----------------------------------------------------------------------
Ran 3 tests in 22.416s

OK

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/159)

### CODE REVIEW

**Comment by sahithi** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/vapp.py, line 441 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1KOFvD9pbwHQupwQIY:-L1KOFvE-7ts9gwXUNVa:b-109ou) ([raw file](https://github.com/vmware/pyvcloud/blob/ac235b89a2b9a2d1a69aad8cbd2dedabc286d576/pyvcloud/vcd/vapp.py#L441)):*
> ```Python
>         :param specs: An array of VM specifications, see `to_sourced_item()`
>             method for specification details.
>         :param deploy: (bool): True if the vApp should be deployed at
> ```

For my benefit, adding a vm - is it not same as deploying VM?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/159)*

**Comment by anusuyar** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 356 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1KTGIzAOsCTSn2jiJY:-L1KTGIzAOsCTSn2jiJZ:b3ewa06) ([raw file](https://github.com/vmware/pyvcloud/blob/ac235b89a2b9a2d1a69aad8cbd2dedabc286d576/pyvcloud/vcd/vapp.py#L356)):*
> ```Python
>                 to be used for this VM
> 
>         :return: SourcedItem
> ```

its better to provide type of the returned type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-:-L1KToC4CiTcEc4v8wBm:bnfp4nl)*

**Comment by anusuyar** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/159)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 356 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1KTGIzAOsCTSn2jiJY:-L1LBADw9j7D4OEr145v:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/ac235b89a2b9a2d1a69aad8cbd2dedabc286d576/pyvcloud/vcd/vapp.py#L356)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

its better to provide type of the returned type.
</blockquote></details>

Done.

---

*[pyvcloud/vcd/vapp.py, line 441 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1KOFvD9pbwHQupwQIY:-L1LBBKeSvb9JvlvMihE:byujopf) ([raw file](https://github.com/vmware/pyvcloud/blob/ac235b89a2b9a2d1a69aad8cbd2dedabc286d576/pyvcloud/vcd/vapp.py#L441)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

For my benefit, adding a vm - is it not same as deploying VM?
</blockquote></details>

adding a VM to a vApp and deploying the vApp or the VM are different operations

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/159)*

**Comment by rocknes** [comment]
Reviewed 3 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 412 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1Rv437cWmD5M_DlTKW:-L1Rv437cWmD5M_DlTKX:b-4g8z95) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/pyvcloud/vcd/vapp.py#L412)):*
> ```Python
>                     guest_customization_param.append(
>                         E.AdminPasswordEnabled(False))
>             if 'password_reset' in spec:
> ```

This change introduces a subtle change in the logic. If password_reset param is not provided we won't be adding the \<ResetPasswordRequired\> tag, I am not sure how vcd interprets that. We should check the behavior at vcd side.

---

*[pyvcloud/vcd/vm.py, line 36 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1RwWf0-hbuaSw19PbO:-L1RwWf0-hbuaSw19PbP:b-t0bz6z) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/pyvcloud/vcd/vm.py#L36)):*
> ```Python
>         """
>         self.client = client
>         self.name = name
> ```

I would like to suggest dropping the param and field _name_. We can always get it from resource.
Param _href_ makes sense, if _resource_ (param) is not supplied, we need to use _href_ to make a ReST call to fetch the resource. However name doesn't help us to accomplish something similar.

---

*[pyvcloud/vcd/vm.py, line 70 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1Rz6WPkpHe-2d1MiWy:-L1Rz6WPkpHe-2d1MiWz:b-843kn0) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/pyvcloud/vcd/vm.py#L70)):*
> ```Python
>              '}ElementName'] = '%s virtual CPU(s)' % virtual_quantity
>         item['{' + NSMAP['rasd'] + '}VirtualQuantity'] = virtual_quantity
>         item['{' + NSMAP['vmw'] + '}CoresPerSocket'] = cores_per_socket
> ```

Do you have any idea why vCD has these two fields instead of just one?
I went through https://pubs.vmware.com/vca/index.jsp?topic=%2Fcom.vmware.vcloud.api.doc_56%2FGUID-472B5732-BAFE-4ECD-B77B-BE6287AABF58.html
and looks like they are supposed to always have the same value. In that case should we expose both the params?

---

*[tests/vcd_vm.py, line 32 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1RzysXayxxcpcGt4Ol:-L1RzysXayxxcpcGt4Om:b6m9deh) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/tests/vcd_vm.py#L32)):*
> ```Python
> 
>     def test_0001_modify_cpu(self):
>         logged_in_org = self.client.get_org()
> ```

How is self.client populated? I don't see an __init__ method

---

*[tests/vcd_vm.py, line 34 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1Rzcus-dnBQeaNxfVQ:-L1Rzcus-dnBQeaNxfVR:by31dv7) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/tests/vcd_vm.py#L34)):*
> ```Python
>         logged_in_org = self.client.get_org()
>         org = Org(self.client, resource=logged_in_org)
>         v = org.get_vdc(self.config['vcd']['vdc'])
> ```

We can get the vdc resource directly using  client.get_resource(vdc_href). And vdc_href is stored in the profile.

---

*[tests/vcd_vm.py, line 54 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1S-a-FU0JnzvRpYtPl:-L1S-a-FU0JnzvRpYtPm:b-7c0pg5) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/tests/vcd_vm.py#L54)):*
> ```Python
>                                 TaskStatus.CANCELED],
>                             callback=None)
>         assert task.get('status') == TaskStatus.SUCCESS.value
> ```

Apart from task success assertion, maybe we should verify that the updated resource has indeed the new cpu value

---

*[tests/vcd_vm.py, line 57 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1S-P9TIrc97PBdF_pD:-L1S-P9TIrc97PBdF_pE:bvvcw6v) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/tests/vcd_vm.py#L57)):*
> ```Python
> 
>     def test_0002_modify_memory(self):
>         logged_in_org = self.client.get_org()
> ```

We can get rid of the intermediate org variable as mentioned above

---

*[tests/vcd_vm.py, line 81 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1S-kqQXZZV4_wPHLeY:-L1S-kqQXZZV4_wPHLeZ:bvvcw6v) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/tests/vcd_vm.py#L81)):*
> ```Python
> 
>     def test_0003_power_on(self):
>         logged_in_org = self.client.get_org()
> ```

We can get rid of the intermediate org variable as mentioned above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/159)*

**Comment by pacogomez** [comment]
Review status: 6 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[pyvcloud/vcd/vapp.py, line 412 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1Rv437cWmD5M_DlTKW:-L1SyESabnkLxMCyBnnQ:b-21zp31) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/pyvcloud/vcd/vapp.py#L412)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This change introduces a subtle change in the logic. If password_reset param is not provided we won't be adding the \<ResetPasswordRequired\> tag, I am not sure how vcd interprets that. We should check the behavior at vcd side.
</blockquote></details>

the `< ResetPasswordRequired>` tag is optional, we should add it to the sourced item only if it is present in the `spec`, so we don't assume any default behavior.

---

*[pyvcloud/vcd/vm.py, line 36 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1RwWf0-hbuaSw19PbO:-L1SzHT1BT4kJsZ3g2zi:b-uj6ioe) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/pyvcloud/vcd/vm.py#L36)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I would like to suggest dropping the param and field _name_. We can always get it from resource.
Param _href_ makes sense, if _resource_ (param) is not supplied, we need to use _href_ to make a ReST call to fetch the resource. However name doesn't help us to accomplish something similar.
</blockquote></details>

removed, `name` is not necessary, we should also review `name` in the `VApp` class

---

*[pyvcloud/vcd/vm.py, line 70 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1Rz6WPkpHe-2d1MiWy:-L1Szd3dCrmM9VPa_xGJ:bmponh9) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/pyvcloud/vcd/vm.py#L70)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Do you have any idea why vCD has these two fields instead of just one?
I went through https://pubs.vmware.com/vca/index.jsp?topic=%2Fcom.vmware.vcloud.api.doc_56%2FGUID-472B5732-BAFE-4ECD-B77B-BE6287AABF58.html
and looks like they are supposed to always have the same value. In that case should we expose both the params?
</blockquote></details>

We should expose the two params from the REST API, if cores_per_socket is None it will default to virtual_quantity.

---

*[tests/vcd_vm.py, line 32 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1RzysXayxxcpcGt4Ol:-L1T0-GrocIMJFcSFFAd:b-nmvbt5) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/tests/vcd_vm.py#L32)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

How is self.client populated? I don't see an __init__ method
</blockquote></details>

See parent class `TestCase` in file `pyvcloud/vcd/test.py`, this is how all unit tests are designed in pyvcloud

---

*[tests/vcd_vm.py, line 54 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1S-a-FU0JnzvRpYtPl:-L1T4ezKEFwfGbi9jBQw:bshslhb) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/tests/vcd_vm.py#L54)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Apart from task success assertion, maybe we should verify that the updated resource has indeed the new cpu value
</blockquote></details>

added additional checks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/159)*

**Comment by rocknes** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/vcd_vm.py, line 32 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-L1RzysXayxxcpcGt4Ol:-L1Tx8jp5cIs-7QdIr68:b5q5xq1) ([raw file](https://github.com/vmware/pyvcloud/blob/9841e61acdbd315625d315c3d247ff304b64851c/tests/vcd_vm.py#L32)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

See parent class `TestCase` in file `pyvcloud/vcd/test.py`, this is how all unit tests are designed in pyvcloud
</blockquote></details>

Sorry about that, realized it after posting the comment :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/159#-:-L1TxOQW41cDW1-lULFw:bnfp4nl)*

**Pull request merged**
