### PR TITLE
Compose & clone vApp

### PR DESCRIPTION
**Pull request by rvdh**
This Pull Request adds the ability to recompose vApps, to add or remove virtual machines to or from vApps (resolves issue #21 for @akulkarni-rvbd, @xcompass, @sanderv32). It also adds the ability to clone vApps to a new vApp in the same or a different VDC.

Also, the network settings passed to create_vapp (issue #40) will now have effect.

### CODE REVIEW

**Comment by zcui99** [comment]
Can someone merge this PR

**Comment by pacogomez** [comment]
Thanks, this has multiple changes. I'll review and merge it

**Comment by rvdh** [comment]
@pacogomez Any idea when you'll be able to review?

**Comment by pasikarkkainen** [comment]
Any plans to add support for being able to copy vapps to catalog ?

**Comment by rvdh** [comment]
@pacogomez Any idea when you will review? Will it help to close this PR and break everything up into smaller PRs?

**Comment by montj2** [comment]
@rvdh Thank you! This really saves me a ton of time. I was fumbling/struggling around with the Network portion as I need to pass IPAddress and ExternalIPAddress. Your commit will make it easy to add these parameters in the compose_vapp method.

**Comment by pacogomez** [comment]
@rvdh I'll try to review it and merge this week

**Comment by pacogomez** [comment]
looks good, thanks!

**Pull request merged**
