### PR TITLE
[VCDA-585] Add system tests for vApp

### PR DESCRIPTION
**Pull request by rocknes**
1. Moved vApp tests from the old test files to the new framework
2. Added some new tests to test vApp operation which were untested as of now.
3. Enhanced environment.py to add an orgvdc network to the testing environment

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/236)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBR7VMj99iHo669zsSC:-LBR7VMj99iHo669zsSD:bdqsqhe) (no related file):*
Please drop the sample run results from the git commit message.  The commit message should be a succinct description of what changed and why.  This keeps the log relatively clean and easy to read. 

---

*[a discussion](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBR8iKY50NuhSCz7KXX:-LBR8iKY50NuhSCz7KXY:b5md09) (no related file):*
As part of this commit can you clean up base_test.py messages like the following?  They make the log very difficult to read: 

/home/USER/git/USER-pyvcloud/pyvcloud/system_test_framework/base_test.py:30: ResourceWarning: unclosed <ssl.SSLSocket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.16.78.235', 33940), raddr=('10.150.200.92', 443)>

(I don't see them in your output but they show up when I run idisk_tests.py.)

---

*[a discussion](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBRMHz10DYS6YZg2HMg:-LBRMHz10DYS6YZg2HMh:bj08x5n) (no related file):*
If there are intermittent errors in the tests can you put in a retry loop to try to get by them?  It will be difficult to incorporate unstable tests in the builds. 

---

*[system_tests/vapp_tests.py, line 14 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBRLElg84sq9Lse1Vwa:-LBRLElg84sq9Lse1Vwb:b-ezn2c2) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L14)):*
> ```Python
> 
> 
> class TestVApp(BaseTestCase):
> ```

How does this test relate to existing unit tests in tests?  The commit should retire obsolete test cases from vapp.py and vapp_vm.py, etc.  

---

*[system_tests/vapp_tests.py, line 201 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBRAocb4ZklCbSSweQc:-LBRAocb4ZklCbSSweQd:biohsyn) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L201)):*
> ```Python
>         vapp_resource = vapp.get_resource()
> 
>         # TODO : Bug in vdc.vapp_instantiate() doesn't take description
> ```

Please log this as an issue in Github so the problem is publicly visible. 

---

*[system_tests/vapp_tests.py, line 242 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBRBGZs3wxW2vo3nA0p:-LBRBGZs3wxW2vo3nA0q:b81r09a) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L242)):*
> ```Python
> 
>     def _power_on_vapp_if_possible(self, client, vapp):
>         # TODO : update power_on to handle missing link exception
> ```

Can also be converted to public issue.

---

*[system_tests/vapp_tests.py, line 265 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBRBhRA2bSrZb7BLg2p:-LBRBhRA2bSrZb7BLg2q:b-7jeit4) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L265)):*
> ```Python
> 
>         print('Undeploying vApp ' + vapp_name)
>         vapp.reload()
> ```

Off-topic but relevant here: This code shows how painful the X.reload() protocol is.  We should fix this in future if possible, as it's an open invitation to bugs.  I can think of a couple of ways that vapp.py could check for links, which is the underlying issue. Obviously not a fix for this checkin. :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/236)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBRMHz10DYS6YZg2HMg:-LBTKRJH1O46i21qZSED:b-59cppo) (no related file):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

If there are intermittent errors in the tests can you put in a retry loop to try to get by them?  It will be difficult to incorporate unstable tests in the builds. 
</blockquote></details>

I believe the issue at hand is related to my testbed rather than the test itself. The failure occurs due to inability of vCD to install the agent on the host. I don't see any generic way for us to detect or stop a test from running for infra issues like this.

---

*[a discussion](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBR8iKY50NuhSCz7KXX:-LBTL9AmAov19thBSvyU:b-if0kfn) (no related file):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

As part of this commit can you clean up base_test.py messages like the following?  They make the log very difficult to read: 

/home/USER/git/USER-pyvcloud/pyvcloud/system_test_framework/base_test.py:30: ResourceWarning: unclosed <ssl.SSLSocket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.16.78.235', 33940), raddr=('10.150.200.92', 443)>

(I don't see them in your output but they show up when I run idisk_tests.py.)

</blockquote></details>

Such warning crop up for this test suite too, I manually removed them before posting. We have a jira task tracking this issue, will look into it once I start the other Jira task.

---

*[a discussion](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBR7VMj99iHo669zsSC:-LBTLLqWEszmI_GLXECT:bnb03gy) (no related file):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Please drop the sample run results from the git commit message.  The commit message should be a succinct description of what changed and why.  This keeps the log relatively clean and easy to read. 
</blockquote></details>

Will do that while merging the PR, reviewable isn't letting me to edit the description :(

---

*[system_tests/vapp_tests.py, line 14 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBRLElg84sq9Lse1Vwa:-LBTLTek9Dx3uqk993tK:b1rmnl0) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L14)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

How does this test relate to existing unit tests in tests?  The commit should retire obsolete test cases from vapp.py and vapp_vm.py, etc.  
</blockquote></details>

These tests cover all the tests in the old unit tests related to vApps. Vm unit tests haven't been ported in this suite. Apart from the old tests I added more tests that made logical sense and covers the gaps in the old coverage.
Yes, I have retired (marked with @unittest.skip()) the obsolete tests in the unit test files and haven't ported them in the new framework.

---

*[system_tests/vapp_tests.py, line 201 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBRAocb4ZklCbSSweQc:-LBTM-ky8qUDwRdh5KAM:b-peol1o) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L201)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Please log this as an issue in Github so the problem is publicly visible. 
</blockquote></details>

Sure will do that

---

*[system_tests/vapp_tests.py, line 242 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBRBGZs3wxW2vo3nA0p:-LBTM99ABi_6Jg8M2X2c:bsltkkl) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L242)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Can also be converted to public issue.
</blockquote></details>

It's already being tracked by Jira task VCDA-603

---

*[system_tests/vapp_tests.py, line 265 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBRBhRA2bSrZb7BLg2p:-LBTMH-IDOkxy0iNYFPS:bslg8ml) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L265)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Off-topic but relevant here: This code shows how painful the X.reload() protocol is.  We should fix this in future if possible, as it's an open invitation to bugs.  I can think of a couple of ways that vapp.py could check for links, which is the underlying issue. Obviously not a fix for this checkin. :)
</blockquote></details>

I agree. I had proposed in past to update the internal resource of objects on put/post operations, since these operations are guaranteed to change the server side resource. We  should revisit the topic in next sprint.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/236)*

**Comment by sahithi** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBRMHz10DYS6YZg2HMg:-LBafm6K1eTkPYgbwWsc:b4fehwe) (no related file):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I believe the issue at hand is related to my testbed rather than the test itself. The failure occurs due to inability of vCD to install the agent on the host. I don't see any generic way for us to detect or stop a test from running for infra issues like this.
</blockquote></details>

Aritra, I have not reviewed this change-set at the logic level for each test. Try to get others who worked on vApp/VMs to review the logic and the coverage. 

---

*[pyvcloud/system_test_framework/environment.py, line 393 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBaaiQx8JU-bErXr-7U:-LBaaiQx8JU-bErXr-7V:b-h750vp) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/pyvcloud/system_test_framework/environment.py#L393)):*
> ```Python
>                 return
> 
>         print('Creating org-vdc network ' + net_name)
> ```

I think we should get to 'Logger' before print statements explode :) please prioritize that task.

---

*[system_tests/vapp_tests.py, line 17 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBabQifDiYXeTfroTOi:-LBabQifDiYXeTfroTOj:bu18duk) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L17)):*
> ```Python
>     """Test vApp functionalities implemented in pyvcloud."""
>     # TODO - Once the share catalog bug is fixed, the runner should be
>     # changed to vApp Author
> ```

Add the umbrella Jira task for any who wants to refer to the actual problem description here

---

*[system_tests/vapp_tests.py, line 50 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBad8LQ4Nbx-n0U1085:-LBad8LQ4Nbx-n0U1086:b-1hlysb) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L50)):*
> ```Python
>            vApps exist, re-use them.
> 
>            This test passes if the two vApp hrefs are not None.
> ```

I like this way of mentioning Pass criteria in the doc string. We should highlight this standard in the documentation for other contributors.

---

*[system_tests/vapp_tests.py, line 63 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBacent-YJefZ63vgm6:-LBacent-YJefZ63vgm7:bj9b0wr) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L63)):*
> ```Python
>                 vapp_resource.Owner.User.get('name')
>         except Exception as e:
>             if 'not found' in str(e):
> ```

Check if Exception is of type EntityNotFoundException instead of checking for "not found" string.

---

*[system_tests/vapp_tests.py, line 80 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBacqyW3gdD6bL_MefI:-LBacqyW3gdD6bL_MefJ:b-ujbwh) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L80)):*
> ```Python
>                 vapp_resource.Owner.User.get('name')
>         except Exception as e:
>             if 'not found' in str(e):
> ```

Use EntityNotFoundException

---

*[system_tests/vapp_tests.py, line 94 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBadblI7Kgf_OVHlwnP:-LBadblI7Kgf_OVHlwnQ:b2nghhf) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L94)):*
> ```Python
>         self.assertIsNotNone(TestVApp._customized_vapp_href)
> 
>     def _create_empty_vapp(self, client, vdc):
> ```

Docstring indicating this is a helper method. Not necessary but good to have.

---

*[system_tests/vapp_tests.py, line 172 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBadqGM0b7ZyMTpzTte:-LBadqGM0b7ZyMTpzTtf:b9soypm) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L172)):*
> ```Python
>             'source_vm_name': source_vm_name,
>             'target_vm_name': target_vm_name}
>         # TODO - implement vApp networking
> ```

Jira task# or Git hub Issue# - must for every mention of TODO. Please do the same for all TODOs in the change-set.

---

*[system_tests/vapp_tests.py, line 494 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBafLuE5r-IugPs6MEg:-LBafLuE5r-IugPs6MEh:b-434w5k) ([raw file](https://github.com/vmware/pyvcloud/blob/6dffc44431e590a7ab64c22c769783c167aa8c06/system_tests/vapp_tests.py#L494)):*
> ```Python
>                                  TaskStatus.SUCCESS.value)
>         finally:
>             TestVApp._client.logout()
> ```

Client has to logout regardless of developerModeAware turned on or off.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/236)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/236#-:-LBblHBW5K3WETCVoeZL:bnfp4nl)*

**Comment by rocknes** [comment]
Review status: 4 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[pyvcloud/system_test_framework/environment.py, line 393 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBaaiQx8JU-bErXr-7U:-LBe6r4e03HH2HcgT-7-:b-7m0tnr) ([raw file](https://github.com/vmware/pyvcloud/blob/9ddd2ef7888d6e4487fc86493b8882a8c6aaa1bd/pyvcloud/system_test_framework/environment.py#L393)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I think we should get to 'Logger' before print statements explode :) please prioritize that task.
</blockquote></details>

Sure, will work on it once I finish the stories in the current sprint.

---

*[system_tests/vapp_tests.py, line 17 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBabQifDiYXeTfroTOi:-LBe9cmCEW36O9foRIGN:b-xlonxq) ([raw file](https://github.com/vmware/pyvcloud/blob/9ddd2ef7888d6e4487fc86493b8882a8c6aaa1bd/system_tests/vapp_tests.py#L17)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Add the umbrella Jira task for any who wants to refer to the actual problem description here
</blockquote></details>

Added jira task

---

*[system_tests/vapp_tests.py, line 63 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBacent-YJefZ63vgm6:-LBeAP-y1bHR56gJFyGu:bb6un1j) ([raw file](https://github.com/vmware/pyvcloud/blob/9ddd2ef7888d6e4487fc86493b8882a8c6aaa1bd/system_tests/vapp_tests.py#L63)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Check if Exception is of type EntityNotFoundException instead of checking for "not found" string.
</blockquote></details>

Done

---

*[system_tests/vapp_tests.py, line 80 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBacqyW3gdD6bL_MefI:-LBeAxqcA18Vm_oF-XQc:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/9ddd2ef7888d6e4487fc86493b8882a8c6aaa1bd/system_tests/vapp_tests.py#L80)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Use EntityNotFoundException
</blockquote></details>

Done.

---

*[system_tests/vapp_tests.py, line 94 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBadblI7Kgf_OVHlwnP:-LBeB09Z-OY2BdvhRuFD:bq15kgr) ([raw file](https://github.com/vmware/pyvcloud/blob/9ddd2ef7888d6e4487fc86493b8882a8c6aaa1bd/system_tests/vapp_tests.py#L94)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Docstring indicating this is a helper method. Not necessary but good to have.
</blockquote></details>

Added docstring for helper methods.

---

*[system_tests/vapp_tests.py, line 172 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBadqGM0b7ZyMTpzTte:-LBeB4RX3AfGBUesQmeS:b-dhpplm) ([raw file](https://github.com/vmware/pyvcloud/blob/9ddd2ef7888d6e4487fc86493b8882a8c6aaa1bd/system_tests/vapp_tests.py#L172)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Jira task# or Git hub Issue# - must for every mention of TODO. Please do the same for all TODOs in the change-set.
</blockquote></details>

vApp network implementation is not on the cards as of now, so removing the ToDo comment.

---

*[system_tests/vapp_tests.py, line 467 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBeCtUo1_a99-aao6Hj:-LBeCtUo1_a99-aao6Hk:b-rnmqr8) ([raw file](https://github.com/vmware/pyvcloud/blob/9ddd2ef7888d6e4487fc86493b8882a8c6aaa1bd/system_tests/vapp_tests.py#L467)):*
> ```Python
>         """
>         """
>         # TODO - Unclear about the use of this feature, not enough
> ```

@sahithi - Let's discuss about this ToDo and it's Jira task tomorrow.

---

*[system_tests/vapp_tests.py, line 494 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBafLuE5r-IugPs6MEg:-LBeCR094HFtJ8JP0GdF:b-76vozs) ([raw file](https://github.com/vmware/pyvcloud/blob/9ddd2ef7888d6e4487fc86493b8882a8c6aaa1bd/system_tests/vapp_tests.py#L494)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Client has to logout regardless of developerModeAware turned on or off.
</blockquote></details>

Separated teardown and client logout into two separate tests.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/236)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[system_tests/vapp_tests.py, line 172 at r1](https://reviewable.io/reviews/vmware/pyvcloud/236#-LBadqGM0b7ZyMTpzTte:-LBgLftu2t2Z7PVI4WMJ:bb7m07t) ([raw file](https://github.com/vmware/pyvcloud/blob/9ddd2ef7888d6e4487fc86493b8882a8c6aaa1bd/system_tests/vapp_tests.py#L172)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

vApp network implementation is not on the cards as of now, so removing the ToDo comment.
</blockquote></details>

okay

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/236#-:-LBgMImkAS5OQpYtPN75:bnfp4nl)*

**Pull request merged**
