### PR TITLE
[VCDA-605] add optional root_folder parameter to attach VC

### PR DESCRIPTION
**Pull request by ckolovson**
- add optional root_folder parameter to attach VC

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/233)

### CODE REVIEW

**Comment by hodgesrm** [comment]
:lgtm:

Also a related question: where is E_VMEXT documented?  I'm unable to find references to this in the vCD API docs.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/233#-:-LAQbRnmAHC6yK0YxcDB:blz0lsh)*

**Comment by ckolovson** [comment]
It’s in client.py:
E_VMEXT = objectify.ElementMaker(
    annotate=False,
    namespace=NSMAP['vmext'],
    nsmap={
        None: NSMAP['vcloud'],
        'vmext': NSMAP['vmext']
    })

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/233#-:-LAQdGYb0geWx1quDfDM:bv6j6hs)*

**Comment by rocknes** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pyvcloud/vcd/platform.py, line 233 at r1](https://reviewable.io/reviews/vmware/pyvcloud/233#-LAzdS-D3cLpk79mqwt8:-LAzdS-D3cLpk79mqwt9:b6c32an) ([raw file](https://github.com/vmware/pyvcloud/blob/43a421e2dc2c5ff49c7d090045c4af3466ae33fc/pyvcloud/vcd/platform.py#L233)):*
> ```Python
>         :param: vc_server_name: (str): vc_server_name (VC name).
>         :param: vc_server_host: (str): FQDN or IP address of VC host.
>         :param: vc_admin_user: (str): vc_admin user.
> ```

We should remove the underscores from the description of vc_server_name, vc_admin and vc_admin_pwd. And use consistent casing for 'vc'.

---

*[pyvcloud/vcd/platform.py, line 251 at r1](https://reviewable.io/reviews/vmware/pyvcloud/233#-LAzdl9Q6WBD-JIu31EM:-LAzdl9Q6WBD-JIu31EN:b-fogl0k) ([raw file](https://github.com/vmware/pyvcloud/blob/43a421e2dc2c5ff49c7d090045c4af3466ae33fc/pyvcloud/vcd/platform.py#L251)):*
> ```Python
>             vc_server.append(E_VMEXT.IsEnabled(is_enabled))
>         if vc_root_folder is not None:
>             vc_server.append(E_VMEXT.rootFolder(vc_root_folder))
> ```

Is the xml element named rootFolder or RootFolder? Not that it matters to vCD but I think as per the standard naming convention, the first character of XML element names should be in upper case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/233)*

**Comment by ckolovson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/platform.py, line 251 at r1](https://reviewable.io/reviews/vmware/pyvcloud/233#-LAzdl9Q6WBD-JIu31EM:-LAzfYn84zOrecCuu_Yi:bhyx9ym) ([raw file](https://github.com/vmware/pyvcloud/blob/43a421e2dc2c5ff49c7d090045c4af3466ae33fc/pyvcloud/vcd/platform.py#L251)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Is the xml element named rootFolder or RootFolder? Not that it matters to vCD but I think as per the standard naming convention, the first character of XML element names should be in upper case.
</blockquote></details>

It is rootFolder. I assume I should use the same first letter case in the code in this case, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/233)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/platform.py, line 251 at r1](https://reviewable.io/reviews/vmware/pyvcloud/233#-LAzdl9Q6WBD-JIu31EM:-LAzhARJ0p357T2dwS8A:b-qtalfp) ([raw file](https://github.com/vmware/pyvcloud/blob/43a421e2dc2c5ff49c7d090045c4af3466ae33fc/pyvcloud/vcd/platform.py#L251)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

It is rootFolder. I assume I should use the same first letter case in the code in this case, right?
</blockquote></details>

Yup, in that case it's fine :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/233)*

**Comment by ckolovson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/platform.py, line 233 at r1](https://reviewable.io/reviews/vmware/pyvcloud/233#-LAzdS-D3cLpk79mqwt8:-LB1tRi5DnhNEhZcI3IU:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/43a421e2dc2c5ff49c7d090045c4af3466ae33fc/pyvcloud/vcd/platform.py#L233)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We should remove the underscores from the description of vc_server_name, vc_admin and vc_admin_pwd. And use consistent casing for 'vc'.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/233)*

**Comment by rocknes** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/233#-:-LB3Puxz6cfjDjoG1r1w:bnfp4nl)*

**Comment by rocknes** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/233)*

**Pull request merged**
