### PR TITLE
[VDP-1661, VCDA-619] Added register, list, and unregister NSX-T Managers

### PR DESCRIPTION
**Pull request by ckolovson**
- [VDP-1661, VCDA-619] Added register, list, and unregister NSX-T Managers

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pyvcloud/vcd/platform.py, line 127 at r1](https://reviewable.io/reviews/vmware/pyvcloud/244#-LCaZXrK3S1Exi4O1YOK:-LCaZXrK3S1Exi4O1YOL:b-ojuyub) ([raw file](https://github.com/vmware/pyvcloud/blob/8294022724f319592cb1c51858b92c63de39570b/pyvcloud/vcd/platform.py#L127)):*
> ```Python
>                                       vxlan_network_pool_name)
> 
>     def get_ID_by_name(self, resource_type, resource_name):
> ```

Is this a previously existing API call?  If so it needs to follow versioning rules to avoid breaking clients. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by ckolovson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/platform.py, line 127 at r1](https://reviewable.io/reviews/vmware/pyvcloud/244#-LCaZXrK3S1Exi4O1YOK:-LCadQeq5SvUA8UN_g8Y:b-vfk8tr) ([raw file](https://github.com/vmware/pyvcloud/blob/8294022724f319592cb1c51858b92c63de39570b/pyvcloud/vcd/platform.py#L127)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Is this a previously existing API call?  If so it needs to follow versioning rules to avoid breaking clients. 
</blockquote></details>

Yes but added only recently. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by ckolovson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/platform.py, line 127 at r1](https://reviewable.io/reviews/vmware/pyvcloud/244#-LCaZXrK3S1Exi4O1YOK:-LCcmT5-0CdvgLgydej2:b9mxu7l) ([raw file](https://github.com/vmware/pyvcloud/blob/8294022724f319592cb1c51858b92c63de39570b/pyvcloud/vcd/platform.py#L127)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

Yes but added only recently. 
</blockquote></details>

This was also changed to avoid confusion w/ client.get_resource(), which returns a linked resource. The original name of this function was a misnomer -- it returns an object ID, not a "resource" (with links). I am 99.999% sure that no other client(s) are calling it, as it was only just added. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by ckolovson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/platform.py, line 127 at r1](https://reviewable.io/reviews/vmware/pyvcloud/244#-LCaZXrK3S1Exi4O1YOK:-LCe2ihY1r_TIplkioc8:b-ewms0e) ([raw file](https://github.com/vmware/pyvcloud/blob/8294022724f319592cb1c51858b92c63de39570b/pyvcloud/vcd/platform.py#L127)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

This was also changed to avoid confusion w/ client.get_resource(), which returns a linked resource. The original name of this function was a misnomer -- it returns an object ID, not a "resource" (with links). I am 99.999% sure that no other client(s) are calling it, as it was only just added. 
</blockquote></details>

DONE (backed out these changes). 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by ckolovson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/platform.py, line 127 at r1](https://reviewable.io/reviews/vmware/pyvcloud/244#-LCaZXrK3S1Exi4O1YOK:-LCe2zAX1cDOkH_eGIii:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/8294022724f319592cb1c51858b92c63de39570b/pyvcloud/vcd/platform.py#L127)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

DONE (backed out these changes). 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by hodgesrm** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[system_tests/nsxt_tests.py, line 24 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFLDPFCBmeNDME7j0u:-LEFLDPGCCcKNVn5TI2G:bn9l0qp) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/system_tests/nsxt_tests.py#L24)):*
> ```Python
> from pyvcloud.vcd.utils import to_dict
> ```

Please add single-sentence docstrings to summarize what cases prove.  Example:
def test_010_register_nsxt(self):
    """Client can register a new NSX-T manager if none exists with same name."

These strings print when you run python -m unittest <name of test> -v, making the test assertions easy to follow.

---

*[system_tests/nsxt_tests.py, line 45 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFM_NlBeL2jz1_dl9d:-LEFM_NlBeL2jz1_dl9e:b648yei) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/system_tests/nsxt_tests.py#L45)):*
> ```Python
> 
>         platform.unregister_nsxt_manager(
>             nsxt_manager_name=Environment._config['nsxt']['manager_name'])
> ```

This should test to ensure the manager is gone.  (I.e. no manager of that name exists.)

---

*[system_tests/nsxt_tests.py, line 47 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFLzqm2JKx7dOcMfXv:-LEFLzqm2JKx7dOcMfXw:b-mghi7c) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/system_tests/nsxt_tests.py#L47)):*
> ```Python
>             nsxt_manager_name=Environment._config['nsxt']['manager_name'])
> 
>     def test_020_list_nsxt_managers(self):
> ```

Do you expect to find at least one manager?  If so, there should be something like 'self.assertTrue(len(list(query)) > 0) to check. 

Also can you reorder so that the methods match the run order.

---

*[tests/vcd_nsxt.py, line 23 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFMsAN9xfEXivxDE74:-LEFMsAN9xfEXivxDE75:b6bxk0v) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/tests/vcd_nsxt.py#L23)):*
> ```Python
> 
> 
> class TestNSXT(TestCase):
> ```

This should inherit from BaseTest--shouldn't it be a system test?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by ckolovson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[system_tests/nsxt_tests.py, line 24 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFLDPFCBmeNDME7j0u:-LEGael11IVw7TJfhTCn:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/system_tests/nsxt_tests.py#L24)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Please add single-sentence docstrings to summarize what cases prove.  Example:
def test_010_register_nsxt(self):
    """Client can register a new NSX-T manager if none exists with same name."

These strings print when you run python -m unittest <name of test> -v, making the test assertions easy to follow.
</blockquote></details>

Done.

---

*[system_tests/nsxt_tests.py, line 45 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFM_NlBeL2jz1_dl9d:-LEGnUZK6KP8oHxq9IGU:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/system_tests/nsxt_tests.py#L45)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

This should test to ensure the manager is gone.  (I.e. no manager of that name exists.)
</blockquote></details>

Done.

---

*[system_tests/nsxt_tests.py, line 47 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFLzqm2JKx7dOcMfXv:-LEGnZOwEoQx98zEYJQq:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/system_tests/nsxt_tests.py#L47)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Do you expect to find at least one manager?  If so, there should be something like 'self.assertTrue(len(list(query)) > 0) to check. 

Also can you reorder so that the methods match the run order.
</blockquote></details>

Done.

---

*[tests/vcd_nsxt.py, line 23 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFMsAN9xfEXivxDE74:-LEG_lWEDfNw0B-bk7Sz:berw8u1) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/tests/vcd_nsxt.py#L23)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

This should inherit from BaseTest--shouldn't it be a system test?
</blockquote></details>

I deleted this file as it has been replaced by system_tests/nsxt_tests.py

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/platform.py, line 304 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIZ8sIDn8PogVE_iF6:-LEIZ8sK-BEKWS644vFL:b-i3wcas) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/pyvcloud/vcd/platform.py#L304)):*
> ```Python
>                               nsxt_manager_password=None,
>                               nsxt_manager_description=None):
>         """Register an NSX-T Manager.
> ```

Do we need to spell manager with capital M?

---

*[pyvcloud/vcd/platform.py, line 311 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIZF5a8I90ly6V1I71:-LEIZF5a8I90ly6V1I72:bw5qf8d) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/pyvcloud/vcd/platform.py#L311)):*
> ```Python
>         :param: nsxt_manager_password: (str): password of NSX-T Manager admin.
>         :param: nsxt_manager_description: (str): description of NSX-T Manager.
>         :return: A :class:lxml.objectify.StringElement object describing the
> ```

A blank line between param list and return will be appreciated.

---

*[pyvcloud/vcd/platform.py, line 318 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIoHrb6T_RFE773m6H:-LEIoHrb6T_RFE773m6I:b-bqub7c) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/pyvcloud/vcd/platform.py#L318)):*
> ```Python
>             nsxt_manager.append(E.Description(nsxt_manager_description))
>         nsxt_manager.append(E_VMEXT.Username(nsxt_manager_username))
>         if (nsxt_manager_password is not None):
> ```

Is there a point to not send the password?
In other words is password truly an optional field?

---

*[pyvcloud/vcd/platform.py, line 332 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIodihDHJP_gLaV8Dm:-LEIodihDHJP_gLaV8Dn:bdxlvhf) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/pyvcloud/vcd/platform.py#L332)):*
> ```Python
>         """Un-register an NSX-T Manager.
> 
>         :param: nsxt_manager_name: (str): name of the NSX-T Manager.
> ```

What is the return type?

---

*[system_tests/base_config.yaml, line 73 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIoroE2NXFQQJY2YYr:-LEIoroF4I3hD8z3B4h4:b-efwtiv) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/system_tests/base_config.yaml#L73)):*
> ```YAML
>   nsx_admin_username: 'admin'
>   nsx_admin_password: '<nsx root password>'
>   
> ```

stray spaces

---

*[system_tests/nsxt_tests.py, line 56 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIpQ6x2uZg3YsDUMIm:-LEIpQ6yAWRjBYWii3XC:b2milbi) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/system_tests/nsxt_tests.py#L56)):*
> ```Python
>                     record,
>                     exclude=['href']))
>         print(result)
> ```

We generally don't print results in tests. Rather we should assert that the manager we are expecting is in the result.

e.g. self.AssertIn(manager_name, list_of_managers_retrieved)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by ckolovson** [comment]
Review status: 2 of 4 files reviewed at latest revision, 10 unresolved discussions.

---

*[pyvcloud/vcd/platform.py, line 304 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIZ8sIDn8PogVE_iF6:-LELcOyB4SdpOizVSYi8:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/pyvcloud/vcd/platform.py#L304)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Do we need to spell manager with capital M?
</blockquote></details>

Done.

---

*[pyvcloud/vcd/platform.py, line 311 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIZF5a8I90ly6V1I71:-LELcVq27qt4CvSmGrSH:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/pyvcloud/vcd/platform.py#L311)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

A blank line between param list and return will be appreciated.
</blockquote></details>

Done.

---

*[pyvcloud/vcd/platform.py, line 318 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIoHrb6T_RFE773m6H:-LELcj7C6xeBOUCF4Aqi:b-x6zjz8) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/pyvcloud/vcd/platform.py#L318)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Is there a point to not send the password?
In other words is password truly an optional field?
</blockquote></details>

It is optional according to the VCD API documentation, but I agree it doesn't make sense to treat it as optional in pyvcloud/vcd-cli. So I have changed it to mandatory. 

---

*[pyvcloud/vcd/platform.py, line 332 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIodihDHJP_gLaV8Dm:-LELkQttBw_6S_B7mYq3:b-q3i2e9) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/pyvcloud/vcd/platform.py#L332)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

What is the return type?
</blockquote></details>

class:NoneType None

---

*[system_tests/base_config.yaml, line 73 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIoroE2NXFQQJY2YYr:-LELl7XX7Tb-hKORDHeu:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/system_tests/base_config.yaml#L73)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

stray spaces
</blockquote></details>

Done.

---

*[system_tests/nsxt_tests.py, line 56 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIpQ6x2uZg3YsDUMIm:-LEM3zcY42rTkR8Micnl:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/system_tests/nsxt_tests.py#L56)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We generally don't print results in tests. Rather we should assert that the manager we are expecting is in the result.

e.g. self.AssertIn(manager_name, list_of_managers_retrieved)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by rocknes** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[pyvcloud/vcd/platform.py, line 51 at r4](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEO0umU6Xh9ZsF95NxC:-LEO0umU6Xh9ZsF95NxD:bvgz33x) ([raw file](https://github.com/vmware/pyvcloud/blob/c7d44c142fb35077c99d5a3b4956f63ac3b37c07/pyvcloud/vcd/platform.py#L51)):*
> ```Python
> 
>         :return: :class:`lxml.objectify.ObjectifiedElement` : list of vCenter
>         :   references.
> ```

This colon is stray.

---

*[pyvcloud/vcd/platform.py, line 92 at r4](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEO0q3Y20cb-x6Emz_v:-LEO0q3ZDSd9qEFKACNn:bvgz33x) ([raw file](https://github.com/vmware/pyvcloud/blob/c7d44c142fb35077c99d5a3b4956f63ac3b37c07/pyvcloud/vcd/platform.py#L92)):*
> ```Python
> 
>         :return: A :class:`lxml.objectify.ObjectifiedElement` object
>         :   representing the reference to external network.
> ```

This colon is stray.

---

*[pyvcloud/vcd/platform.py, line 198 at r4](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEO1Xys2-LBktoMKks0:-LEO1XytC5JSxkUgHjyw:b-co93dq) ([raw file](https://github.com/vmware/pyvcloud/blob/c7d44c142fb35077c99d5a3b4956f63ac3b37c07/pyvcloud/vcd/platform.py#L198)):*
> ```Python
>         :param: nsxt_manager_name: (str): name of nsx-t manager.
>         :return: A :class:`lxml.objectify.ObjectifiedElement` object describing
>         :        the new provider VDC.
> ```

The colon at the start of the line is stray.

---

*[pyvcloud/vcd/platform.py, line 272 at r4](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEO1S-77nb0e-YiTEnK:-LEO1S-77nb0e-YiTEnL:bvgz33x) ([raw file](https://github.com/vmware/pyvcloud/blob/c7d44c142fb35077c99d5a3b4956f63ac3b37c07/pyvcloud/vcd/platform.py#L272)):*
> ```Python
>         :param: nsx_admin_pwd: (str): NSX admin password.
>         :return: A :class:`lxml.objectify.ObjectifiedElement` object describing
>         :        the newly registered (attached) VimServer.
> ```

This colon is stray.

---

*[system_tests/base_config.yaml, line 73 at r3](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEIoroE2NXFQQJY2YYr:-LEO1Goc66GLwLKad02r:b7rxr8y) ([raw file](https://github.com/vmware/pyvcloud/blob/1e3d38f3cb8d221e8979761dbac6e0e0893f58b4/system_tests/base_config.yaml#L73)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Umm I still see two stray spaces :P

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244#-:-LEO1sdWAiFEIeqMAAHe:bnfp4nl)*

**Comment by hodgesrm** [comment]
Reviewed 2 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[system_tests/nsxt_tests.py, line 45 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFM_NlBeL2jz1_dl9d:-LEPfu0G1kLXRKMVmBCP:b-z8b3j6) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/system_tests/nsxt_tests.py#L45)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

How does the code ensure no manager is currently registered? I was expected to see something like an unregister that ignores any errors. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by ckolovson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[system_tests/nsxt_tests.py, line 45 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFM_NlBeL2jz1_dl9d:-LERRQVO3ge_tEP9-IFI:bec6go3) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/system_tests/nsxt_tests.py#L45)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

How does the code ensure no manager is currently registered? I was expected to see something like an unregister that ignores any errors. 
</blockquote></details>

Not sure what you’re asking. Unregister does an unregister of a specified NSX-T manager. There can be 0 or more. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by ckolovson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[system_tests/nsxt_tests.py, line 45 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFM_NlBeL2jz1_dl9d:-LERSaH5CfGtTsTRsdtz:b719en2) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/system_tests/nsxt_tests.py#L45)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

Not sure what you’re asking. Unregister does an unregister of a specified NSX-T manager. There can be 0 or more. 
</blockquote></details>

This test checks that after the unregister, the specified NSX-T manager is not registered. It doesn’t check first to see if it was registered before doing the unregister. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by ckolovson** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[system_tests/nsxt_tests.py, line 45 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFM_NlBeL2jz1_dl9d:-LES196J2fQ3H4hvoyO7:b-9c8d9p) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/system_tests/nsxt_tests.py#L45)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

This test checks that after the unregister, the specified NSX-T manager is not registered. It doesn’t check first to see if it was registered before doing the unregister. 
</blockquote></details>

I see what you're suggesting. I tried doing an unregister and ignoring errors, but delete_linked_resource (called by unregister) returns an error that can't be ignored, so this is not possible. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by ckolovson** [comment]
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[system_tests/nsxt_tests.py, line 45 at r2](https://reviewable.io/reviews/vmware/pyvcloud/244#-LEFM_NlBeL2jz1_dl9d:-LEUEgM-3Sx6p8HoDRXD:btkggtm) ([raw file](https://github.com/vmware/pyvcloud/blob/b59ba116b33e020a160f399f906bd9e606bf4472/system_tests/nsxt_tests.py#L45)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

I see what you're suggesting. I tried doing an unregister and ignoring errors, but delete_linked_resource (called by unregister) returns an error that can't be ignored, so this is not possible. 
</blockquote></details>

In the register test, I now check for the manager's existence. If it's already there, I unregister it. Comment is now addressed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/244#-:-LEV2V_zDZtPj4lfjqqd:bnfp4nl)*

**Comment by Harish0596** [comment]
Hi

Is there any recommended python library to manage operations on NSX-T manager, just like how we use pyvcloud to manage VCD

**Pull request merged**
