### PR TITLE
Add or remove rights from organization

### PR DESCRIPTION
**Pull request by sahithi**
1. New method to add new rights to a given organization.
2. New method to remove new rights from a given organization.
3. New method to list rights associated with a given organization.
4. Renamed existing method 'org.list_rights' to 'org.list_all_rights' as it lists all rights available in the System.
5. Minor refactoring of existing variable names.
6. Unit tests for add and remove rights from organization.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/174)

### CODE REVIEW

**Comment by anusuyar** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 614 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35A8hPWdSPPiHATmSh:-L35A8hPWdSPPiHATmSi:bc92ueg) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L614)):*
> ```Python
>         org_admin_resource = self.client.get_resource(self.href_admin)
>         org_rights = E.OrgRights()
>         for right in rights:
> ```

What happens if the org already have a particular right being added?

---

*[pyvcloud/vcd/org.py, line 646 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35BGAU9me77MS1csfe:-L35BGAVKbcadGH_xkd7:bpctr2j) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L646)):*
> ```Python
>                         if right_reference.get('name') == right:
>                             org_rights_resource.remove(right_reference)
>                             break
> ```

i think moving for right in rights: into outer loop will make it more readable. Also , since we are removing elemets in org_rights_resource.RightReference for each match, making it in inner loops makes for sense to me.

for right in rights:
     for right_reference in \
                        list(org_rights_resource.RightReference):
               if right_reference.get('name') == right:
                            org_rights_resource.remove(right_reference)
                            break;
       

---

*[pyvcloud/vcd/org.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35DGqcZzoMBSRJizCy:-L35DGqcZzoMBSRJizCz:blr44t9) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L666)):*
> ```Python
> 
>     def list_all_rights(self, name_filter=None):
>         """Retrieves the list of all rights available
> ```

I think the google based flake8 expects a period after the first line of docstring.

---

*[pyvcloud/vcd/org.py, line 689 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35DQmP7xfLisIHiQy9:-L35DQmP7xfLisIHiQyA:b6ko8g4) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L689)):*
> ```Python
> 
>     def list_my_rights(self):
>         """Retrieves the list of rights associated with the Organization
> ```

Period here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174)*

**Comment by anusuyar** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 688 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35MDT3xP0y0L_dlxno:-L35MDT3xP0y0L_dlxnp:b5vco91) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L688)):*
> ```Python
>         return result
> 
>     def list_my_rights(self):
> ```

something like list_org_rights might be a better name. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pyvcloud/vcd/org.py, line 614 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35A8hPWdSPPiHATmSh:-L35ZVanCBLQSIYjEeX_:b-w6nwi0) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L614)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

What happens if the org already have a particular right being added?
</blockquote></details>

its a no-op rest-api call. I tested this.

---

*[pyvcloud/vcd/org.py, line 646 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35BGAU9me77MS1csfe:-L35ZhoszLEd8am4UT_U:b-zic0lb) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L646)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

i think moving for right in rights: into outer loop will make it more readable. Also , since we are removing elemets in org_rights_resource.RightReference for each match, making it in inner loops makes for sense to me.

for right in rights:
     for right_reference in \
                        list(org_rights_resource.RightReference):
               if right_reference.get('name') == right:
                            org_rights_resource.remove(right_reference)
                            break;
       
</blockquote></details>

I deliberately chose to make it inner loop. On avg, any org can have rights ranging from 100 to 213 (max). And user may specify at the most around 10 rights per command. Traversing all of org's rights for each right input is a performance dent.

---

*[pyvcloud/vcd/org.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35DGqcZzoMBSRJizCy:-L35_xidVUhFh77RsvLZ:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L666)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I think the google based flake8 expects a period after the first line of docstring.
</blockquote></details>

Done.

---

*[pyvcloud/vcd/org.py, line 688 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35MDT3xP0y0L_dlxno:-L35a5t2vpsNf96aqr_R:b-ha3859) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L688)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

something like list_org_rights might be a better name. 
</blockquote></details>

Take an another look at below set of calls side by side.

org.list_my_rights()    org.list_org_rights()
org.list_all_rights()     org.list_all_rights()


I find org.list_my_rights() more pronounced in distinguishing itself from org.list_all_rights(). There is no scope for any future confusion here.
Let us wait if other reviewers think, I can change it then.

---

*[pyvcloud/vcd/org.py, line 689 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35DQmP7xfLisIHiQy9:-L35a09mB7mfz44ly-0H:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L689)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Period here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174)*

**Comment by anusuyar** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pyvcloud/vcd/org.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35DGqcZzoMBSRJizCy:-L35fBdQbaQqhzMXNmTG:b60mwtn) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L666)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You might have missed a period here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/org.py, line 610 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L3A3TjclKraoXNKLgjL:-L3A3TjclKraoXNKLgjM:badeo61) ([raw file](https://github.com/vmware/pyvcloud/blob/3c5c7e5c579c80cfb680aa7ecc0cec714394cd36/pyvcloud/vcd/org.py#L610)):*
> ```Python
> 
>         :return A :class:`lxml.objectify.StringElement` object representing
>         the updated Org rights resource.
> ```

Can we remove the resource at the end of this return in the doc ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/org.py, line 666 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L3A6WuLTtd_NB0VLpBR:-L3A6WuLTtd_NB0VLpBS:b-jqtory) ([raw file](https://github.com/vmware/pyvcloud/blob/3c5c7e5c579c80cfb680aa7ecc0cec714394cd36/pyvcloud/vcd/org.py#L666)):*
> ```Python
> 
>     def list_all_rights(self, name_filter=None):
>         """Retrieves the list of all rights available
> ```

List of all rights available in the system ? Could we have this as "list_all_system_rights" or "list_available_system_rights" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174)*

**Comment by sompa** [comment]
*[pyvcloud/vcd/org.py, line 688 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35MDT3xP0y0L_dlxno:-L3A6LglNXzFM9mS2Z08:b-a3r6a4) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L688)):*
> :return A :class:`lxml.objectify.StringElement` object representing
I think if we have "list_all_system_rights" for all rights available in the system, then we can also change this to org.list_all_org_rights(). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174)*

**Comment by sompa** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174)*

**Comment by sahithi** [comment]
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pyvcloud/vcd/org.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35DGqcZzoMBSRJizCy:-L36Zzryq3a5SwzDzlKE:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L666)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

You might have missed a period here?
</blockquote></details>

Done.

---

*[pyvcloud/vcd/org.py, line 688 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35MDT3xP0y0L_dlxno:-L3AMo-drLhlcwMe-jhL:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L688)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

> :return A :class:`lxml.objectify.StringElement` object representing
I think if we have "list_all_system_rights" for all rights available in the system, then we can also change this to org.list_all_org_rights(). 
</blockquote></details>

Done.

---

*[pyvcloud/vcd/org.py, line 610 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L3A3TjclKraoXNKLgjL:-L3AD7k-_XDR6r0-thyg:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/3c5c7e5c579c80cfb680aa7ecc0cec714394cd36/pyvcloud/vcd/org.py#L610)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Can we remove the resource at the end of this return in the doc ? 
</blockquote></details>

Done.

---

*[pyvcloud/vcd/org.py, line 666 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L3A6WuLTtd_NB0VLpBR:-L3AMpN9YaqSINTBWzVJ:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/3c5c7e5c579c80cfb680aa7ecc0cec714394cd36/pyvcloud/vcd/org.py#L666)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

List of all rights available in the system ? Could we have this as "list_all_system_rights" or "list_available_system_rights" ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174)*

**Comment by sompa** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-:-L3ANjOkaUWQmIo53Wt3:bnfp4nl)*

**Comment by sompa** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174)*

**Comment by sahithi** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pyvcloud/vcd/org.py, line 646 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-L35BGAU9me77MS1csfe:-L3ARcR36HuPdWfgC4jG:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/b157f590e639b73f4689c3fc61153e4108fd6e26/pyvcloud/vcd/org.py#L646)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I deliberately chose to make it inner loop. On avg, any org can have rights ranging from 100 to 213 (max). And user may specify at the most around 10 rights per command. Traversing all of org's rights for each right input is a performance dent.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-:-L3ARtoSDiT92fJNNPj0:bnfp4nl)*

**Comment by pacogomez** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/174#-:-L3Abx4dq0cbAHgLpAL_:bnfp4nl)*

**Pull request merged**
