### PR TITLE
VCDA-369: Adding capability to create isolated OrgVDC networks.

### PR DESCRIPTION
**Pull request by rocknes**
Adding capability to create isolated OrgVDC networks.

* Added a new function create_isolated_vdc_network() in vdc.py which can be used to create isolated org vdc networks,
* Added unit test for the same
* Ran yapf on vdc.py and vcd_network.py (P.s. pull request will contain few style changes in functions unrelated  to the current feature).

Unit test result :
(pyvcloud) C:\code\pyvcloud\tests>python -m unittest vcd_network.TestNetwork.test_020_create_isolated_orgvdc_network
.
----------------------------------------------------------------------
Ran 1 test in 64.571s

OK

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/171)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Thanks for the new commit formatting.  Looks nice!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/vdc.py, line 783 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/171#-L2czgaLSbFxd2h6MGjG:-L2czgaLSbFxd2h6MGjH:b-hs3boa) ([raw file](https://github.com/vmware/pyvcloud/blob/60fd02c72f8e61912cba3c83e476bb3ec221090e/pyvcloud/vcd/vdc.py#L783)):*
> ```Python
>             request_payload)
> 
>     def create_isolated_vdc_network(self,
> ```

Given the small amount of code necessary to implement isolated and direct networks, it makes me wonder why we don't just add bridged networks as well.   What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/171#-:-L2cymaIn0qP2T6XwEky:b-2tpwdc)*

**Comment by pacogomez** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/vdc.py, line 783 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/171#-L2czgaLSbFxd2h6MGjG:-L2fhHk0E4tuVHEeWOAK:b-3u6rgg) ([raw file](https://github.com/vmware/pyvcloud/blob/60fd02c72f8e61912cba3c83e476bb3ec221090e/pyvcloud/vcd/vdc.py#L783)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Given the small amount of code necessary to implement isolated and direct networks, it makes me wonder why we don't just add bridged networks as well.   What do you think?
</blockquote></details>

I think it is better to limit to the PR to the scope of the story.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/171#-:-L2fhFcNDAsPhPmIRm_x:bnfp4nl)*

**Comment by pacogomez** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/171)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/vdc.py, line 783 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/171#-L2czgaLSbFxd2h6MGjG:-L2gwfGEo0hYeJO9K9Y8:bf9n6rs) ([raw file](https://github.com/vmware/pyvcloud/blob/60fd02c72f8e61912cba3c83e476bb3ec221090e/pyvcloud/vcd/vdc.py#L783)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

I think it is better to limit to the PR to the scope of the story.
</blockquote></details>

The code might look small, but significant effort is required to understand the vCD ReST api for the related operation. So I will prefer to add support for nat routed org vdc networks in a separate pull request.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/171)*

**Comment by anusuyar** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pyvcloud/vcd/vdc.py, line 819 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/171#-L2gy7gPPeYdk-kY-3kj:-L2gy7gPPeYdk-kY-3kk:b-v9fcrj) ([raw file](https://github.com/vmware/pyvcloud/blob/60fd02c72f8e61912cba3c83e476bb3ec221090e/pyvcloud/vcd/vdc.py#L819)):*
> ```Python
>         :param dhcp_ip_range_start (str): Start address of the IP range \
>             used for DHCP addresses
>         :param dhcp_ip_range_end (): End address of the IP range used for \
> ```

(str) missing

---

*[pyvcloud/vcd/vdc.py, line 821 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/171#-L2gyWcBWN4eHIBEAdHE:-L2gyWcBWN4eHIBEAdHF:b-7wegpq) ([raw file](https://github.com/vmware/pyvcloud/blob/60fd02c72f8e61912cba3c83e476bb3ec221090e/pyvcloud/vcd/vdc.py#L821)):*
> ```Python
>         :param dhcp_ip_range_end (): End address of the IP range used for \
>             DHCP addresses
>         :param is_shared: (bool): True, is the network is shared with other \
> ```

typo:
True if the network is shared. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/171)*

**Comment by anusuyar** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/171)*

**Comment by rocknes** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pyvcloud/vcd/vdc.py, line 819 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/171#-L2gy7gPPeYdk-kY-3kj:-L2hAHpr44W7bUb_isAi:b-8b11j9) ([raw file](https://github.com/vmware/pyvcloud/blob/60fd02c72f8e61912cba3c83e476bb3ec221090e/pyvcloud/vcd/vdc.py#L819)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

(str) missing
</blockquote></details>

Added

---

*[pyvcloud/vcd/vdc.py, line 821 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/171#-L2gyWcBWN4eHIBEAdHE:-L2hAIx0o03pZLyEp8Z6:b3qh3qt) ([raw file](https://github.com/vmware/pyvcloud/blob/60fd02c72f8e61912cba3c83e476bb3ec221090e/pyvcloud/vcd/vdc.py#L821)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

typo:
True if the network is shared. 
</blockquote></details>

fixed typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/171)*

**Comment by anusuyar** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/171#-:-L2hB35haLYc3BtwPYvp:bnfp4nl)*

**Comment by anusuyar** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/171)*

**Pull request merged**
