### PR TITLE
[VDP-1665, VCDA-642] Implemented enable, disable, detach VC

### PR DESCRIPTION
**Pull request by ckolovson**
[VDP-1665, VCDA-642] Implemented enable, disable, detach VC

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/260)

### CODE REVIEW

**Comment by hodgesrm** [comment]
This looks great.  Can you add short comments to the unit test to describe what each test checks? (Useful examples in catalog_tests.py or client_tests.py.) 

It's an :lgtm: once you do that.  No need to re-review. 

---

Reviewed 3 of 3 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/260#-:-LGR7ECJ5EX-kQ9zmylQ:b-tt43dx)*

**Comment by rocknes** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed, 6 unresolved discussions (waiting on @ckolovson)

---

*[pyvcloud/vcd/platform.py, line 351 at r2](https://reviewable.io/reviews/vmware/pyvcloud/260#-LGRjUoxBQzHFXEQwh9s:-LGRjUoxBQzHFXEQwh9t:bxese9q) ([raw file](https://github.com/vmware/pyvcloud/blob/d3e44985f5ff51735d40ced058785f8456c184d5/pyvcloud/vcd/platform.py#L351)):*
> ```Python
> 
>         :param str vc_name: name of VC server.
>         :param boolean enable_flag: True mean enable, False means disable.
> ```

True means?

---

*[pyvcloud/vcd/platform.py, line 353 at r2](https://reviewable.io/reviews/vmware/pyvcloud/260#-LGRjdsmEfNYaEBN5Uin:-LGRjdsmEfNYaEBN5Uio:b-3kgj4g) ([raw file](https://github.com/vmware/pyvcloud/blob/d3e44985f5ff51735d40ced058785f8456c184d5/pyvcloud/vcd/platform.py#L353)):*
> ```Python
>         :param boolean enable_flag: True mean enable, False means disable.
> 
>         :return: an object containing XML data of the VC server.
> ```

We should be more specific about the data returned. If it's one of the XML element types listed in EntityType enum in client.py, we should list that.

---

*[pyvcloud/vcd/platform.py, line 357 at r2](https://reviewable.io/reviews/vmware/pyvcloud/260#-LGRkHDr0YHWcM2Njnpn:-LGRkHDs3-qRTpPsXIzp:bmt8knn) ([raw file](https://github.com/vmware/pyvcloud/blob/d3e44985f5ff51735d40ced058785f8456c184d5/pyvcloud/vcd/platform.py#L357)):*
> ```Python
>         :rtype: lxml.objectify.ObjectifiedElement
>         """
>         vc_record = self.get_vcenter(vc_name)
> ```

the function get_vcenter() returns a full blown vc xml resource not a record.

---

*[pyvcloud/vcd/platform.py, line 359 at r2](https://reviewable.io/reviews/vmware/pyvcloud/260#-LGRkTfA1Hcqt1ydJpJ-:-LGRkTfA1Hcqt1ydJpJ0:bdfglxm) ([raw file](https://github.com/vmware/pyvcloud/blob/d3e44985f5ff51735d40ced058785f8456c184d5/pyvcloud/vcd/platform.py#L359)):*
> ```Python
>         vc_record = self.get_vcenter(vc_name)
>         vc_href = vc_record.get('href')
>         vc = self.client.get_resource(vc_href)
> ```

the above two lines are not required.

---

*[pyvcloud/vcd/platform.py, line 380 at r2](https://reviewable.io/reviews/vmware/pyvcloud/260#-LGRk_rQEN8tyhgORNc-:-LGRk_rR8hoXKumUmfsb:b-rvaq6f) ([raw file](https://github.com/vmware/pyvcloud/blob/d3e44985f5ff51735d40ced058785f8456c184d5/pyvcloud/vcd/platform.py#L380)):*
> ```Python
>         """
>         vc_record = self.get_vcenter(vc_name)
>         vc_href = vc_record.get('href')
> ```

Same as my other comment in enable_diasble_vcenter function.

---

*[pyvcloud/vcd/platform.py, line 382 at r2](https://reviewable.io/reviews/vmware/pyvcloud/260#-LGRkwDsD580iVD88rs0:-LGRkwDsD580iVD88rs1:bqgzl0g) ([raw file](https://github.com/vmware/pyvcloud/blob/d3e44985f5ff51735d40ced058785f8456c184d5/pyvcloud/vcd/platform.py#L382)):*
> ```Python
>         vc_href = vc_record.get('href')
>         vc = self.client.get_resource(vc_href)
>         if vc.IsEnabled:
> ```

vc.IsEnabled will return a lmxl.Objectified element and not a boolean, we might have to cast this object to a bool. Can you please test the current code works or not (manual testing is fine)?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/260)*

**Comment by rocknes** [comment]
Review status: all files reviewed, 6 unresolved discussions (waiting on @ckolovson)

---

*[pyvcloud/vcd/platform.py, line 351 at r2](https://reviewable.io/reviews/vmware/pyvcloud/260#-LGRjUoxBQzHFXEQwh9s:-LGRpBtD7ysHr4puh6f7:b2wi75h) ([raw file](https://github.com/vmware/pyvcloud/blob/d3e44985f5ff51735d40ced058785f8456c184d5/pyvcloud/vcd/platform.py#L351)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

True means?
</blockquote></details>

Clarification on the comment above : 'mean -> means' for True?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/260)*

**Comment by ckolovson** [comment]
Done.

---

Review status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @hodgesrm and @ckolovson)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/260#-:-LGSFCgg2Jfui0Q_6qkf:b-896fix)*

**Comment by ckolovson** [comment]
Review status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @hodgesrm and @rocknes)

---

*[pyvcloud/vcd/platform.py, line 353 at r2](https://reviewable.io/reviews/vmware/pyvcloud/260#-LGRjdsmEfNYaEBN5Uin:-LGWTQod174jjHUOPXHV:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/d3e44985f5ff51735d40ced058785f8456c184d5/pyvcloud/vcd/platform.py#L353)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

It actually returns a Task. How shall I document that? 
</blockquote></details>

Done.

---

*[pyvcloud/vcd/platform.py, line 357 at r2](https://reviewable.io/reviews/vmware/pyvcloud/260#-LGRkHDr0YHWcM2Njnpn:-LGWTVCp-XqF_uEEAmNR:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/d3e44985f5ff51735d40ced058785f8456c184d5/pyvcloud/vcd/platform.py#L357)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

Is this better?
:rtype: lxml.objectify.ObjectifiedElement (virtual center XML resource)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/260)*

**Pull request merged**
