### PR TITLE
 Implementing SDK methods to update acl of vdc and vapp

### PR DESCRIPTION
**Pull request by anusuyar**
Implementing SDK methods to update acl of vdc and vapp.

Implemented the following methods
add_access_settings
remove_access_settings
share_access
unshare_access

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/169)

### CODE REVIEW

**Comment by sompa** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-:-L2W8UgOGN9_8A5SkHhc:bnfp4nl)*

**Comment by sompa** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169)*

**Comment by pacogomez** [comment]
see my comments

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pyvcloud/vcd/acl.py, line 46 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2f_eOisU41-CpOofq6:-L2f_eOisU41-CpOofq7:b-eh2wgk) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/acl.py#L46)):*
> ```Python
>         return self.resource
> 
>     def update_resource(self, control_access_params):
> ```

docstring is missing

---

*[pyvcloud/vcd/acl.py, line 48 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2f_nFOPJfX_2Bur-kz:-L2f_nFOPJfX_2Bur-l-:b-gquvw5) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/acl.py#L48)):*
> ```Python
>     def update_resource(self, control_access_params):
>         # vdc acl is updated though PUT instead of POST
>         if self.parent_resource.attrib.get('type') == EntityType.VDC.value:
> ```

instead of 'hard coding' this decision, is there any other way that vCD can tell us wether to use put or post with no previous knowledge?

---

*[pyvcloud/vcd/org.py, line 644 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2fcUgo-b6HbQQQjkaV:-L2fcUgo-b6HbQQQjkaW:baok7ua) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/org.py#L644)):*
> ```Python
>         :return:  A :class:`lxml.objectify.StringElement` object representing
>             the access settings of the catalog.
>         """  # NOQA
> ```

please reformat docstring following guidelines and remove NOQA

---

*[pyvcloud/vcd/vapp.py, line 334 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2fbzcmzB1cqhaY3DEj:-L2fbzcmzB1cqhaY3DEk:b-libnfc) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vapp.py#L334)):*
> ```Python
>         :param access_settings_list: (list of dict): list of access_setting
>             in the dict format. Each dict contains:
>             type: (str): type of the subject. Only 'user' allowed for vapp.
> ```

does it support group as well?

---

*[pyvcloud/vcd/vapp.py, line 352 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2fc4jj5u7CgP4Q3tWe:-L2fc4jj5u7CgP4Q3tWf:b-libnfc) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vapp.py#L352)):*
> ```Python
>         :param access_settings_list: (list of dict): list of access_setting
>             in the dict format. Each dict contains:
>             type: (str): type of the subject. Only 'user' allowed for vdc.
> ```

does it support group as well?

---

*[pyvcloud/vcd/vdc.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2fcBEPBC4Tqi_f6zjw:-L2fcBEPBC4Tqi_f6zjx:b-libnfc) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vdc.py#L666)):*
> ```Python
>         :param access_settings_list: (list of dict): list of access_setting
>             in the dict format. Each dict contains:
>             type: (str): type of the subject. 'Only 'user' allowed for vdc.
> ```

does it support group as well?

---

*[pyvcloud/vcd/vdc.py, line 684 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2fcCy0VaBzImGZ0ZaK:-L2fcCy0VaBzImGZ0ZaL:b-libnfc) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vdc.py#L684)):*
> ```Python
>         :param access_settings_list: (list of dict): list of access_setting
>             in the dict format. Each dict contains:
>             type: (str): type of the subject. Only 'user' allowed for vdc.
> ```

does it support group as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-:-L2fcP3rjntjGF6-605-:bbl1p12)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[pyvcloud/vcd/acl.py, line 260 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gizuXR1VQBVX8mfe1:-L2gizuXR1VQBVX8mfe2:bcai7r1) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/acl.py#L260)):*
> ```Python
>         for access_setting in access_settings_list:
>             if access_setting["type"] == 'user':
>                 org_href = self.get_parent_org_href()
> ```

In my opinion get_org_href is clear enough for the function name.

---

*[pyvcloud/vcd/acl.py, line 299 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gjNEDi4skBng6FfJc:-L2gjNEED4SK9eZF2DJR:b2ra259) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/acl.py#L299)):*
> ```Python
>         except MissingLinkException:
>             # for vapp, have to get the org via vdc
>             vdc_href = find_link(self.parent_resource, RelationType.UP,
> ```

This is not a good practice! We shouldn't put business logic in catch block .
Have a switch case (based on type of parent)  if necessary.

---

*[pyvcloud/vcd/org.py, line 640 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gjtIuade_o5jG25to:-L2gjtIuade_o5jG25tp:b-51qv9y) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/org.py#L640)):*
> ```Python
>     def get_catalog_access_settings(self, catalog_name):
>         """Get the access settings of a catalog.
>         
> ```

stray space

---

*[pyvcloud/vcd/vapp.py, line 352 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2fc4jj5u7CgP4Q3tWe:-L2gkVIf77inZFNpROkw:bf2n7ix) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vapp.py#L352)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

does it support group as well?
</blockquote></details>

[doc] "Only 'user' allowed for vdc" - doesn't seem to apply to vApps.

---

*[pyvcloud/vcd/vapp.py, line 363 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gof_aQ3GdEZdoAdrq:-L2gof_aQ3GdEZdoAdrr:b-662uy9) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vapp.py#L363)):*
> ```Python
>         return acl.remove_access_settings(access_settings_list, remove_all)
> 
>     def share_access(self, everyone_access_level='ReadOnly'):
> ```

nit : Can we name these functions to share_with/unshare_from

share_access sounds a bit off

---

*[pyvcloud/vcd/vapp.py, line 367 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gp7Tlp_5gMd4DV-sy:-L2gp7Tlp_5gMd4DV-sz:b286xa) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vapp.py#L367)):*
> ```Python
> 
>         :param everyone_access_level: (str) : access level when sharing the
>             vdc with everyone. One of 'ReadOnly', 'Change', 'FullControl'
> ```

"sharing the vdc"?

One of -> Values can be {'R', 'C', 'F'}

---

*[pyvcloud/vcd/vdc.py, line 669 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gpWt4ZD17N3pdNWq4:-L2gpWt4ZD17N3pdNWq5:bqsxm2s) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vdc.py#L669)):*
> ```Python
>             name: (str): name of the user.
>             access_level: (str): access_level of the particular subject.
>             Only 'ReadOnly' allowed for vdc.
> ```

nit : is allowed

---

*[pyvcloud/vcd/vdc.py, line 710 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2grphywY9AHuSdwYYt:-L2grphywY9AHuSdwYYu:b-vp5c6) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vdc.py#L710)):*
> ```Python
>         """Unshare the vdc from all members of current organization.
> 
>         Should give individual access to at least one user before un sharing
> ```

un sharing -> unsharing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169)*

**Comment by anusuyar** [comment]
Review status: 4 of 8 files reviewed at latest revision, 14 unresolved discussions.

---

*[pyvcloud/vcd/acl.py, line 46 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2f_eOisU41-CpOofq6:-L2hm11Zfc-P1HCP5KWf:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/acl.py#L46)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

docstring is missing
</blockquote></details>

Done.

---

*[pyvcloud/vcd/acl.py, line 48 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2f_nFOPJfX_2Bur-kz:-L2hm1wIB6n5XBdw2VgV:b-pm7d8x) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/acl.py#L48)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

instead of 'hard coding' this decision, is there any other way that vCD can tell us wether to use put or post with no previous knowledge?
</blockquote></details>

We are not getting whether we need todo  put or post from the VCD. We only this the following info

 <Link rel="controlAccess" href="https://bos1-vcd-sp-static-199-204.eng.vmware.com/api/catalog/5828a8b1-5d4e-477c-8701-b219f814872f/action/controlAccess" type="application/vnd.vmware.vcloud.controlAccess+xml"/>

So I don't think we can avoid having this hard coding. 

---

*[pyvcloud/vcd/acl.py, line 260 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gizuXR1VQBVX8mfe1:-L2hZVnv5ZtbFAa9hCpg:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/acl.py#L260)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

In my opinion get_org_href is clear enough for the function name.
</blockquote></details>

Done.

---

*[pyvcloud/vcd/acl.py, line 299 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gjNEDi4skBng6FfJc:-L2ht2_J17ubCFlmXhK5:b-gyoqj) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/acl.py#L299)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This is not a good practice! We shouldn't put business logic in catch block .
Have a switch case (based on type of parent)  if necessary.
</blockquote></details>

Done. Use if statement based on parent_resouce

---

*[pyvcloud/vcd/org.py, line 640 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gjtIuade_o5jG25to:-L2huUlu3CDhhMPbjSNe:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/org.py#L640)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

stray space
</blockquote></details>

Done.

---

*[pyvcloud/vcd/org.py, line 644 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2fcUgo-b6HbQQQjkaV:-L2huW8StiG3XPiaoG1o:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/org.py#L644)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

please reformat docstring following guidelines and remove NOQA
</blockquote></details>

Done.

---

*[pyvcloud/vcd/vapp.py, line 334 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2fbzcmzB1cqhaY3DEj:-L2guf4tiDDdzbI78kQB:b-8vrsx) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vapp.py#L334)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

does it support group as well?
</blockquote></details>

We do not have support for groups in this current implementation.  Groups can only be imported from an LDAP server. Since we do not have support for LDAP yet in the SDK, I didn't add support for the group.  We can have a separate task to import groups and add support of groups in acl.

https://pubs.vmware.com/vca/index.jsp#com.vmware.vcloud.api.doc_56/GUID-36D7DB69-C6BA-4778-84C0-E5D187AE59A8.html

---

*[pyvcloud/vcd/vapp.py, line 352 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2fc4jj5u7CgP4Q3tWe:-L2h1JT5zJRiSEDY6pJc:bdru4ei) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vapp.py#L352)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

[doc] "Only 'user' allowed for vdc" - doesn't seem to apply to vApps.
</blockquote></details>

@pacogomez We do not have support for groups in this current implementation of acl.  Groups can only be imported from an LDAP server. Since we do not have support for LDAP yet in the SDK, I didn't add support for the group.  We can have a separate task to import groups and add support of groups in acl.

https://pubs.vmware.com/vca/index.jsp#com.vmware.vcloud.api.doc_56/GUID-36D7DB69-C6BA-4778-84C0-E5D187AE59A8.html

@rocknes changed to vapp

---

*[pyvcloud/vcd/vapp.py, line 363 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gof_aQ3GdEZdoAdrq:-L2hGu5ZEQYhhxppTpT9:bujy2n8) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vapp.py#L363)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit : Can we name these functions to share_with/unshare_from

share_access sounds a bit off
</blockquote></details>

Since we have documented what share_access mean in the docstring, the current method name should be fine i think.

---

*[pyvcloud/vcd/vapp.py, line 367 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gp7Tlp_5gMd4DV-sy:-L2hZqbfxbJ8Wqn3d1gX:b-usr0ab) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vapp.py#L367)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

"sharing the vdc"?

One of -> Values can be {'R', 'C', 'F'}
</blockquote></details>

changed vdc to vapp.
'One of' is the wording in the api documentaion. I prefer to have this way.

---

*[pyvcloud/vcd/vdc.py, line 666 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2fcBEPBC4Tqi_f6zjw:-L2gvtXJYb-ncVEgYChz:b-7ncxw5) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vdc.py#L666)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

does it support group as well?
</blockquote></details>

We do not have support for groups in this current implementation.  Groups can only be imported from an LDAP server. Since we do not have support for LDAP yet in the SDK, I didn't add support for the group.  We can have a separate task to import groups and add support of groups in acl.

https://pubs.vmware.com/vca/index.jsp#com.vmware.vcloud.api.doc_56/GUID-36D7DB69-C6BA-4778-84C0-E5D187AE59A8.html

---

*[pyvcloud/vcd/vdc.py, line 669 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gpWt4ZD17N3pdNWq4:-L2hx61swNrHFzt4rsjE:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vdc.py#L669)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit : is allowed
</blockquote></details>

Done.

---

*[pyvcloud/vcd/vdc.py, line 684 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2fcCy0VaBzImGZ0ZaK:-L2gvut4BU8s3XFVF0MY:b-xl1ugy) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vdc.py#L684)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

does it support group as well?
</blockquote></details>

We do not have support for groups in this current implementation of acl.  Groups can only be imported from an LDAP server. Since we do not have support for LDAP yet in the SDK, I didn't add support for the group.  We can have a separate task to import groups and add support of groups in acl.

https://pubs.vmware.com/vca/index.jsp#com.vmware.vcloud.api.doc_56/GUID-36D7DB69-C6BA-4778-84C0-E5D187AE59A8.html

---

*[pyvcloud/vcd/vdc.py, line 710 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2grphywY9AHuSdwYYt:-L2hxCvtmNKWPIB942ns:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vdc.py#L710)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

un sharing -> unsharing
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169)*

**Comment by pacogomez** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[pyvcloud/vcd/acl.py, line 67 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2maaaOfylb7Kze4MPx:-L2maaaOfylb7Kze4MPy:benake5) ([raw file](https://github.com/vmware/pyvcloud/blob/e8620e83a21313c799aaec60b48bc878501dbfb7/pyvcloud/vcd/acl.py#L67)):*
> ```Python
>                                      EntityType.CONTROL_ACCESS_PARAMS.value,
>                                      control_access_params)
>         return self.resource
> ```

One potential issue that I see with this approach is that the content of `self.resource` will depend on the response from the call. What happens if there is an error? I think it would be better just to return the response from the call and not modify the local cache `self.resource`

---

*[pyvcloud/vcd/acl.py, line 99 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2mW9ff5pkcJU6bQiBu:-L2mW9ff5pkcJU6bQiBv:b-19kk0u) ([raw file](https://github.com/vmware/pyvcloud/blob/e8620e83a21313c799aaec60b48bc878501dbfb7/pyvcloud/vcd/acl.py#L99)):*
> ```Python
>             return self.resource
> 
>         control_access_params = deepcopy(self.resource)
> ```

I think this is the better way to implement it, so local cache is not modified

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169)*

**Comment by anusuyar** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[pyvcloud/vcd/acl.py, line 67 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2maaaOfylb7Kze4MPx:-L303O1tYWrjAfM6ZH1t:b7ydfx2) ([raw file](https://github.com/vmware/pyvcloud/blob/e8620e83a21313c799aaec60b48bc878501dbfb7/pyvcloud/vcd/acl.py#L67)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

One potential issue that I see with this approach is that the content of `self.resource` will depend on the response from the call. What happens if there is an error? I think it would be better just to return the response from the call and not modify the local cache `self.resource`
</blockquote></details>

_do_request() will throw an exception for any response code other than in the 200 range.  So if there is an error, post_linked_resource will throw an exception and self.resource will not be overwritten with bad xml.
 ``` def _do_request()
    if 200 <= sc <= 299:
            return _objectify_response(response) if objectify_results else \
                etree.fromstring(response.content)

        if 400 <= sc <= 499:
            raise VcdErrorResponseException(
                sc, self._get_response_request_id(response),
                objectify.fromstring(response.content))```

I think modifying the resource might be useful. if a user wants to remove all acl and share the vapp to all org members via SDK, they can do the following 

acl = Acl(self.client, vapp_resource)
 acl.remove_access_settings(access_settings_list, remove_all)
acl.share_access()

without updating the cahce, acl.share_access() will have a older version of self.resource ( not the one after the remove_access_settings) resulting in a wrong update.
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169)*

**Comment by sahithi** [comment]
Reviewed 4 of 8 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[pyvcloud/vcd/acl.py, line 67 at r2](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2maaaOfylb7Kze4MPx:-L30RS5PxTnYzqTfRF84:bdxz2ve) ([raw file](https://github.com/vmware/pyvcloud/blob/e8620e83a21313c799aaec60b48bc878501dbfb7/pyvcloud/vcd/acl.py#L67)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

_do_request() will throw an exception for any response code other than in the 200 range.  So if there is an error, post_linked_resource will throw an exception and self.resource will not be overwritten with bad xml.
 ``` def _do_request()
    if 200 <= sc <= 299:
            return _objectify_response(response) if objectify_results else \
                etree.fromstring(response.content)

        if 400 <= sc <= 499:
            raise VcdErrorResponseException(
                sc, self._get_response_request_id(response),
                objectify.fromstring(response.content))```

I think modifying the resource might be useful. if a user wants to remove all acl and share the vapp to all org members via SDK, they can do the following 

acl = Acl(self.client, vapp_resource)
 acl.remove_access_settings(access_settings_list, remove_all)
acl.share_access()

without updating the cahce, acl.share_access() will have a older version of self.resource ( not the one after the remove_access_settings) resulting in a wrong update.
</blockquote></details>

I think updating self.resource is okay as long as we are not actually modifying the self.resource itself in the method. In cases like that, use deepcopy().

---

*[pyvcloud/vcd/acl.py, line 56 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L30QB9LVZGJT7Wzidwr:-L30QB9LVZGJT7Wzidws:b-i6rc88) ([raw file](https://github.com/vmware/pyvcloud/blob/53e9f5bc83af2271c1494e7be46d610a0017e0f6/pyvcloud/vcd/acl.py#L56)):*
> ```Python
>         if self.parent_resource.attrib.get('type') == EntityType.VDC.value:
>             self.resource = self.client.put_resource(
>                 self.parent_resource.get('href') + '/action/controlAccess/',
> ```

We should avoid hard-coding of the links unless it becomes really cumbersome to get the link. Links can be obtained from the parent resource using find_link(). Here, Parent resource catalog or vdc should have the link readily available. 

---

*[pyvcloud/vcd/acl.py, line 260 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L30TEuGi3bM6lPbFGCl:-L30TEuGi3bM6lPbFGCm:b-rfbsnd) ([raw file](https://github.com/vmware/pyvcloud/blob/53e9f5bc83af2271c1494e7be46d610a0017e0f6/pyvcloud/vcd/acl.py#L260)):*
> ```Python
>         for access_setting in access_settings_list:
>             if access_setting["type"] == 'user':
>                 org_href = self.get_org_href()
> ```

Why do we need to find link for the org? For subject type user, can't we re-use org-in-use or org_href? We anyway ruled out the option of users from different org earlier in our discussion.

---

*[pyvcloud/vcd/vapp.py, line 363 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gof_aQ3GdEZdoAdrq:-L30V57rU3cOFtDTCICQ:b-n573k0) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vapp.py#L363)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Since we have documented what share_access mean in the docstring, the current method name should be fine i think.
</blockquote></details>

+1
Consider share_to_everyone (or) share_with_org_members.

---

*[pyvcloud/vcd/vapp.py, line 376 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L30VZpRsfGJEMUZKy2Q:-L30VZpRsfGJEMUZKy2R:b-8i9w11) ([raw file](https://github.com/vmware/pyvcloud/blob/53e9f5bc83af2271c1494e7be46d610a0017e0f6/pyvcloud/vcd/vapp.py#L376)):*
> ```Python
>         return acl.share_access(everyone_access_level)
> 
>     def unshare_access(self):
> ```

Consider renaming the method.

---

*[pyvcloud/vcd/vdc.py, line 695 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L30VwfXxaAHdx7liKMS:-L30VwfYTJ3zeZiaYU3c:b-88qt3o) ([raw file](https://github.com/vmware/pyvcloud/blob/53e9f5bc83af2271c1494e7be46d610a0017e0f6/pyvcloud/vcd/vdc.py#L695)):*
> ```Python
>         return acl.remove_access_settings(access_settings_list, remove_all)
> 
>     def share_access(self, everyone_access_level='ReadOnly'):
> ```

Consider a different method name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169)*
<!-- Sent from Reviewable.io -->

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[pyvcloud/vcd/acl.py, line 56 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L30QB9LVZGJT7Wzidwr:-L30jIrHR2_-jEWja5od:b1ykup1) ([raw file](https://github.com/vmware/pyvcloud/blob/53e9f5bc83af2271c1494e7be46d610a0017e0f6/pyvcloud/vcd/acl.py#L56)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We should avoid hard-coding of the links unless it becomes really cumbersome to get the link. Links can be obtained from the parent resource using find_link(). Here, Parent resource catalog or vdc should have the link readily available. 
</blockquote></details>

the previous implementation is preferred, we should address the issue of loosing controlAccess links on a separate issue, it might be a bug

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169)*

**Comment by anusuyar** [comment]
Review status: 1 of 8 files reviewed at latest revision, 13 unresolved discussions.

---

*[pyvcloud/vcd/acl.py, line 56 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L30QB9LVZGJT7Wzidwr:-L30mQh4umqK52MI8dI2:b-l7689k) ([raw file](https://github.com/vmware/pyvcloud/blob/53e9f5bc83af2271c1494e7be46d610a0017e0f6/pyvcloud/vcd/acl.py#L56)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

the previous implementation is preferred, we should address the issue of loosing controlAccess links on a separate issue, it might be a bug
</blockquote></details>

Done. Reverted to previous impl

---

*[pyvcloud/vcd/acl.py, line 260 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L30TEuGi3bM6lPbFGCl:-L30uqzdhu497t5p7aBB:byitab0) ([raw file](https://github.com/vmware/pyvcloud/blob/53e9f5bc83af2271c1494e7be46d610a0017e0f6/pyvcloud/vcd/acl.py#L260)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Why do we need to find link for the org? For subject type user, can't we re-use org-in-use or org_href? We anyway ruled out the option of users from different org earlier in our discussion.
</blockquote></details>

org_in_use and org_href are in the client profile. It is not available to VApp and Vdc objects. only in vcd-cli.  In order to find the org_href from Acl class, getting it from parent_resource(using find_link) seemed to be a better way.

---

*[pyvcloud/vcd/vapp.py, line 363 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L2gof_aQ3GdEZdoAdrq:-L30mIOAlf8DX6RnSSl_:btywchy) ([raw file](https://github.com/vmware/pyvcloud/blob/c1b12368e5932357ada8edf86464f490b3101fd4/pyvcloud/vcd/vapp.py#L363)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

+1
Consider share_to_everyone (or) share_with_org_members.
</blockquote></details>

Done. changed to share_with_org_members and unshare_from_org_members

---

*[pyvcloud/vcd/vapp.py, line 376 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L30VZpRsfGJEMUZKy2Q:-L30mKEYSIC0WB05uOEp:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/53e9f5bc83af2271c1494e7be46d610a0017e0f6/pyvcloud/vcd/vapp.py#L376)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Consider renaming the method.
</blockquote></details>

Done.

---

*[pyvcloud/vcd/vdc.py, line 695 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-L30VwfXxaAHdx7liKMS:-L30mM1uJPrOhXt6Au7D:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/53e9f5bc83af2271c1494e7be46d610a0017e0f6/pyvcloud/vcd/vdc.py#L695)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Consider a different method name.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-:-L327L1VTYmc1B0oTVzt:bnfp4nl)*

**Comment by pacogomez** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169#-:-L33_XPZNXskBmSPsv44:bnfp4nl)*

**Comment by pacogomez** [comment]
Reviewed 1 of 7 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/169)*

**Pull request merged**
