### PR TITLE
VCDA-236

### PR DESCRIPTION
**Pull request by pacogomez**
create empty vApp and add VMs

```
$ python -m unittest vcd_vapp_vm.TestVAppVM -v
test_0001_create_vapp (vcd_vapp_vm.TestVAppVM) ... ok
test_0002_add_vm (vcd_vapp_vm.TestVAppVM) ... ok
test_1000_delete_vapp (vcd_vapp_vm.TestVAppVM) ... ok

----------------------------------------------------------------------
Ran 3 tests in 27.808s

OK
```

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/151)

### CODE REVIEW

**Comment by sahithi** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/list-vapps.py, line 27 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fh8j6TJg5kWkVbO2f:-L0fh8j6TJg5kWkVbO2g:bypy87b) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/examples/list-vapps.py#L27)):*
> ```Python
> vdc_resource = org.get_vdc('orgVdc-1')
> vdc = VDC(client, resource=vdc_resource)
> vapps = vdc.list_resources()
> ```

vdc.list_resources() - it should  return other key resources like storage profiles, disks, networks.

---

*[pyvcloud/vcd/vapp.py, line 319 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fiCkZfRXeB6awTVJD:-L0fiCkZfRXeB6awTVJE:beflhn9) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L319)):*
> ```Python
>         networks = self.get_all_networks()
>         if networks is None or len(networks) < index + 1:
>             raise Exception('Can\'t find the specified vApp network')
> ```

Error message is not indicative of the actual status - "vApp does not have networks at all". 
raise Exception('vApp <name> doesn't have any networks')

Speaking of which, can this ever be the case? If we do not specify any network by default, it is automatically connected to the default vdc network, right? If that's the case do we need this check here?

---

*[pyvcloud/vcd/vapp.py, line 322 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fl0D_OgDssfzkh5B9:-L0fl0Da6zaLhsltNAqy:b-5ytzff) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L322)):*
> ```Python
>         return networks[index].get('{' + NSMAP['ovf'] + '}name')
> 
>     def to_sourced_item(self, spec):
> ```

Can we track new Jira task to include an array of source, target vms, storage profiles as part of the spec? 

---

*[pyvcloud/vcd/vdc.py, line 587 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fmHyfYcgmum10TBl8:-L0fmHyfYcgmum10TBl9:b-4mdqe6) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vdc.py#L587)):*
> ```Python
>                                                   RelationType.REMOVE, None)
> 
>     def create_vapp(self,
> ```

create_empty_vapp makes more sense as we are not passing any VM specs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/151)*

**Comment by anusuyar** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pyvcloud/vcd/vapp.py, line 233 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fzHSgcCYoZzwqvo0z:-L0fzHSgcCYoZzwqvo1-:b8lx5fx) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L233)):*
> ```Python
>            hasattr(self.resource.Children, 'Vm') and \
>            len(self.resource.Children.Vm) > 0:
>             return self.resource.Children.Vm
> ```

I feel it could be better if we create a result = [] variable and use it to assign result= self.resource.Children.Vm

```result= []
if hasattr(self.resource, 'Children') and \
           hasattr(self.resource.Children, 'Vm') and \
           len(self.resource.Children.Vm) > 0:
               result = self.resource.Children.Vm
return result 
```


---

*[pyvcloud/vcd/vapp.py, line 250 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0g-0Ual_VfdgKf34w6:-L0g-0UbgD3H8Tb3fSQY:b-8phk11) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L250)):*
> ```Python
>             if vm.get('name') == vm_name:
>                 return vm
>         raise Exception('can\'t find VM')
> ```

Adding the vm_name in the exception msg string is better

---

*[pyvcloud/vcd/vapp.py, line 319 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fiCkZfRXeB6awTVJD:-L0g1m1pfLRhJVURrNG6:b65p8vk) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L319)):*
> Error message is not indicative of the actual status - "vApp does not have networks at all".
> raise Exception('vApp  doesn't have any networks')

It is possible the vapp has networks, but there is no network with the specified index. 


for the purpose of the method 'get_vapp_network_name' we either find the network with the specified index. or we don't. The Exception message seems fine to me.

---

*[pyvcloud/vcd/vapp.py, line 322 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fl0D_OgDssfzkh5B9:-L0g5B9eHKJmQLndh881:byjs0e4) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L322)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can we track new Jira task to include an array of source, target vms, storage profiles as part of the spec? 
</blockquote></details>

Can we rename spec to something more specific . say like vm_spec etc?

---

*[pyvcloud/vcd/vapp.py, line 327 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0g6WbDCjip4WCSu8X6:-L0g6WbDCjip4WCSu8X7:bg78w3p) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L327)):*
> ```Python
>         :param spec: (dict) containing:
>             vapp: (resource)(required) source vApp or vAppTemplate resource
>             source_vm_name: (str)(required) source VM name
> ```

I think the docstring format should have a ':' after the type

vapp: (resource): (required) source vApp or vAppTemplate resource. Please change the format in all other docstirng if you going to add ':'

---

*[pyvcloud/vcd/vdc.py, line 587 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fmHyfYcgmum10TBl8:-L0g9tXxuj9V_ryT_jxL:bkl96lv) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vdc.py#L587)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

create_empty_vapp makes more sense as we are not passing any VM specs.
</blockquote></details>

I think the name should be create_vapp. When we want to create vapp with vm, we should add a param vm_spec=None and use the spec to add vm to the vapp. When it is none, we just create an empty vapp.
create empty and non empty vapp could be handled by the same method.

In that case, we should change the doc string to ' Create a new  vApp in this VDC'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/151)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[examples/list-vapps.py, line 27 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fh8j6TJg5kWkVbO2f:-L0ityEIjK9E63HxoYKx:b-4sj6c7) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/examples/list-vapps.py#L27)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

vdc.list_resources() - it should  return other key resources like storage profiles, disks, networks.
</blockquote></details>

this method maps the `ResourceEntities` section of the OrgVDC XML, other resources are in other sections of the XML and can be retrieved separately

---

*[pyvcloud/vcd/vapp.py, line 233 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fzHSgcCYoZzwqvo0z:-L0ivS21YuE-0g9P0oXh:befwdwj) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L233)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I feel it could be better if we create a result = [] variable and use it to assign result= self.resource.Children.Vm

```result= []
if hasattr(self.resource, 'Children') and \
           hasattr(self.resource.Children, 'Vm') and \
           len(self.resource.Children.Vm) > 0:
               result = self.resource.Children.Vm
return result 


</blockquote></details>

Both approaches are very similar. This avoids using a new variable therefore is more concise.

---

*[pyvcloud/vcd/vapp.py, line 250 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0g-0Ual_VfdgKf34w6:-L0iwC_jRs9uf3r3jAab:b2oyzb3) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L250)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Adding the vm_name in the exception msg string is better
</blockquote></details>

I will modify it

---

*[pyvcloud/vcd/vapp.py, line 319 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fiCkZfRXeB6awTVJD:-L0ix4Q5NyGuhUalPjZe:b2o3qbw) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L319)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

> Error message is not indicative of the actual status - "vApp does not have networks at all".
> raise Exception('vApp  doesn't have any networks')

It is possible the vapp has networks, but there is no network with the specified index. 


for the purpose of the method 'get_vapp_network_name' we either find the network with the specified index. or we don't. The Exception message seems fine to me.
</blockquote></details>

this is a helper method that I created for the initial implementation but is no longer used. I will leave it in case it is needed in the future.

---

*[pyvcloud/vcd/vapp.py, line 322 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fl0D_OgDssfzkh5B9:-L0ixiMVPqMX4QV6KTtS:bgzsxoy) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L322)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Can we rename spec to something more specific . say like vm_spec etc?
</blockquote></details>

this method is designed to create a single `sourced_item`. the `add_vms` method below is the one that accepts an array of vm specs. I prefer to keep the name simple because it is later used in methods combined with indexes and other elements and it makes it more readable.

---

*[pyvcloud/vcd/vapp.py, line 327 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0g6WbDCjip4WCSu8X6:-L0iyhmAlX1npdlpHQKB:b2oyzb3) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L327)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I think the docstring format should have a ':' after the type

vapp: (resource): (required) source vApp or vAppTemplate resource. Please change the format in all other docstirng if you going to add ':'
</blockquote></details>

I will modify it

---

*[pyvcloud/vcd/vdc.py, line 587 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fmHyfYcgmum10TBl8:-L0j-K_GSqVALZoeUzDS:by73wm4) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vdc.py#L587)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I think the name should be create_vapp. When we want to create vapp with vm, we should add a param vm_spec=None and use the spec to add vm to the vapp. When it is none, we just create an empty vapp.
create empty and non empty vapp could be handled by the same method.

In that case, we should change the doc string to ' Create a new  vApp in this VDC'


</blockquote></details>

I like the idea of having an optional param for VM. It will be an array of vm specs. We can implement it in another task.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/151)*
<!-- Sent from Reviewable.io -->

**Comment by anusuyar** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/151)*

**Comment by pacogomez** [comment]
I merged the latest changes from upstream/master

---

Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-:-L0lKqWfsBucrPTWn1jQ:b-v06jrl)*

**Comment by anusuyar** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/151)*

**Comment by anusuyar** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-:-L0pYdPBrMZFMdy9Ek2G:bnfp4nl)*

**Comment by rocknes** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/list-vapps.py, line 27 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fh8j6TJg5kWkVbO2f:-L0q-lveUTIMtVhwLcP2:bkq82vf) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/examples/list-vapps.py#L27)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

this method maps the `ResourceEntities` section of the OrgVDC XML, other resources are in other sections of the XML and can be retrieved separately
</blockquote></details>

I think we should rename the method list_resources in vdc.py, the current implementation is capable of returning only vapp records.

         if entity_type is None or \
                   entity_type.value == vapp.get('type'):
                    result.append({'name': vapp.get('name')})

---

*[pyvcloud/vcd/org.py, line 95 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0q0KYfBslFBlp7575v:-L0q0KYfBslFBlp7575w:b9jqeey) ([raw file](https://github.com/vmware/pyvcloud/blob/961829fd6602a7379fe7d5b5e219a87c7e49bac4/pyvcloud/vcd/org.py#L95)):*
> ```Python
>                     type=EntityType.RIGHT.value))
>         return self.client.post_linked_resource(
>             org_admin_resource, RelationType.ADD, EntityType.ROLE.value, role)
> ```

Looks like yapf is flip flopping between two formatting (both of which are PRP8 compliant). Maybe we should look into this.

---

*[pyvcloud/vcd/vapp.py, line 319 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fiCkZfRXeB6awTVJD:-L0qEPlC7aCroY_zDOO3:b-dh2nom) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L319)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

this is a helper method that I created for the initial implementation but is no longer used. I will leave it in case it is needed in the future.
</blockquote></details>

It's more of an index out of bound exception :)

---

*[pyvcloud/vcd/vapp.py, line 322 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fl0D_OgDssfzkh5B9:-L0qMxapgNv1dFdHSAX2:b-ilglp3) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L322)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

this method is designed to create a single `sourced_item`. the `add_vms` method below is the one that accepts an array of vm specs. I prefer to keep the name simple because it is later used in methods combined with indexes and other elements and it makes it more readable.
</blockquote></details>

Asking out of curiosity, can this function be used in function instantiate_vapp() in vdc.py? looks very similar.

---

*[pyvcloud/vcd/vapp.py, line 251 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0q2LUcc1_E4Y9QytSo:-L0q2LUcc1_E4Y9QytSp:bukczej) ([raw file](https://github.com/vmware/pyvcloud/blob/961829fd6602a7379fe7d5b5e219a87c7e49bac4/pyvcloud/vcd/vapp.py#L251)):*
> ```Python
>             if vm.get('name') == vm_name:
>                 return vm
>         raise Exception('can\'t find VM %s' % vm_name)
> ```

Capital C in can't ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-:-L0qO8nbmy8j9Gf2KpB5:bnfp4nl)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/list-vapps.py, line 27 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fh8j6TJg5kWkVbO2f:-L0qbp7GmyA4OZd8Et1L:b-eewx22) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/examples/list-vapps.py#L27)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think we should rename the method list_resources in vdc.py, the current implementation is capable of returning only vapp records.

         if entity_type is None or \
                   entity_type.value == vapp.get('type'):
                    result.append({'name': vapp.get('name')})
</blockquote></details>

I created story VCDA-372 to address it

---

*[pyvcloud/vcd/org.py, line 95 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0q0KYfBslFBlp7575v:-L0qcCXdffHQmO_VNOZh:bjdurvb) ([raw file](https://github.com/vmware/pyvcloud/blob/961829fd6602a7379fe7d5b5e219a87c7e49bac4/pyvcloud/vcd/org.py#L95)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Looks like yapf is flip flopping between two formatting (both of which are PRP8 compliant). Maybe we should look into this.
</blockquote></details>

yapf is not yet applied to vcd-cli repo, I created VCDA-373 to address it

---

*[pyvcloud/vcd/vapp.py, line 322 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0fl0D_OgDssfzkh5B9:-L0qdLUL5ZC2Z86wshjm:b-whaxle) ([raw file](https://github.com/vmware/pyvcloud/blob/cbb2b3562bae1e7f48c567dd50a8dfe5d6be5044/pyvcloud/vcd/vapp.py#L322)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Asking out of curiosity, can this function be used in function instantiate_vapp() in vdc.py? looks very similar.
</blockquote></details>

yes, there is task VCDA-355 to refactor instantiate_vapp and reuse it

---

*[pyvcloud/vcd/vapp.py, line 251 at r3](https://reviewable.io:443/reviews/vmware/pyvcloud/151#-L0q2LUcc1_E4Y9QytSo:-L0qd55HVEPSZCFJi413:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/961829fd6602a7379fe7d5b5e219a87c7e49bac4/pyvcloud/vcd/vapp.py#L251)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Capital C in can't ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/151)*

**Pull request merged**
