### PR TITLE
VCDA-635: Implement pyvcloud client to server API version compatibility

### PR DESCRIPTION
**Pull request by hodgesrm**
Adapted Client class to default to highest API version supported by
pyvcloud and negotiation down to a lower certified vCD API version if
necessary.  Restricted pyvcloud certified versions to vCD 8.20 up to
vCD 9.1 (current prod release).  Added method to get client version 
in effect and cleaned up selection of highest server version. 

Implemented client system test to check login and API versioning
behavior, added precise documentation for APIs related to login/logout,
and eliminated client socket leaks due to login failures.  Added new
client system test to stable test list in run_system_tests.sh.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/248)

### CODE REVIEW

**Comment by rocknes** [comment]
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

*[pyvcloud/vcd/client.py, line 385 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOCRQnBVBP1ys4qLqk:-LEOCRQoCa1BVw20PFKV:bob0abq) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/pyvcloud/vcd/client.py#L385)):*
> ```Python
> 
> def _objectify_response(response, as_object=True):
>     """Convert response content to Python type."""
> ```

Python type sounds a bit weird. Should we replace it with lxml.something objects?

---

*[pyvcloud/vcd/client.py, line 629 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOE2M72jVLPtBv0z-0:-LEOE2M72jVLPtBv0z-1:b-divyjn) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/pyvcloud/vcd/client.py#L629)):*
> ```Python
>             and password
>         """
>         # If we need to negotiate the server API level find the highest
> ```

'API level, find' ?

---

*[pyvcloud/vcd/client.py, line 635 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOEX4AC3BaL687N1d8:-LEOEX4B5EOP-vGMhidd:bjf3uc9) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/pyvcloud/vcd/client.py#L635)):*
> ```Python
>             active_versions = self.get_supported_versions_list()
>             self._logger.debug('API versions supported: %s' % active_versions)
>             for version in reversed(active_versions):
> ```

This for loop can be traded for something like

max(set(API_CURRENT_VERSIONS).intersection(active_versions))

---

*[pyvcloud/vcd/client.py, line 723 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOFgo5Atl2gTAgTZDC:-LEOFgo6-7u5TtpoaiLR:bpc0bd3) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/pyvcloud/vcd/client.py#L723)):*
> ```Python
>         result in undefined behavior.
> 
>         :return: Response from successful /DELETE operation or None
> ```

I believe the DELETE call results in 204 no body, we should verify that and update the return type accordingly.

---

*[system_tests/client_tests.py, line 46 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOGMQq4EA56lPH7Exr:-LEOGMQq4EA56lPH7Exs:b-7cfb84) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L46)):*
> ```Python
> 
>     def setUp(self):
>         self._config = Environment._config
> ```

We should avoid accesssing the Environment._config property directly. Rather we should have a getter which takes the key(s) and returns the value.

---

*[system_tests/client_tests.py, line 162 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOHe395RXDzgJJfB6Q:-LEOHe395RXDzgJJfB6R:b-npgbbl) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L162)):*
> ```Python
>         try:
>             self._client.set_credentials(creds)
>             raise Exception("Login succeeded with bad password")
> ```

self.fail(..message..)

---

*[system_tests/client_tests.py, line 178 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOHOMH4EBroTFwLAIz:-LEOHOMH4EBroTFwLAJ-:b-npgbbl) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L178)):*
> ```Python
>                 self._pass)
>             self._client.set_credentials(creds)
>             exception = Exception("Login succeeded with bad host")
> ```

self.fail(..message..)

---

*[system_tests/client_tests.py, line 190 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOGsNz18L2sqjlBqOw:-LEOGsNz18L2sqjlBqOx:b-9bk0o5) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L190)):*
> ```Python
>         """Create client with/without explicit API version."""
>         if api_version is None:
>             return client.Client(
> ```

Isn't the default value of api_version in Client constructor now None?

I think we can get rid of this function.

---

*[system_tests/run_system_tests.sh, line 29 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOG29VD3CYlTzCYg4h:-LEOG29VD3CYlTzCYg4i:beacypt) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/run_system_tests.sh#L29)):*
> ```Shell
> # If there are tests to run use those. Otherwise use stable tests. 
> STABLE_TESTS="client_tests.py \
> idisk_tests.py \
> ```

vapp_tests should be stable too.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/248)*

**Comment by rocknes** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 485 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEWYIZkEg3Yg4zGVR_C:-LEWYIZlCLQhD6P7gA_g:b-w81q6m) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/pyvcloud/vcd/client.py#L485)):*
> ```Python
> 
>     Clients default to the production vCD API version as of the pyvcloud
>     module release and will try to negotiate down to a lower API version
> ```

I think for multi line comments we tab the second line and onwards, e.g.

extension (:obj:`pyvcloud.vcd.Extension`, optional): It holds an
            Extension object to interact with vCD admin extension.

---

*[system_tests/client_tests.py, line 79 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEWZP97Eh9NdoZ9P8pE:-LEWZP97Eh9NdoZ9P8pF:bw08dsw) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L79)):*
> ```Python
>         if client.API_DEFAULT_VERSION != self._client.get_api_version():
>             # Server must be a lower version.
>             self.assertEqual(client_version, server_versions[-1])
> ```

It's better if we use max() function.
I know it's guaranteed that server_versions is always sorted in ascending order, but I guess the intent comes off clearer with max().

---

*[system_tests/client_tests.py, line 112 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEW_svF4Ey7CLRJRjRA:-LEW_svF4Ey7CLRJRjRB:b9ijcd8) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L112)):*
> ```Python
>         try:
>             self._client = self._create_client_with_credentials('99.99')
>             raise Exception("Login succeeded with bad API version")
> ```

self.fail()

---

*[system_tests/client_tests.py, line 145 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEWaGfQA3pPAs5qn89G:-LEWaGfR2JFyuUlX_gde:b9ijcd8) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L145)):*
> ```Python
>         try:
>             self._client.get_org_list()
>             exception = Exception("Org list succeeded after session logout!")
> ```

self.fail()

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/248)*

**Comment by hodgesrm** [comment]
Review status: 2 of 3 files reviewed at latest revision, 13 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 485 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEWYIZkEg3Yg4zGVR_C:-LEWdHUD5HOg8xTJ-URD:b-1vjwoa) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/pyvcloud/vcd/client.py#L485)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think for multi line comments we tab the second line and onwards, e.g.

extension (:obj:`pyvcloud.vcd.Extension`, optional): It holds an
            Extension object to interact with vCD admin extension.
</blockquote></details>

Looks as though indenting the second line of a multi-line class/function comment makes Sphinx go a little crazy. I just checked the effect on the latest fixes in org.py. :( 

With your indulgence.  I'm going to keep this one as is, and we'll need to adjust other comments. 

---

*[pyvcloud/vcd/client.py, line 629 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOE2M72jVLPtBv0z-0:-LEWpenJCWppiwUfSZyV:b-lx4fj3) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/pyvcloud/vcd/client.py#L629)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

'API level, find' ?
</blockquote></details>

Fixed. 

---

*[pyvcloud/vcd/client.py, line 635 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOEX4AC3BaL687N1d8:-LEWpr2B9ecCqH_CYNqV:b-pe8uxz) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/pyvcloud/vcd/client.py#L635)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This for loop can be traded for something like

max(set(API_CURRENT_VERSIONS).intersection(active_versions))
</blockquote></details>

That's a good trick.  However, it turns out that because the versions are strings we can't count on max() working properly.  It would work if they were all floats but using floats for comparison could expose us to weird corner cases if a string conversion to float for some reason returned a non-exact value, e.g., with an value after the decimal point due to floating point imprecision.

---

*[pyvcloud/vcd/client.py, line 723 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOFgo5Atl2gTAgTZDC:-LEWuPow2rmWyYEUiCbq:b5619xp) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/pyvcloud/vcd/client.py#L723)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I believe the DELETE call results in 204 no body, we should verify that and update the return type accordingly.
</blockquote></details>

Body is empty.  Updated accordingly to eliminate return type. 

---

*[system_tests/client_tests.py, line 46 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOGMQq4EA56lPH7Exr:-LEWw5Ie8c7T_ZR2eYhy:busb6cf) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L46)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We should avoid accesssing the Environment._config property directly. Rather we should have a getter which takes the key(s) and returns the value.
</blockquote></details>

Fixed.  

---

*[system_tests/client_tests.py, line 79 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEWZP97Eh9NdoZ9P8pE:-LEWv76O-HCKuW3nfLYO:b-o3ji5u) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L79)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

It's better if we use max() function.
I know it's guaranteed that server_versions is always sorted in ascending order, but I guess the intent comes off clearer with max().
</blockquote></details>

Similar problem as noted above--since values are strings, not floats you can get tripped up by cases like ('6.0', '30.0') in which 6.0 sorts higher.  I thought it was safer to sort the list carefully and then depend on the order. 

I did however eliminate the API_DEFAULT_VERSION which is unnecessary if client API versions are ordered.

---

*[system_tests/client_tests.py, line 112 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEW_svF4Ey7CLRJRjRA:-LEWzID_1niSPJGibmAr:bt2vr1b) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L112)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

self.fail()
</blockquote></details>

Fixed.

---

*[system_tests/client_tests.py, line 145 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEWaGfQA3pPAs5qn89G:-LEWzJ8k07ND856i-B9k:bt2vr1b) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L145)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

self.fail()
</blockquote></details>

Fixed.

---

*[system_tests/client_tests.py, line 162 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOHe395RXDzgJJfB6Q:-LEWzw_XCcFcefVFHxia:bt2vr1b) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L162)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

self.fail(..message..)
</blockquote></details>

Fixed.

---

*[system_tests/client_tests.py, line 178 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOHOMH4EBroTFwLAIz:-LEX-aNF65R__2D1sV6l:b1uu4lj) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L178)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

self.fail(..message..)
</blockquote></details>

self.fail() throws an exception which is problematic in this case, since we expect an exception from trying to use the old connection. 

---

*[system_tests/client_tests.py, line 190 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOGsNz18L2sqjlBqOw:-LEX-tOS2JVH4dQg01gV:bown02t) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L190)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Isn't the default value of api_version in Client constructor now None?

I think we can get rid of this function.
</blockquote></details>

Actually we're doing something a bit different here--the code is deciding whether to create a client that auto-negotiates.  Clarified with a comment (or 2 or 3) since it was obviously not clear. :)

---

*[system_tests/run_system_tests.sh, line 29 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOG29VD3CYlTzCYg4h:-LEX3-8P6Abu-u7fTPRU:bmcvcok) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/run_system_tests.sh#L29)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

vapp_tests should be stable too.
</blockquote></details>

Added catalog_tests.py and vapp_tests.py. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/248)*

**Comment by rocknes** [comment]
Reviewed 4 of 5 files at r2.
Review status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @rocknes, @hodgesrm, and @sahithi)

---

*[pyvcloud/system_test_framework/base_test.py, line 3 at r2](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEjvpm0-igoWLqvk1SB:-LEjvpm11-o396VMiedq:b-3opr38) ([raw file](https://github.com/vmware/pyvcloud/blob/8ee16fd43a0f7dc8e5addd5978be7c547cac66ff/pyvcloud/system_test_framework/base_test.py#L3)):*
> ```Python
> # VMware vCloud Director Python SDK
> # Copyright (c) 2018 VMware, Inc. All Rights Reserved.
> #
> ```

Thanks for adding the license files :)

---

*[pyvcloud/vcd/client.py, line 635 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOEX4AC3BaL687N1d8:-LEjweBrAT40uEcQfVqw:b-5qzfov) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/pyvcloud/vcd/client.py#L635)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

That's a good trick.  However, it turns out that because the versions are strings we can't count on max() working properly.  It would work if they were all floats but using floats for comparison could expose us to weird corner cases if a string conversion to float for some reason returned a non-exact value, e.g., with an value after the decimal point due to floating point imprecision.
</blockquote></details>

https://stackoverflow.com/questions/2574080/sorting-a-list-of-dot-separated-numbers-like-software-versions

distutils.version - seems this problem has been solved already :)

---

*[system_tests/client_tests.py, line 79 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEWZP97Eh9NdoZ9P8pE:-LEjxQ3qCM0hfoZ1FHBS:b-rmf9x7) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L79)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Similar problem as noted above--since values are strings, not floats you can get tripped up by cases like ('6.0', '30.0') in which 6.0 sorts higher.  I thought it was safer to sort the list carefully and then depend on the order. 

I did however eliminate the API_DEFAULT_VERSION which is unnecessary if client API versions are ordered.
</blockquote></details>

distutils.version ? Please look at my other comment above.

---

*[system_tests/client_tests.py, line 162 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOHe395RXDzgJJfB6Q:-LEjyTne9Gs4Y8DWEolU:bn3lyi9) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L162)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Umm I still see an exception being raised :|

---

*[system_tests/client_tests.py, line 178 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOHOMH4EBroTFwLAIz:-LEjyeRf5NDdYGQkKr_G:by7xgtx) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L178)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

self.fail() throws an exception which is problematic in this case, since we expect an exception from trying to use the old connection. 
</blockquote></details>

In that case, just as I suggested in the previous comment, we should use a bool to track that the code has reached an undesired section of code and make an assert on that bool at the end of the test.

---

*[system_tests/client_tests.py, line 154 at r2](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEjxx17AYYayYep4uOQ:-LEjxx17AYYayYep4uOR:bc5gdlm) ([raw file](https://github.com/vmware/pyvcloud/blob/8ee16fd43a0f7dc8e5addd5978be7c547cac66ff/system_tests/client_tests.py#L154)):*
> ```Python
>                 exc_info=True)
> 
>         if exception is not None:
> ```

Since we can't use self.fail() in the try-except block.
We should do a self.assertIsNone(exception, msg) instead of raising the exception manually.

Even better we can set a boolean in case we are able to do a successful login with a logged out client and test the boolean at the end of the test to raise an assertion error.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/248)*

**Comment by rocknes** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed, 8 unresolved discussions (waiting on @rocknes, @hodgesrm, and @sahithi)

---

*[pyvcloud/system_test_framework/environment.py, line 100 at r3](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEuB_ip-zwxN1E9OxMT:-LEuB_iq88pYENMfYFIc:bphjkup) ([raw file](https://github.com/vmware/pyvcloud/blob/6aa143ea75e2e97db0dd1ac44619e76469167a25/pyvcloud/system_test_framework/environment.py#L100)):*
> ```Python
>         """Get test configuration parameter dictionary.
> 
>         :return: A dict containing configuration information
> ```

missing "rtype:

---

*[pyvcloud/vcd/client.py, line 394 at r3](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEuBeSlEqRtPm2oqazn:-LEuBeSlEqRtPm2oqazo:b-ombk0e) ([raw file](https://github.com/vmware/pyvcloud/blob/6aa143ea75e2e97db0dd1ac44619e76469167a25/pyvcloud/vcd/client.py#L394)):*
> ```Python
>         lxml.objectify.ObjectifiedElement where XML properties look like
>         Python object attributes.
>     :return: lxml.objectify.ObjectifiedElement or root of parsed XML
> ```

sphinx raises a warning if we don't separate param section and return section by a blank line

missing :rtype: field

Btw please don't forget to space out :return: and :rtype: with a blank line

---

*[pyvcloud/vcd/client.py, line 458 at r3](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEuBvm10SCU38W1B84U:-LEuBvm10SCU38W1B84V:b-1o9t85) ([raw file](https://github.com/vmware/pyvcloud/blob/6aa143ea75e2e97db0dd1ac44619e76469167a25/pyvcloud/vcd/client.py#L458)):*
> ```Python
>             status.
>         :return: Task we were waiting for
>         :rtype Task:
> ```

blank line between last :param:, :return: , :rtype: and :raises: sections respectively

---

*[pyvcloud/vcd/client.py, line 494 at r3](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEuCbVc-fe1rdtdkru3:-LEuCbVd2ycUJ3agXFUN:b-s4tyqy) ([raw file](https://github.com/vmware/pyvcloud/blob/6aa143ea75e2e97db0dd1ac44619e76469167a25/pyvcloud/vcd/client.py#L494)):*
> ```Python
> 
> class Client(object):
>     """A low-level interface to the vCloud Director REST API.
> ```

General comment:

1. There should be a blank line betwen different sections viz.
```:param: , :return:, :rtype:, :raises:```

2. the first character after
```:param:, :return:, :raises:, etc.```
should be lower cased unless we are referencing to class/objects
```


---

*[pyvcloud/vcd/client.py, line 589 at r3](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEuC5uZECqAB5XeClzQ:-LEuC5uZECqAB5XeClzR:bydnjf) ([raw file](https://github.com/vmware/pyvcloud/blob/6aa143ea75e2e97db0dd1ac44619e76469167a25/pyvcloud/vcd/client.py#L589)):*
> ```Python
> 
>         :return: List of versions sorted in numerical order
>         :rtype: list of str
> ```

Blank line missing

---

*[pyvcloud/vcd/client.py, line 1054 at r3](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEuCvtx-5Cxhicx9dEG:-LEuCvtx-5Cxhicx9dEH:b2nicjw) ([raw file](https://github.com/vmware/pyvcloud/blob/6aa143ea75e2e97db0dd1ac44619e76469167a25/pyvcloud/vcd/client.py#L1054)):*
> ```Python
>         """Retrieve an organization.
> 
>         :param string org_name: name of the org to be retrieved.
> ```

str

---

*[pyvcloud/vcd/client.py, line 1153 at r3](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEuD1QKB3FSzjquUz8U:-LEuD1QKB3FSzjquUz8V:bwfi9y8) ([raw file](https://github.com/vmware/pyvcloud/blob/6aa143ea75e2e97db0dd1ac44619e76469167a25/pyvcloud/vcd/client.py#L1153)):*
> ```Python
>     """Returns the link of the specified rel and type in the resource.
> 
>     :param resource: the resource with the link
> ```

types are missing.

---

*[system_tests/client_tests.py, line 190 at r1](https://reviewable.io/reviews/vmware/pyvcloud/248#-LEOGsNz18L2sqjlBqOw:-LEuDO9DEz18ehdH3sK-:b-yafcfq) ([raw file](https://github.com/vmware/pyvcloud/blob/7b33a7168627dd1aa85cf51d37672ea72cab78f0/system_tests/client_tests.py#L190)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Actually we're doing something a bit different here--the code is deciding whether to create a client that auto-negotiates.  Clarified with a comment (or 2 or 3) since it was obviously not clear. :)
</blockquote></details>

What I meant is that the call 
client.Client(self._host, verify_ssl_certs=False) 
is equivalent to 
self.client.Client(slef._host, api_version=None, verify_ssl_certs=False)

or to say 
api_version=None
self.client.Client(slef._host, api_version=api_version, verify_ssl_certs=False)

so the 'if' block here is redundant. And if the 'if' block is redundant then this whole function can be inlined.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/248#-:-LEuE28qDCFUlUajn4RH:bnfp4nl)*
<!-- Sent from Reviewable.io -->

**Pull request merged**
