### PR TITLE
Refactor Pyvcloud to use the new exception classes

### PR DESCRIPTION
**Pull request by anusuyar**
Refactored the pyvlcoud codebase to use the newly created Exception class hierarchy.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/231)

### CODE REVIEW

**Comment by sahithi** [comment]
Just skimmed through the review and made few comments. Please get other reviewers to take a thorough look.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pyvcloud/vcd/client.py, line 309 at r1](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAFrZBL6JN7SdULcU_t:-LAFrZBL6JN7SdULcU_u:bibutu5) ([raw file](https://github.com/vmware/pyvcloud/blob/3f2205841e39fe803358f5755d36877675ecf1b8/pyvcloud/vcd/client.py#L309)):*
> ```Python
> 
> 
> class MultipleLinksException(LinkException):
> ```

Code in few places still has references to these deleted exceptions?

---

*[pyvcloud/vcd/client.py, line 775 at r1](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAFrDIgB6e2JpxR2Rup:-LAFrDIgB6e2JpxR2Ruq:blsbljl) ([raw file](https://github.com/vmware/pyvcloud/blob/94ad71cf5f1d659233e51fdfffdbd5bd0ff053df/pyvcloud/vcd/client.py#L775)):*
> ```Python
>             return self.put_resource(
>                 find_link(resource, rel, media_type).href, contents, media_type)
>         except MissingLinkException as e:
> ```

Are we not getting rid of MissingLinkException and other similar existing exceptions?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-:-LAFrlCT-GByn_oAAKxB:bxish0x)*

**Comment by anusuyar** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pyvcloud/vcd/client.py, line 309 at r1](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAFrZBL6JN7SdULcU_t:-LAFsYe14YS6LEh_C7Mc:bd212ik) ([raw file](https://github.com/vmware/pyvcloud/blob/3f2205841e39fe803358f5755d36877675ecf1b8/pyvcloud/vcd/client.py#L309)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Code in few places still has references to these deleted exceptions?
</blockquote></details>

LinkExceptions is not eliminated. Its just confined within pyvcloud.  find_link() will still throw MissingLinkException. But it will be re-thrown as OperationNotSupportedException to the client.

---

*[pyvcloud/vcd/client.py, line 775 at r1](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAFrDIgB6e2JpxR2Rup:-LAFsEU413mBXNROqrsC:bd212ik) ([raw file](https://github.com/vmware/pyvcloud/blob/94ad71cf5f1d659233e51fdfffdbd5bd0ff053df/pyvcloud/vcd/client.py#L775)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Are we not getting rid of MissingLinkException and other similar existing exceptions?
</blockquote></details>

LinkExceptions is not eliminated. Its just confined within pyvcloud.  find_link() will still throw MissingLinkException. But it will be re-thrown as OperationNotSupportedException to the client.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/231)*

**Comment by hodgesrm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAG-Wno3uQ6vTQLMxVl:-LAG-Wno3uQ6vTQLMxVm:btbhhba) (no related file):*
Pull request code is currently getting flake8 errors in the Travis build.  Please correct these.  

---

*[pyvcloud/vcd/client.py, line 584 at r1](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAG054N1s_B38eWBgLP:-LAG054N1s_B38eWBgLQ:b-y8uzv1) ([raw file](https://github.com/vmware/pyvcloud/blob/94ad71cf5f1d659233e51fdfffdbd5bd0ff053df/pyvcloud/vcd/client.py#L584)):*
> ```Python
> 
>         print("inside do request %s" ,sc)
> ```

Unexpected print statement here and in locations below this line.  Please remove. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/231)*

**Comment by hodgesrm** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/231)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 584 at r1](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAG054N1s_B38eWBgLP:-LAQVvpV3ODq4Z5Wj7pd:b-y3gow8) ([raw file](https://github.com/vmware/pyvcloud/blob/94ad71cf5f1d659233e51fdfffdbd5bd0ff053df/pyvcloud/vcd/client.py#L584)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Unexpected print statement here and in locations below this line.  Please remove. 
</blockquote></details>

Looks good.  Thanks!

---

*[pyvcloud/vcd/client.py, line 38 at r2](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAQVQCM2zfhRj2itQy7:-LAQVQCN1JG4sxfFkpKT:b9fllrr) ([raw file](https://github.com/vmware/pyvcloud/blob/8bc80b64ab7cf96e77ac21309243261225b97e5e/pyvcloud/vcd/client.py#L38)):*
> ```Python
>     TaskTimeoutException, UnauthorizedException, UnknownApiException, \
>     UnsupportedMediaTypeException, VcdException, VcdResponseException, \
>     VcdTaskException  # NOQA
> ```

I think you should be able to drop NOQA, no?  This looks flake8 compatible. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-:-LAQW5ug8vcNEo_4SkRV:bnfp4nl)*

**Comment by sahithi** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 512 at r3](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAUPN4lC53W29JRWPTm:-LAUPN4lC53W29JRWPTn:bek6j9x) ([raw file](https://github.com/vmware/pyvcloud/blob/42dfc202caff40fb29d9bcf706652abc57c1111d/pyvcloud/vcd/client.py#L512)):*
> ```Python
>             except Exception:
>                 pass
>             raise VcdResponseException(
> ```

Isn't this supposed to be AuthenticationException chained with VcdResponseException?
Have you tested this? Can you paste the output of the exception here?

---

*[pyvcloud/vcd/client.py, line 815 at r3](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAUQDOUCc176Hvqll2M:-LAUQDOUCc176Hvqll2N:b-qzdk3p) ([raw file](https://github.com/vmware/pyvcloud/blob/42dfc202caff40fb29d9bcf706652abc57c1111d/pyvcloud/vcd/client.py#L815)):*
> ```Python
>         except MissingLinkException as e:
>             raise OperationNotSupportedException(
>                 "Operation is not supported").with_traceback(e.__traceback__)
> ```

Please paste the exception output here for reviewers reference.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/231)*

**Comment by anusuyar** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 815 at r3](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAUQDOUCc176Hvqll2M:-LAUT9Tc9RUZIMZArqcY:b-zhupxo) ([raw file](https://github.com/vmware/pyvcloud/blob/42dfc202caff40fb29d9bcf706652abc57c1111d/pyvcloud/vcd/client.py#L815)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please paste the exception output here for reviewers reference.
</blockquote></details>

```
File "c:\sources\github\service_ecosystem\vcd-cli\vcd_cli\vdc.py", line 461, in list_acl
    acl = vdc.get_access_settings()
  File "c:\sources\github\service_ecosystem\pyvcloud\pyvcloud\vcd\vdc.py", line 695, in get_access_settings
    return acl.get_access_settings()
  File "c:\sources\github\service_ecosystem\pyvcloud\pyvcloud\vcd\acl.py", line 77, in get_access_settings
    return self.get_resource()
  File "c:\sources\github\service_ecosystem\pyvcloud\pyvcloud\vcd\acl.py", line 45, in get_resource
    EntityType.CONTROL_ACCESS_PARAMS.value)
  File "c:\sources\github\service_ecosystem\pyvcloud\pyvcloud\vcd\client.py", line 834, in get_linked_resource
    "supported").with_traceback(e.__traceback__) from e
  File "c:\sources\github\service_ecosystem\pyvcloud\pyvcloud\vcd\client.py", line 831, in get_linked_resource
    return self.get_resource(find_link(resource, rel, media_type).href)
  File "c:\sources\github\service_ecosystem\pyvcloud\pyvcloud\vcd\client.py", line 978, in find_link
    raise MissingLinkException(resource.get('href'), rel, media_type)
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/231)*

**Comment by hodgesrm** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/231)*

**Comment by anusuyar** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 38 at r2](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAQVQCM2zfhRj2itQy7:-LAoQfXh0v7h9PNxMFKP:bf7pwfi) ([raw file](https://github.com/vmware/pyvcloud/blob/8bc80b64ab7cf96e77ac21309243261225b97e5e/pyvcloud/vcd/client.py#L38)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

I think you should be able to drop NOQA, no?  This looks flake8 compatible. 
</blockquote></details>

NO, it complains that it should be in separate lines.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/231)*

**Comment by anusuyar** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 815 at r3](https://beta.reviewable.io/reviews/vmware/pyvcloud/231#-LAUQDOUCc176Hvqll2M:-LAoZcga5QqQix4K9H16:b-e9gl7f) ([raw file](https://github.com/vmware/pyvcloud/blob/42dfc202caff40fb29d9bcf706652abc57c1111d/pyvcloud/vcd/client.py#L815)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

```
File "c:\sources\github\service_ecosystem\vcd-cli\vcd_cli\vdc.py", line 461, in list_acl
    acl = vdc.get_access_settings()
  File "c:\sources\github\service_ecosystem\pyvcloud\pyvcloud\vcd\vdc.py", line 695, in get_access_settings
    return acl.get_access_settings()
  File "c:\sources\github\service_ecosystem\pyvcloud\pyvcloud\vcd\acl.py", line 77, in get_access_settings
    return self.get_resource()
  File "c:\sources\github\service_ecosystem\pyvcloud\pyvcloud\vcd\acl.py", line 45, in get_resource
    EntityType.CONTROL_ACCESS_PARAMS.value)
  File "c:\sources\github\service_ecosystem\pyvcloud\pyvcloud\vcd\client.py", line 834, in get_linked_resource
    "supported").with_traceback(e.__traceback__) from e
  File "c:\sources\github\service_ecosystem\pyvcloud\pyvcloud\vcd\client.py", line 831, in get_linked_resource
    return self.get_resource(find_link(resource, rel, media_type).href)
  File "c:\sources\github\service_ecosystem\pyvcloud\pyvcloud\vcd\client.py", line 978, in find_link
    raise MissingLinkException(resource.get('href'), rel, media_type)
```
</blockquote></details>


```
C:\sources\github\service_ecosystem\vcd-cli (master) 
(vcd-cli) λ vcd vdc acl list DevelopmentOrgVdc
Usage: vcd vdc acl list [OPTIONS] <vdc-name>

Error: Operation is not supported

C:\sources\github\service_ecosystem\vcd-cli (master) 
(vcd-cli) λ 

```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/231)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/231#-:-LAp8S4R855BMLIn5vCx:bnfp4nl)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/231#-:-LBNfJ8Q32rAx48vJxBg:bnfp4nl)*

**Pull request merged**
