### PR TITLE
VCDA-474: consider name and namespace in api extension

### PR DESCRIPTION
**Pull request by pacogomez**
- api extension operation now consider both name and namespace
- added unit tests
- minor re-format in VApp class

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/201)

### CODE REVIEW

**Comment by anusuyar** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/api_extension.py, line 135 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/201#-L4d9FDtqnfuvloKP0-g:-L4d9FDtqnfuvloKP0-h:b-i058u2) ([raw file](https://github.com/vmware/pyvcloud/blob/f725e267b4cab47fe16ec0df1630698800ac0773/pyvcloud/vcd/api_extension.py#L135)):*
>  qfilter='name==%s;namespace==%s' % (name, ns),

consider a tertiary operator here as below. We can avoid the 
```python
 qfilter='name==%s;namespace==%s' % (name, namespace if namespace else name),
```

if that case we can avoid the following if else statement

```python
    if namespace is None:
            ns = name
        else:
            ns = namespace
```

having a temp variable ns looks confusing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/201)*

**Comment by pacogomez** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/api_extension.py, line 135 at r1](https://beta.reviewable.io/reviews/vmware/pyvcloud/201#-L4d9FDtqnfuvloKP0-g:-L4dDuth8EG0OvzruXRW:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/f725e267b4cab47fe16ec0df1630698800ac0773/pyvcloud/vcd/api_extension.py#L135)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

>  qfilter='name==%s;namespace==%s' % (name, ns),

consider a tertiary operator here as below. We can avoid the 
```python
 qfilter='name==%s;namespace==%s' % (name, namespace if namespace else name),
```

if that case we can avoid the following if else statement

```python
    if namespace is None:
            ns = name
        else:
            ns = namespace
```

having a temp variable ns looks confusing.

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/201)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/pyvcloud/201#-:-L4dFsnt0dAPcYlZ6MSI:bnfp4nl)*

**Comment by sahithi** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/201#-:-L4hPlJVx-N5CcOqQopa:bnfp4nl)*

**Pull request merged**
