### PR TITLE
VCDA-248 error handling on invalid session

### PR DESCRIPTION
**Pull request by pacogomez**
- more informative message when error is due to invalid session
- fix VCDA-399 show VDC info
- fixed errors due to insufficient access
- memory capacity in human format

These changes are to display more informative messages to users, no new functionality has been added and existing unit tests still apply.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/172)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/172)*

**Comment by sahithi** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pyvcloud/vcd/client.py, line 285 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/172#-L30IYkBHRp5-HVKFEuD:-L30IYkCI9NIEc9ATYYU:bvkxyp2) ([raw file](https://github.com/vmware/pyvcloud/blob/05cd46432e5cd62a589c7c929e1aeae83117522f/pyvcloud/vcd/client.py#L285)):*
> ```Python
> class MissingLinkException(LinkException):
>     def __init__(self, href, rel, media_type):
>         super(MissingLinkException, self).__init__(href, rel, media_type)
> ```

Can we add _str_() for all exceptions emerging from vcd-cli and pyvcloud as well? I was going to do this as part of my next review, but this changeset is more apt to track this.

For example:
    def __str__(self):
        return 'MissingLinkException; ' + \
               super(MissingLinkException, self).__str__()

Currently, it is very hard for users to decipher exceptions thrown from vcd-cli/pyvcloud. Below is the exception that makes no sense to the user. I debugged a bit to find that this is MissingLinkException (user doesnt have enough privileges). 

*Before*: 'https://127.0.0.1:8443/api/vApp/vapp-09490763-e6c6-4c11-a062-8f7784e50df5', <EnumValue: RelationType.DOWN [value=down]>, 'application/vnd.vmware.vcloud.metadata+xml'); href: https://127.0.0.1:8443/api/vApp/vapp-09490763-e6c6-4c11-a062-8f7784e50df5, rel: RelationType.DOWN, mediaType: application/vnd.vmware.vcloud.metadata+xml

*After*: MissingLinkException; ('https://127.0.0.1:8443/api/vApp/vapp-09490763-e6c6-4c11-a062-8f7784e50df5', <EnumValue: RelationType.DOWN [value=down]>, 'application/vnd.vmware.vcloud.metadata+xml'); href: https://127.0.0.1:8443/api/vApp/vapp-09490763-e6c6-4c11-a062-8f7784e50df5, rel: RelationType.DOWN, mediaType: application/vnd.vmware.vcloud.metadata+xml

Later exception can lead user to the thought process of "probably user is less pivileged .. so on"

Feel free to change the naming.

---

*[pyvcloud/vcd/client.py, line 636 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/172#-L30Lk8o7HCbDAUmvT6I:-L30Lk8o7HCbDAUmvT6J:b-luw5i9) ([raw file](https://github.com/vmware/pyvcloud/blob/05cd46432e5cd62a589c7c929e1aeae83117522f/pyvcloud/vcd/client.py#L636)):*
>  if 400 <= sc <= 499:
>             raise VcdErrorResponseException(
>                 sc, self._get_response_request_id(response),
>                 _objectify_response(response, objectify_results))
>  
>         if sc == 500:
>             raise VcdErrorResponseException(
>                 sc, self._get_response_request_id(response),

Can we do below?
if 400 <= sc <= 500
        raise VcdErrorResponseException

If you think separate blocks are necessary for any future reason, I suggest classifying BadRequestException and InternalServerException as sub-classes of VcdErrorResponseException and throw the appropriate one..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/172)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/client.py, line 285 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/172#-L30IYkBHRp5-HVKFEuD:-L30VAQ-fTNCjiS8XO8d:bb4keh4) ([raw file](https://github.com/vmware/pyvcloud/blob/05cd46432e5cd62a589c7c929e1aeae83117522f/pyvcloud/vcd/client.py#L285)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can we add _str_() for all exceptions emerging from vcd-cli and pyvcloud as well? I was going to do this as part of my next review, but this changeset is more apt to track this.

For example:
    def __str__(self):
        return 'MissingLinkException; ' + \
               super(MissingLinkException, self).__str__()

Currently, it is very hard for users to decipher exceptions thrown from vcd-cli/pyvcloud. Below is the exception that makes no sense to the user. I debugged a bit to find that this is MissingLinkException (user doesnt have enough privileges). 

*Before*: 'https://127.0.0.1:8443/api/vApp/vapp-09490763-e6c6-4c11-a062-8f7784e50df5', <EnumValue: RelationType.DOWN [value=down]>, 'application/vnd.vmware.vcloud.metadata+xml'); href: https://127.0.0.1:8443/api/vApp/vapp-09490763-e6c6-4c11-a062-8f7784e50df5, rel: RelationType.DOWN, mediaType: application/vnd.vmware.vcloud.metadata+xml

*After*: MissingLinkException; ('https://127.0.0.1:8443/api/vApp/vapp-09490763-e6c6-4c11-a062-8f7784e50df5', <EnumValue: RelationType.DOWN [value=down]>, 'application/vnd.vmware.vcloud.metadata+xml'); href: https://127.0.0.1:8443/api/vApp/vapp-09490763-e6c6-4c11-a062-8f7784e50df5, rel: RelationType.DOWN, mediaType: application/vnd.vmware.vcloud.metadata+xml

Later exception can lead user to the thought process of "probably user is less pivileged .. so on"

Feel free to change the naming.

</blockquote></details>

the exceptions have fields that can be used in upper layers, if we just convert to str we lose the information of those fields and can't provide meaningful messages based on that (see corresponding vcd-cli code)

---

*[pyvcloud/vcd/client.py, line 636 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/172#-L30Lk8o7HCbDAUmvT6I:-L30VcviIS-db_Lvwqsg:bg8pvfa) ([raw file](https://github.com/vmware/pyvcloud/blob/05cd46432e5cd62a589c7c929e1aeae83117522f/pyvcloud/vcd/client.py#L636)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

>  if 400 <= sc <= 499:
>             raise VcdErrorResponseException(
>                 sc, self._get_response_request_id(response),
>                 _objectify_response(response, objectify_results))
>  
>         if sc == 500:
>             raise VcdErrorResponseException(
>                 sc, self._get_response_request_id(response),

Can we do below?
if 400 <= sc <= 500
        raise VcdErrorResponseException

If you think separate blocks are necessary for any future reason, I suggest classifying BadRequestException and InternalServerException as sub-classes of VcdErrorResponseException and throw the appropriate one..

</blockquote></details>

I want to keep 500 separate from the original block 400-499

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/172)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/172#-:-L34Kibt4V1PgmvwCo_0:bnfp4nl)*

**Comment by sahithi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/client.py, line 285 at r1](https://reviewable.io:443/reviews/vmware/pyvcloud/172#-L30IYkBHRp5-HVKFEuD:-L34NFYDBhpP7M5udV-2:bkz7lkl) ([raw file](https://github.com/vmware/pyvcloud/blob/05cd46432e5cd62a589c7c929e1aeae83117522f/pyvcloud/vcd/client.py#L285)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

the exceptions have fields that can be used in upper layers, if we just convert to str we lose the information of those fields and can't provide meaningful messages based on that (see corresponding vcd-cli code)
</blockquote></details>

Sure, leaving aside implementation detail, my focus was more on the need to convey meaningful error message to the user, which can help him troubleshoot or root-cause the error.
We can tackle this as part of a separate task 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/pyvcloud/172#-:-L34NqJrkHdIT2wH0AFz:bnfp4nl)*

**Pull request merged**
