### PR TITLE
[VCDA-606] Add NSX-T manager name optional parameter to create PVDC

### PR DESCRIPTION
**Pull request by ckolovson**
- Add NSX-T manager name optional parameter to create PVDC

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pyvcloud/vcd/platform.py, line 100 at r1](https://reviewable.io/reviews/vmware/pyvcloud/235#-LB3bWKi29zVR3wVFdyR:-LB3bWKj-d51aH6is5TJ:b7coa2w) ([raw file](https://github.com/vmware/pyvcloud/blob/704357f2990fde3b8043a3101143967a22ea597e/pyvcloud/vcd/platform.py#L100)):*
> ```
> get_vxlan_network_pool
> ```
This change removes a call from the API which may or may not be used by clients.  We should retain the function so that the client API surface remains identical but call get_obj_by_name() underneath.  Otherwise there's a possibility you'll break clients.  

---

*[pyvcloud/vcd/platform.py, line 195 at r1](https://reviewable.io/reviews/vmware/pyvcloud/235#-LB3c6pU9uidjpFfPBeb:-LB3c6pV9K6sjg4tagzN:baxp4d8) ([raw file](https://github.com/vmware/pyvcloud/blob/90f6e799f3a127c0efb8ceda55914bed28c4fd26/pyvcloud/vcd/platform.py#L195)):*
> ```Python
>             vmw_prov_vdc_params.append(E_VMEXT.VxlanNetworkPool(
>                 href=vx_href))
>         if nsxt_manager_name is not None:
> ```

Does this new logic change nsx-v support in any way?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235)*

**Comment by ckolovson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pyvcloud/vcd/platform.py, line 100 at r1](https://reviewable.io/reviews/vmware/pyvcloud/235#-LB3bWKi29zVR3wVFdyR:-LB3chs57K_6Owy0Z5-M:b-r3ghri) ([raw file](https://github.com/vmware/pyvcloud/blob/704357f2990fde3b8043a3101143967a22ea597e/pyvcloud/vcd/platform.py#L100)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

> ```
> get_vxlan_network_pool
> ```
This change removes a call from the API which may or may not be used by clients.  We should retain the function so that the client API surface remains identical but call get_obj_by_name() underneath.  Otherwise there's a possibility you'll break clients.  
</blockquote></details>

Perhaps, but I recently introduced the old helper function and I'd be very surprised if anyone else is using it. This is a case of code restructuring. Strictly speaking you're right, but I'm not sure if restoring the old function (even as a wrapper) is worthwhile. 

---

*[pyvcloud/vcd/platform.py, line 195 at r1](https://reviewable.io/reviews/vmware/pyvcloud/235#-LB3c6pU9uidjpFfPBeb:-LB3d2Zq5jd-wOwC3MP7:bx6omyh) ([raw file](https://github.com/vmware/pyvcloud/blob/90f6e799f3a127c0efb8ceda55914bed28c4fd26/pyvcloud/vcd/platform.py#L195)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Does this new logic change nsx-v support in any way?
</blockquote></details>

No, it's an alternative. People can use nsx-v or nsx-t, but not both simultaneously. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235)*

**Comment by hodgesrm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pyvcloud/vcd/platform.py, line 100 at r1](https://reviewable.io/reviews/vmware/pyvcloud/235#-LB3bWKi29zVR3wVFdyR:-LB3kDQM2n4D9KLB3GW7:byze9iz) ([raw file](https://github.com/vmware/pyvcloud/blob/704357f2990fde3b8043a3101143967a22ea597e/pyvcloud/vcd/platform.py#L100)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

Perhaps, but I recently introduced the old helper function and I'd be very surprised if anyone else is using it. This is a case of code restructuring. Strictly speaking you're right, but I'm not sure if restoring the old function (even as a wrapper) is worthwhile. 
</blockquote></details>

It seems to have entered the API in commit 87d8327323bba77298ea0458483729fa328cbb4f on 14 February.  We need to be disciplined about what's in the public API.  I suggest you leave it in and mark it as deprecated by adding [Deprecated] to the front of the docstring.  We can then remove it in a future version.  

Python has a convention for marking deprecated functions using the 'warnings' module (see https://docs.python.org/3/library/warnings.html).  However I don't really like the idea of things appearing on stderr in a library that's supposed to underly other services.  Open to other opinions on this. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235)*

**Comment by ckolovson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pyvcloud/vcd/platform.py, line 100 at r1](https://reviewable.io/reviews/vmware/pyvcloud/235#-LB3bWKi29zVR3wVFdyR:-LB3n7Ia7WDJZz6j03IR:b-emx8l0) ([raw file](https://github.com/vmware/pyvcloud/blob/704357f2990fde3b8043a3101143967a22ea597e/pyvcloud/vcd/platform.py#L100)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

It seems to have entered the API in commit 87d8327323bba77298ea0458483729fa328cbb4f on 14 February.  We need to be disciplined about what's in the public API.  I suggest you leave it in and mark it as deprecated by adding [Deprecated] to the front of the docstring.  We can then remove it in a future version.  

Python has a convention for marking deprecated functions using the 'warnings' module (see https://docs.python.org/3/library/warnings.html).  However I don't really like the idea of things appearing on stderr in a library that's supposed to underly other services.  Open to other opinions on this. 
</blockquote></details>

Ok. Seems like overkill but ok. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235)*

**Comment by ckolovson** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/platform.py, line 100 at r1](https://reviewable.io/reviews/vmware/pyvcloud/235#-LB3bWKi29zVR3wVFdyR:-LBNb3fg-p_1Lc4i0Tqy:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/704357f2990fde3b8043a3101143967a22ea597e/pyvcloud/vcd/platform.py#L100)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

Ok. Seems like overkill but ok. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235#-:-LBNeooW2xBvswkxOQPZ:bnfp4nl)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pyvcloud/vcd/platform.py, line 127 at r2](https://reviewable.io/reviews/vmware/pyvcloud/235#-LBWgwjRBMllkz2MUrSm:-LBWgwjRBMllkz2MUrSn:b-kyc48f) ([raw file](https://github.com/vmware/pyvcloud/blob/8cbbe6d3c4d607a14fec41b570e45df8f3c85a43/pyvcloud/vcd/platform.py#L127)):*
> ```Python
>         """Fetch an object by its name.
> 
>         :param: obj_type (str): type of the object.
> ```

This is too wild west-y. We should have an enum class which will contain all the object types in it. I am sure vCD can only fetch a handful of object types, so leaving this field open for all values is going to cause unnecessary confusion and headaches.

Please take a look at how we use rel type in  post_linked_resource()

---

*[pyvcloud/vcd/platform.py, line 132 at r2](https://reviewable.io/reviews/vmware/pyvcloud/235#-LBWiGdq-6dSLPVrquGG:-LBWiGdq-6dSLPVrquGH:b-p1lplx) ([raw file](https://github.com/vmware/pyvcloud/blob/8cbbe6d3c4d607a14fec41b570e45df8f3c85a43/pyvcloud/vcd/platform.py#L132)):*
> ```Python
>         :raises: Exception: if the named object cannot be found.
>         """
>         query_filter = 'name==%s' % urllib.parse.quote_plus(obj_name)
> ```

Does this take care of url encoding? e.g. does it change characters like /,?etc to something like %E5% etc.

---

*[pyvcloud/vcd/platform.py, line 214 at r2](https://reviewable.io/reviews/vmware/pyvcloud/235#-LBWgkQ75cLbvjVkua-y:-LBWgkQ75cLbvjVkua-z:b-mby6lj) ([raw file](https://github.com/vmware/pyvcloud/blob/8cbbe6d3c4d607a14fec41b570e45df8f3c85a43/pyvcloud/vcd/platform.py#L214)):*
> ```Python
>         vmw_prov_vdc_params.append(E_VMEXT.VimServer(href=vc_href))
>         if vxlan_network_pool is not None:
>             network_pool_record = self.get_obj_by_name('networkPool',
> ```

We shouldn't be hard coding values like this. It will be better if we have an enum class which contains all the valid values.

---

*[pyvcloud/vcd/platform.py, line 220 at r2](https://reviewable.io/reviews/vmware/pyvcloud/235#-LBWhf4W5M6dvowr2_cW:-LBWhf4W5M6dvowr2_cX:bz7icgm) ([raw file](https://github.com/vmware/pyvcloud/blob/8cbbe6d3c4d607a14fec41b570e45df8f3c85a43/pyvcloud/vcd/platform.py#L220)):*
> ```Python
>                 href=vx_href))
>         if nsxt_manager_name is not None:
>             nsxt_manager_record = self.get_obj_by_name('nsxTManager',
> ```

We shouldn't be hard coding these values.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235)*

**Comment by ckolovson** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/platform.py, line 132 at r2](https://reviewable.io/reviews/vmware/pyvcloud/235#-LBWiGdq-6dSLPVrquGG:-LBWo7nM97dxEHG4v_xx:b-d8u8qr) ([raw file](https://github.com/vmware/pyvcloud/blob/8cbbe6d3c4d607a14fec41b570e45df8f3c85a43/pyvcloud/vcd/platform.py#L132)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Does this take care of url encoding? e.g. does it change characters like /,?etc to something like %E5% etc.
</blockquote></details>

Yes it does. That's why I'm using urllib.parse.quote_plus(obj_name). Ankit pointed me at this. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235)*

**Comment by ckolovson** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pyvcloud/vcd/platform.py, line 132 at r2](https://reviewable.io/reviews/vmware/pyvcloud/235#-LBWiGdq-6dSLPVrquGG:-LBXJN3_0kOd4soFANrR:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/8cbbe6d3c4d607a14fec41b570e45df8f3c85a43/pyvcloud/vcd/platform.py#L132)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

Yes it does. That's why I'm using urllib.parse.quote_plus(obj_name). Ankit pointed me at this. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235)*

**Comment by hodgesrm** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235)*

**Comment by ckolovson** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[pyvcloud/vcd/platform.py, line 127 at r2](https://reviewable.io/reviews/vmware/pyvcloud/235#-LBWgwjRBMllkz2MUrSm:-LBwssrp93lK3pUtAza7:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/8cbbe6d3c4d607a14fec41b570e45df8f3c85a43/pyvcloud/vcd/platform.py#L127)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This is too wild west-y. We should have an enum class which will contain all the object types in it. I am sure vCD can only fetch a handful of object types, so leaving this field open for all values is going to cause unnecessary confusion and headaches.

Please take a look at how we use rel type in  post_linked_resource()
</blockquote></details>

Done.

---

*[pyvcloud/vcd/platform.py, line 214 at r2](https://reviewable.io/reviews/vmware/pyvcloud/235#-LBWgkQ75cLbvjVkua-y:-LBwsuxnBgU_GRrHpy3-:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/8cbbe6d3c4d607a14fec41b570e45df8f3c85a43/pyvcloud/vcd/platform.py#L214)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We shouldn't be hard coding values like this. It will be better if we have an enum class which contains all the valid values.
</blockquote></details>

Done.

---

*[pyvcloud/vcd/platform.py, line 220 at r2](https://reviewable.io/reviews/vmware/pyvcloud/235#-LBWhf4W5M6dvowr2_cW:-LBwsw8x7FciZVfbaMFK:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/8cbbe6d3c4d607a14fec41b570e45df8f3c85a43/pyvcloud/vcd/platform.py#L220)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We shouldn't be hard coding these values.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235)*

**Comment by rocknes** [comment]
:lgtm:

Fix it and then ship it :)

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pyvcloud/vcd/client.py, line 108 at r4](https://reviewable.io/reviews/vmware/pyvcloud/235#-LC0jkXH1QQS_d8AgZEy:-LC0jkXH1QQS_d8AgZEz:bsksy15) ([raw file](https://github.com/vmware/pyvcloud/blob/f50554689eba626f690931b6663d1ad2ca6a235c/pyvcloud/vcd/client.py#L108)):*
> ```Python
>     'externalLocalization', 'externalNetwork', 'fileDescriptor',
>     'fromCloudTunnel', 'group', 'host', 'media', 'networkPool', 'nsxTManager',
>     'organization', 'orgNetwork', 'orgVdc', 'orgVdcNetwork',
> ```

I think we can get rid of this List, or change it's definition to something like 
https://stackoverflow.com/questions/29503339/how-to-get-all-values-from-python-enum-class

So that we don't have the constant values spelled out twice.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235#-:-LC0k_N0DeVpijzqTeRq:b-e5bvbz)*

**Comment by ckolovson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/client.py, line 108 at r4](https://reviewable.io/reviews/vmware/pyvcloud/235#-LC0jkXH1QQS_d8AgZEy:-LC0va7rEYzpVjywXgAq:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/f50554689eba626f690931b6663d1ad2ca6a235c/pyvcloud/vcd/client.py#L108)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think we can get rid of this List, or change it's definition to something like 
https://stackoverflow.com/questions/29503339/how-to-get-all-values-from-python-enum-class

So that we don't have the constant values spelled out twice.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/235)*

**Pull request merged**
