### PR TITLE
Query to get a single page response

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Add support to Abstract Query to return a single page response

Testing done:
Called the newly created function from CSE to get paginated response
Tested with invalid page number and pageSize (non existent page and negative values for page and pageSize)

@rocknes @sahithi @sakthisunda @ltimothy7 @ChintanShahVMware

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/724)

### CODE REVIEW

**Review by ltimothy7 — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/724#-:-MMWnNS63lr35EC5Myvp:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by rocknes — CHANGES_REQUESTED** [review]
Please fix the flake8 error

> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/724#-:-MN05BQ4EOam2kva_cff:b-8wvgp6)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[pyvcloud/vcd/client.py, line 1975 at r1](https://reviewable.io/reviews/vmware/pyvcloud/724#-MN063Vq3fpYWxCedP9z:-MN063VrCbs1Fmh88URX:b-34x0i9) ([raw file](https://github.com/vmware/pyvcloud/blob/1ac30584cf257d7be5a6ee12c5e22c8d2ebe6cda/pyvcloud/vcd/client.py#L1975)):*
> ```Python
>         return uri
> 
>     def get_single_page(self, page=1, page_size=25):
> ```

I think it will be better to just augment _init() method with `page` param. It will default to None, that will allow us to differentiate between if caller wants a random page or all results. If page is None, then we set it to 1 and set a bool to track that we want all results.

We get rid of this method, instead execute now looks at the bool set above, and decides whether it has to fetch one page or all results.

If only one page is being returned, instead of sending back a tuple or results and total number of items, we should send a dict back with
current page result, next link, prev link and total set size.

**Comment by Anirudh9794** [comment]
___
*[pyvcloud/vcd/client.py, line 1975 at r1](https://reviewable.io/reviews/vmware/pyvcloud/724#-MN063Vq3fpYWxCedP9z:-MNUBdLj1USVvIKmkXyX:b6hpt4i) ([raw file](https://github.com/vmware/pyvcloud/blob/1ac30584cf257d7be5a6ee12c5e22c8d2ebe6cda/pyvcloud/vcd/client.py#L1975)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think it will be better to just augment _init() method with `page` param. It will default to None, that will allow us to differentiate between if caller wants a random page or all results. If page is None, then we set it to 1 and set a bool to track that we want all results.

We get rid of this method, instead execute now looks at the bool set above, and decides whether it has to fetch one page or all results.

If only one page is being returned, instead of sending back a tuple or results and total number of items, we should send a dict back with
current page result, next link, prev link and total set size.

</blockquote></details>

Made changes in `execute()` to return a dictionary containing - resultTotal, nextPageUri, previousPageUri along with values if the `page` variable is set.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/724#-:-MNVinTWCgGVx7YaLgAC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

___
*[pyvcloud/vcd/client.py, line 1884 at r2](https://reviewable.io/reviews/vmware/pyvcloud/724#-MNVi8i_2GO8LNh3Hk6b:-MNVi8i_2GO8LNh3Hk6c:byvzzs1) ([raw file](https://github.com/vmware/pyvcloud/blob/1914f3223686f772558cb708c126cf2b1627e7c9/pyvcloud/vcd/client.py#L1884)):*
> ```Python
>         """Executes query and returns results.
> 
>         :return: If specific page number is not set. If a specific page number
> ```

Please remove the first sentence.

**Review by rocknes — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/724)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Pull request merged**
